/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IdCheckPermissionsTemplatesBody struct {
	// Target dir path
	TargetPath string `json:"target_path"`
	// Template view ID
	TemplateViewId int32 `json:"template_view_id"`
	// Template dir path
	TemplateDirPath string `json:"template_dir_path"`
	// Template file path
	TemplateFilePath string `json:"template_file_path,omitempty"`
}
