/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ClusterMaxPerformance struct {
	ReadBw int32 `json:"read_bw,omitempty"`
	WriteBw float32 `json:"write_bw,omitempty"`
	ReadIops int32 `json:"read_iops,omitempty"`
	WriteIops int32 `json:"write_iops,omitempty"`
}
