/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ProjectionCreateParams struct {
	// Name of the Database
	DatabaseName string `json:"database_name"`
	// Name of the Schema
	SchemaName string `json:"schema_name"`
	// Name of the Table
	TableName string `json:"table_name"`
	// Name of the object
	Name string `json:"name"`
	// Array of sorted column names
	SortedColumns []string `json:"sorted_columns"`
	// Array of unsorted column names
	UnsortedColumns []string `json:"unsorted_columns,omitempty"`
}
