/*
 * VAST API Swagger Schema
 *
 * VAST Management API definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type IdUpgradeSsdBody struct {
	// Forces upgrade regardless of version
	Force bool `json:"force,omitempty"`
}
