/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// SnapshotpoliciesAPIService SnapshotpoliciesAPI service
type SnapshotpoliciesAPIService service

type SnapshotpoliciesAPISnapshotpoliciesCreateRequest struct {
	ctx context.Context
	ApiService *SnapshotpoliciesAPIService
	snapshotpolicyCreateParams *SnapshotpoliciesCreateRequest
}

func (r SnapshotpoliciesAPISnapshotpoliciesCreateRequest) SnapshotpolicyCreateParams(snapshotpolicyCreateParams SnapshotpoliciesCreateRequest) SnapshotpoliciesAPISnapshotpoliciesCreateRequest {
	r.snapshotpolicyCreateParams = &snapshotpolicyCreateParams
	return r
}

func (r SnapshotpoliciesAPISnapshotpoliciesCreateRequest) Execute() (*SnapshotPolicy, *http.Response, error) {
	return r.ApiService.SnapshotpoliciesCreateExecute(r)
}

/*
SnapshotpoliciesCreate Create a Snapshot Policy (deprecated from VAST Cluster 3.4)

This endpoint creates a snapshot policy. It is deprecated from VAST Cluster 3.4. Use /protectionpolicies/.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return SnapshotpoliciesAPISnapshotpoliciesCreateRequest
*/
func (a *SnapshotpoliciesAPIService) SnapshotpoliciesCreate(ctx context.Context) SnapshotpoliciesAPISnapshotpoliciesCreateRequest {
	return SnapshotpoliciesAPISnapshotpoliciesCreateRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return SnapshotPolicy
func (a *SnapshotpoliciesAPIService) SnapshotpoliciesCreateExecute(r SnapshotpoliciesAPISnapshotpoliciesCreateRequest) (*SnapshotPolicy, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SnapshotPolicy
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SnapshotpoliciesAPIService.SnapshotpoliciesCreate")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/snapshotpolicies/"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.snapshotpolicyCreateParams
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type SnapshotpoliciesAPISnapshotpoliciesDeleteRequest struct {
	ctx context.Context
	ApiService *SnapshotpoliciesAPIService
	id string
}

func (r SnapshotpoliciesAPISnapshotpoliciesDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.SnapshotpoliciesDeleteExecute(r)
}

/*
SnapshotpoliciesDelete Delete a Snapshot Policy (deprecated from VAST Cluster 3.4)

This endpoint deletes a snapshot policy. It is deprecated from VAST Cluster 3.4. Use /protectionpolicies/.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return SnapshotpoliciesAPISnapshotpoliciesDeleteRequest
*/
func (a *SnapshotpoliciesAPIService) SnapshotpoliciesDelete(ctx context.Context, id string) SnapshotpoliciesAPISnapshotpoliciesDeleteRequest {
	return SnapshotpoliciesAPISnapshotpoliciesDeleteRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *SnapshotpoliciesAPIService) SnapshotpoliciesDeleteExecute(r SnapshotpoliciesAPISnapshotpoliciesDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SnapshotpoliciesAPIService.SnapshotpoliciesDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/snapshotpolicies/{id}/"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type SnapshotpoliciesAPISnapshotpoliciesListRequest struct {
	ctx context.Context
	ApiService *SnapshotpoliciesAPIService
	path *string
	lastOperationState *string
	schedule *string
	enabled *bool
}

// Filter by snapshot path
func (r SnapshotpoliciesAPISnapshotpoliciesListRequest) Path(path string) SnapshotpoliciesAPISnapshotpoliciesListRequest {
	r.path = &path
	return r
}

// Filter by last operation state
func (r SnapshotpoliciesAPISnapshotpoliciesListRequest) LastOperationState(lastOperationState string) SnapshotpoliciesAPISnapshotpoliciesListRequest {
	r.lastOperationState = &lastOperationState
	return r
}

// Filter by schedule
func (r SnapshotpoliciesAPISnapshotpoliciesListRequest) Schedule(schedule string) SnapshotpoliciesAPISnapshotpoliciesListRequest {
	r.schedule = &schedule
	return r
}

// Filter to return only enabled snapshots
func (r SnapshotpoliciesAPISnapshotpoliciesListRequest) Enabled(enabled bool) SnapshotpoliciesAPISnapshotpoliciesListRequest {
	r.enabled = &enabled
	return r
}

func (r SnapshotpoliciesAPISnapshotpoliciesListRequest) Execute() ([]SnapshotPolicy, *http.Response, error) {
	return r.ApiService.SnapshotpoliciesListExecute(r)
}

/*
SnapshotpoliciesList List Snapshot Policies (deprecated from VAST Cluster 3.4)

This endpoint returns the list of snapshot policies. The list can be filtered. It is deprecated from VAST Cluster 3.4. Use /protectionpolicies/.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return SnapshotpoliciesAPISnapshotpoliciesListRequest
*/
func (a *SnapshotpoliciesAPIService) SnapshotpoliciesList(ctx context.Context) SnapshotpoliciesAPISnapshotpoliciesListRequest {
	return SnapshotpoliciesAPISnapshotpoliciesListRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []SnapshotPolicy
func (a *SnapshotpoliciesAPIService) SnapshotpoliciesListExecute(r SnapshotpoliciesAPISnapshotpoliciesListRequest) ([]SnapshotPolicy, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []SnapshotPolicy
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SnapshotpoliciesAPIService.SnapshotpoliciesList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/snapshotpolicies/"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.path != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "path", r.path, "")
	}
	if r.lastOperationState != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "last_operation_state", r.lastOperationState, "")
	}
	if r.schedule != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "schedule", r.schedule, "")
	}
	if r.enabled != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "enabled", r.enabled, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type SnapshotpoliciesAPISnapshotpoliciesPartialUpdateRequest struct {
	ctx context.Context
	ApiService *SnapshotpoliciesAPIService
	id string
	snapshotpolicyModifyParams *SnapshotpoliciesPartialUpdateRequest
}

func (r SnapshotpoliciesAPISnapshotpoliciesPartialUpdateRequest) SnapshotpolicyModifyParams(snapshotpolicyModifyParams SnapshotpoliciesPartialUpdateRequest) SnapshotpoliciesAPISnapshotpoliciesPartialUpdateRequest {
	r.snapshotpolicyModifyParams = &snapshotpolicyModifyParams
	return r
}

func (r SnapshotpoliciesAPISnapshotpoliciesPartialUpdateRequest) Execute() (*http.Response, error) {
	return r.ApiService.SnapshotpoliciesPartialUpdateExecute(r)
}

/*
SnapshotpoliciesPartialUpdate Modify a Snapshot Policy (deprecated from VAST Cluster 3.4)

This endpoint modifies a snapshot policy. It is deprecated from VAST Cluster 3.4. Use /protectionpolicies/.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return SnapshotpoliciesAPISnapshotpoliciesPartialUpdateRequest
*/
func (a *SnapshotpoliciesAPIService) SnapshotpoliciesPartialUpdate(ctx context.Context, id string) SnapshotpoliciesAPISnapshotpoliciesPartialUpdateRequest {
	return SnapshotpoliciesAPISnapshotpoliciesPartialUpdateRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
func (a *SnapshotpoliciesAPIService) SnapshotpoliciesPartialUpdateExecute(r SnapshotpoliciesAPISnapshotpoliciesPartialUpdateRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SnapshotpoliciesAPIService.SnapshotpoliciesPartialUpdate")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/snapshotpolicies/{id}/"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.snapshotpolicyModifyParams
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type SnapshotpoliciesAPISnapshotpoliciesReadRequest struct {
	ctx context.Context
	ApiService *SnapshotpoliciesAPIService
	id string
}

func (r SnapshotpoliciesAPISnapshotpoliciesReadRequest) Execute() (*SnapshotPolicy, *http.Response, error) {
	return r.ApiService.SnapshotpoliciesReadExecute(r)
}

/*
SnapshotpoliciesRead Return Details of a Snapshot Policy (deprecated from VAST Cluster 3.4)

This endpoint returns details of a snapshot policy. It is deprecated from VAST Cluster 3.4. Use /protectionpolicies/.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param id
 @return SnapshotpoliciesAPISnapshotpoliciesReadRequest
*/
func (a *SnapshotpoliciesAPIService) SnapshotpoliciesRead(ctx context.Context, id string) SnapshotpoliciesAPISnapshotpoliciesReadRequest {
	return SnapshotpoliciesAPISnapshotpoliciesReadRequest{
		ApiService: a,
		ctx: ctx,
		id: id,
	}
}

// Execute executes the request
//  @return SnapshotPolicy
func (a *SnapshotpoliciesAPIService) SnapshotpoliciesReadExecute(r SnapshotpoliciesAPISnapshotpoliciesReadRequest) (*SnapshotPolicy, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SnapshotPolicy
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SnapshotpoliciesAPIService.SnapshotpoliciesRead")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/snapshotpolicies/{id}/"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
