/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


// EncryptiongroupsAPIService EncryptiongroupsAPI service
type EncryptiongroupsAPIService service

type EncryptiongroupsAPIEncryptiongroupsListRequest struct {
	ctx context.Context
	ApiService *EncryptiongroupsAPIService
	page *int32
	pageSize *int32
}

func (r EncryptiongroupsAPIEncryptiongroupsListRequest) Page(page int32) EncryptiongroupsAPIEncryptiongroupsListRequest {
	r.page = &page
	return r
}

func (r EncryptiongroupsAPIEncryptiongroupsListRequest) PageSize(pageSize int32) EncryptiongroupsAPIEncryptiongroupsListRequest {
	r.pageSize = &pageSize
	return r
}

func (r EncryptiongroupsAPIEncryptiongroupsListRequest) Execute() ([]EncryptionGroup, *http.Response, error) {
	return r.ApiService.EncryptiongroupsListExecute(r)
}

/*
EncryptiongroupsList List Encryption Groups

This endpoint lists Encryption Groups.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return EncryptiongroupsAPIEncryptiongroupsListRequest
*/
func (a *EncryptiongroupsAPIService) EncryptiongroupsList(ctx context.Context) EncryptiongroupsAPIEncryptiongroupsListRequest {
	return EncryptiongroupsAPIEncryptiongroupsListRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []EncryptionGroup
func (a *EncryptiongroupsAPIService) EncryptiongroupsListExecute(r EncryptiongroupsAPIEncryptiongroupsListRequest) ([]EncryptionGroup, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []EncryptionGroup
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "EncryptiongroupsAPIService.EncryptiongroupsList")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/encryptiongroups/"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "")
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page_size", r.pageSize, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"*/*"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
