/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProtectedpathsPauseRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProtectedpathsPauseRequest{}

// ProtectedpathsPauseRequest struct for ProtectedpathsPauseRequest
type ProtectedpathsPauseRequest struct {
	// Set to False to pause snapshot restore
	Enabled *bool `json:"enabled,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProtectedpathsPauseRequest ProtectedpathsPauseRequest

// NewProtectedpathsPauseRequest instantiates a new ProtectedpathsPauseRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtectedpathsPauseRequest() *ProtectedpathsPauseRequest {
	this := ProtectedpathsPauseRequest{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// NewProtectedpathsPauseRequestWithDefaults instantiates a new ProtectedpathsPauseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtectedpathsPauseRequestWithDefaults() *ProtectedpathsPauseRequest {
	this := ProtectedpathsPauseRequest{}
	var enabled bool = false
	this.Enabled = &enabled
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ProtectedpathsPauseRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectedpathsPauseRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ProtectedpathsPauseRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ProtectedpathsPauseRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o ProtectedpathsPauseRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProtectedpathsPauseRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProtectedpathsPauseRequest) UnmarshalJSON(data []byte) (err error) {
	varProtectedpathsPauseRequest := _ProtectedpathsPauseRequest{}

	err = json.Unmarshal(data, &varProtectedpathsPauseRequest)

	if err != nil {
		return err
	}

	*o = ProtectedpathsPauseRequest(varProtectedpathsPauseRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "enabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProtectedpathsPauseRequest struct {
	value *ProtectedpathsPauseRequest
	isSet bool
}

func (v NullableProtectedpathsPauseRequest) Get() *ProtectedpathsPauseRequest {
	return v.value
}

func (v *NullableProtectedpathsPauseRequest) Set(val *ProtectedpathsPauseRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProtectedpathsPauseRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProtectedpathsPauseRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtectedpathsPauseRequest(val *ProtectedpathsPauseRequest) *NullableProtectedpathsPauseRequest {
	return &NullableProtectedpathsPauseRequest{value: val, isSet: true}
}

func (v NullableProtectedpathsPauseRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtectedpathsPauseRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


