/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the AddBoxesCBoxesHostsParamsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddBoxesCBoxesHostsParamsInner{}

// AddBoxesCBoxesHostsParamsInner struct for AddBoxesCBoxesHostsParamsInner
type AddBoxesCBoxesHostsParamsInner struct {
	Id int32 `json:"id"`
	NetType string `json:"net_type"`
	// relevant only for large subnet
	NbEthMtu *int32 `json:"nb_eth_mtu,omitempty"`
	// relevant only for large subnet
	NbIbMtu *int32 `json:"nb_ib_mtu,omitempty"`
	// relevant only for large subnet
	NbIbMode *string `json:"nb_ib_mode,omitempty"`
	ReverseNics bool `json:"reverse_nics"`
	SkipNic string `json:"skip_nic"`
	AdditionalProperties map[string]interface{}
}

type _AddBoxesCBoxesHostsParamsInner AddBoxesCBoxesHostsParamsInner

// NewAddBoxesCBoxesHostsParamsInner instantiates a new AddBoxesCBoxesHostsParamsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddBoxesCBoxesHostsParamsInner(id int32, netType string, reverseNics bool, skipNic string) *AddBoxesCBoxesHostsParamsInner {
	this := AddBoxesCBoxesHostsParamsInner{}
	this.Id = id
	this.NetType = netType
	this.ReverseNics = reverseNics
	this.SkipNic = skipNic
	return &this
}

// NewAddBoxesCBoxesHostsParamsInnerWithDefaults instantiates a new AddBoxesCBoxesHostsParamsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddBoxesCBoxesHostsParamsInnerWithDefaults() *AddBoxesCBoxesHostsParamsInner {
	this := AddBoxesCBoxesHostsParamsInner{}
	var reverseNics bool = false
	this.ReverseNics = reverseNics
	return &this
}

// GetId returns the Id field value
func (o *AddBoxesCBoxesHostsParamsInner) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AddBoxesCBoxesHostsParamsInner) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AddBoxesCBoxesHostsParamsInner) SetId(v int32) {
	o.Id = v
}

// GetNetType returns the NetType field value
func (o *AddBoxesCBoxesHostsParamsInner) GetNetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NetType
}

// GetNetTypeOk returns a tuple with the NetType field value
// and a boolean to check if the value has been set.
func (o *AddBoxesCBoxesHostsParamsInner) GetNetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetType, true
}

// SetNetType sets field value
func (o *AddBoxesCBoxesHostsParamsInner) SetNetType(v string) {
	o.NetType = v
}

// GetNbEthMtu returns the NbEthMtu field value if set, zero value otherwise.
func (o *AddBoxesCBoxesHostsParamsInner) GetNbEthMtu() int32 {
	if o == nil || IsNil(o.NbEthMtu) {
		var ret int32
		return ret
	}
	return *o.NbEthMtu
}

// GetNbEthMtuOk returns a tuple with the NbEthMtu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddBoxesCBoxesHostsParamsInner) GetNbEthMtuOk() (*int32, bool) {
	if o == nil || IsNil(o.NbEthMtu) {
		return nil, false
	}
	return o.NbEthMtu, true
}

// HasNbEthMtu returns a boolean if a field has been set.
func (o *AddBoxesCBoxesHostsParamsInner) HasNbEthMtu() bool {
	if o != nil && !IsNil(o.NbEthMtu) {
		return true
	}

	return false
}

// SetNbEthMtu gets a reference to the given int32 and assigns it to the NbEthMtu field.
func (o *AddBoxesCBoxesHostsParamsInner) SetNbEthMtu(v int32) {
	o.NbEthMtu = &v
}

// GetNbIbMtu returns the NbIbMtu field value if set, zero value otherwise.
func (o *AddBoxesCBoxesHostsParamsInner) GetNbIbMtu() int32 {
	if o == nil || IsNil(o.NbIbMtu) {
		var ret int32
		return ret
	}
	return *o.NbIbMtu
}

// GetNbIbMtuOk returns a tuple with the NbIbMtu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddBoxesCBoxesHostsParamsInner) GetNbIbMtuOk() (*int32, bool) {
	if o == nil || IsNil(o.NbIbMtu) {
		return nil, false
	}
	return o.NbIbMtu, true
}

// HasNbIbMtu returns a boolean if a field has been set.
func (o *AddBoxesCBoxesHostsParamsInner) HasNbIbMtu() bool {
	if o != nil && !IsNil(o.NbIbMtu) {
		return true
	}

	return false
}

// SetNbIbMtu gets a reference to the given int32 and assigns it to the NbIbMtu field.
func (o *AddBoxesCBoxesHostsParamsInner) SetNbIbMtu(v int32) {
	o.NbIbMtu = &v
}

// GetNbIbMode returns the NbIbMode field value if set, zero value otherwise.
func (o *AddBoxesCBoxesHostsParamsInner) GetNbIbMode() string {
	if o == nil || IsNil(o.NbIbMode) {
		var ret string
		return ret
	}
	return *o.NbIbMode
}

// GetNbIbModeOk returns a tuple with the NbIbMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddBoxesCBoxesHostsParamsInner) GetNbIbModeOk() (*string, bool) {
	if o == nil || IsNil(o.NbIbMode) {
		return nil, false
	}
	return o.NbIbMode, true
}

// HasNbIbMode returns a boolean if a field has been set.
func (o *AddBoxesCBoxesHostsParamsInner) HasNbIbMode() bool {
	if o != nil && !IsNil(o.NbIbMode) {
		return true
	}

	return false
}

// SetNbIbMode gets a reference to the given string and assigns it to the NbIbMode field.
func (o *AddBoxesCBoxesHostsParamsInner) SetNbIbMode(v string) {
	o.NbIbMode = &v
}

// GetReverseNics returns the ReverseNics field value
func (o *AddBoxesCBoxesHostsParamsInner) GetReverseNics() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ReverseNics
}

// GetReverseNicsOk returns a tuple with the ReverseNics field value
// and a boolean to check if the value has been set.
func (o *AddBoxesCBoxesHostsParamsInner) GetReverseNicsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReverseNics, true
}

// SetReverseNics sets field value
func (o *AddBoxesCBoxesHostsParamsInner) SetReverseNics(v bool) {
	o.ReverseNics = v
}

// GetSkipNic returns the SkipNic field value
func (o *AddBoxesCBoxesHostsParamsInner) GetSkipNic() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SkipNic
}

// GetSkipNicOk returns a tuple with the SkipNic field value
// and a boolean to check if the value has been set.
func (o *AddBoxesCBoxesHostsParamsInner) GetSkipNicOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SkipNic, true
}

// SetSkipNic sets field value
func (o *AddBoxesCBoxesHostsParamsInner) SetSkipNic(v string) {
	o.SkipNic = v
}

func (o AddBoxesCBoxesHostsParamsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddBoxesCBoxesHostsParamsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["net_type"] = o.NetType
	if !IsNil(o.NbEthMtu) {
		toSerialize["nb_eth_mtu"] = o.NbEthMtu
	}
	if !IsNil(o.NbIbMtu) {
		toSerialize["nb_ib_mtu"] = o.NbIbMtu
	}
	if !IsNil(o.NbIbMode) {
		toSerialize["nb_ib_mode"] = o.NbIbMode
	}
	toSerialize["reverse_nics"] = o.ReverseNics
	toSerialize["skip_nic"] = o.SkipNic

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AddBoxesCBoxesHostsParamsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"net_type",
		"reverse_nics",
		"skip_nic",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddBoxesCBoxesHostsParamsInner := _AddBoxesCBoxesHostsParamsInner{}

	err = json.Unmarshal(data, &varAddBoxesCBoxesHostsParamsInner)

	if err != nil {
		return err
	}

	*o = AddBoxesCBoxesHostsParamsInner(varAddBoxesCBoxesHostsParamsInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "net_type")
		delete(additionalProperties, "nb_eth_mtu")
		delete(additionalProperties, "nb_ib_mtu")
		delete(additionalProperties, "nb_ib_mode")
		delete(additionalProperties, "reverse_nics")
		delete(additionalProperties, "skip_nic")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAddBoxesCBoxesHostsParamsInner struct {
	value *AddBoxesCBoxesHostsParamsInner
	isSet bool
}

func (v NullableAddBoxesCBoxesHostsParamsInner) Get() *AddBoxesCBoxesHostsParamsInner {
	return v.value
}

func (v *NullableAddBoxesCBoxesHostsParamsInner) Set(val *AddBoxesCBoxesHostsParamsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAddBoxesCBoxesHostsParamsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAddBoxesCBoxesHostsParamsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddBoxesCBoxesHostsParamsInner(val *AddBoxesCBoxesHostsParamsInner) *NullableAddBoxesCBoxesHostsParamsInner {
	return &NullableAddBoxesCBoxesHostsParamsInner{value: val, isSet: true}
}

func (v NullableAddBoxesCBoxesHostsParamsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddBoxesCBoxesHostsParamsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


