/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the DynamicConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DynamicConfig{}

// DynamicConfig struct for DynamicConfig
type DynamicConfig struct {
	// Dynamic Config Key
	Key string `json:"key"`
	// Dynamic Config Value
	Value *string `json:"value,omitempty"`
	// Dynamic Config is modified flag
	IsModified bool `json:"is_modified"`
	AdditionalProperties map[string]interface{}
}

type _DynamicConfig DynamicConfig

// NewDynamicConfig instantiates a new DynamicConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDynamicConfig(key string, isModified bool) *DynamicConfig {
	this := DynamicConfig{}
	this.Key = key
	this.IsModified = isModified
	return &this
}

// NewDynamicConfigWithDefaults instantiates a new DynamicConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDynamicConfigWithDefaults() *DynamicConfig {
	this := DynamicConfig{}
	return &this
}

// GetKey returns the Key field value
func (o *DynamicConfig) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *DynamicConfig) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *DynamicConfig) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *DynamicConfig) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DynamicConfig) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *DynamicConfig) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *DynamicConfig) SetValue(v string) {
	o.Value = &v
}

// GetIsModified returns the IsModified field value
func (o *DynamicConfig) GetIsModified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsModified
}

// GetIsModifiedOk returns a tuple with the IsModified field value
// and a boolean to check if the value has been set.
func (o *DynamicConfig) GetIsModifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsModified, true
}

// SetIsModified sets field value
func (o *DynamicConfig) SetIsModified(v bool) {
	o.IsModified = v
}

func (o DynamicConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DynamicConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	toSerialize["is_modified"] = o.IsModified

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DynamicConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"is_modified",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDynamicConfig := _DynamicConfig{}

	err = json.Unmarshal(data, &varDynamicConfig)

	if err != nil {
		return err
	}

	*o = DynamicConfig(varDynamicConfig)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "key")
		delete(additionalProperties, "value")
		delete(additionalProperties, "is_modified")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDynamicConfig struct {
	value *DynamicConfig
	isSet bool
}

func (v NullableDynamicConfig) Get() *DynamicConfig {
	return v.value
}

func (v *NullableDynamicConfig) Set(val *DynamicConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableDynamicConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableDynamicConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDynamicConfig(val *DynamicConfig) *NullableDynamicConfig {
	return &NullableDynamicConfig{value: val, isSet: true}
}

func (v NullableDynamicConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDynamicConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


