/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RequestQOSStaticLimits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestQOSStaticLimits{}

// RequestQOSStaticLimits struct for RequestQOSStaticLimits
type RequestQOSStaticLimits struct {
	// Minimal amount of performance to provide when there is resource contention
	MinReadsBwMbps *int32 `json:"min_reads_bw_mbps,omitempty"`
	// Maximal amount of performance to provide when there is no resource contention
	MaxReadsBwMbps *int32 `json:"max_reads_bw_mbps,omitempty"`
	// Minimal amount of performance to provide when there is resource contention
	MinWritesBwMbps *int32 `json:"min_writes_bw_mbps,omitempty"`
	// Maximal amount of performance to provide when there is no resource contention
	MaxWritesBwMbps *int32 `json:"max_writes_bw_mbps,omitempty"`
	// Minimal amount of performance to provide when there is resource contention
	MinReadsIops *int32 `json:"min_reads_iops,omitempty"`
	// Maximal amount of performance to provide when there is no resource contention
	MaxReadsIops *int32 `json:"max_reads_iops,omitempty"`
	// Minimal amount of performance to provide when there is resource contention
	MinWritesIops *int32 `json:"min_writes_iops,omitempty"`
	// Maximal amount of performance to provide when there is no resource contention
	MaxWritesIops *int32 `json:"max_writes_iops,omitempty"`
	// Burst reads BW Mb
	BurstReadsBwMb *int32 `json:"burst_reads_bw_mb,omitempty"`
	// Burst writes BW Mb
	BurstWritesBwMb *int32 `json:"burst_writes_bw_mb,omitempty"`
	// Burst reads loan Mb
	BurstReadsLoanMb *int32 `json:"burst_reads_loan_mb,omitempty"`
	// Burst writes loan Mb
	BurstWritesLoanMb *int32 `json:"burst_writes_loan_mb,omitempty"`
	// Burst reads IOPS
	BurstReadsIops *int32 `json:"burst_reads_iops,omitempty"`
	// Burst writes IOPS
	BurstWritesIops *int32 `json:"burst_writes_iops,omitempty"`
	// Burst reads loan IOPS
	BurstReadsLoanIops *int32 `json:"burst_reads_loan_iops,omitempty"`
	// Burst writes loan IOPS
	BurstWritesLoanIops *int32 `json:"burst_writes_loan_iops,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RequestQOSStaticLimits RequestQOSStaticLimits

// NewRequestQOSStaticLimits instantiates a new RequestQOSStaticLimits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestQOSStaticLimits() *RequestQOSStaticLimits {
	this := RequestQOSStaticLimits{}
	return &this
}

// NewRequestQOSStaticLimitsWithDefaults instantiates a new RequestQOSStaticLimits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestQOSStaticLimitsWithDefaults() *RequestQOSStaticLimits {
	this := RequestQOSStaticLimits{}
	return &this
}

// GetMinReadsBwMbps returns the MinReadsBwMbps field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetMinReadsBwMbps() int32 {
	if o == nil || IsNil(o.MinReadsBwMbps) {
		var ret int32
		return ret
	}
	return *o.MinReadsBwMbps
}

// GetMinReadsBwMbpsOk returns a tuple with the MinReadsBwMbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetMinReadsBwMbpsOk() (*int32, bool) {
	if o == nil || IsNil(o.MinReadsBwMbps) {
		return nil, false
	}
	return o.MinReadsBwMbps, true
}

// HasMinReadsBwMbps returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasMinReadsBwMbps() bool {
	if o != nil && !IsNil(o.MinReadsBwMbps) {
		return true
	}

	return false
}

// SetMinReadsBwMbps gets a reference to the given int32 and assigns it to the MinReadsBwMbps field.
func (o *RequestQOSStaticLimits) SetMinReadsBwMbps(v int32) {
	o.MinReadsBwMbps = &v
}

// GetMaxReadsBwMbps returns the MaxReadsBwMbps field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetMaxReadsBwMbps() int32 {
	if o == nil || IsNil(o.MaxReadsBwMbps) {
		var ret int32
		return ret
	}
	return *o.MaxReadsBwMbps
}

// GetMaxReadsBwMbpsOk returns a tuple with the MaxReadsBwMbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetMaxReadsBwMbpsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxReadsBwMbps) {
		return nil, false
	}
	return o.MaxReadsBwMbps, true
}

// HasMaxReadsBwMbps returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasMaxReadsBwMbps() bool {
	if o != nil && !IsNil(o.MaxReadsBwMbps) {
		return true
	}

	return false
}

// SetMaxReadsBwMbps gets a reference to the given int32 and assigns it to the MaxReadsBwMbps field.
func (o *RequestQOSStaticLimits) SetMaxReadsBwMbps(v int32) {
	o.MaxReadsBwMbps = &v
}

// GetMinWritesBwMbps returns the MinWritesBwMbps field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetMinWritesBwMbps() int32 {
	if o == nil || IsNil(o.MinWritesBwMbps) {
		var ret int32
		return ret
	}
	return *o.MinWritesBwMbps
}

// GetMinWritesBwMbpsOk returns a tuple with the MinWritesBwMbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetMinWritesBwMbpsOk() (*int32, bool) {
	if o == nil || IsNil(o.MinWritesBwMbps) {
		return nil, false
	}
	return o.MinWritesBwMbps, true
}

// HasMinWritesBwMbps returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasMinWritesBwMbps() bool {
	if o != nil && !IsNil(o.MinWritesBwMbps) {
		return true
	}

	return false
}

// SetMinWritesBwMbps gets a reference to the given int32 and assigns it to the MinWritesBwMbps field.
func (o *RequestQOSStaticLimits) SetMinWritesBwMbps(v int32) {
	o.MinWritesBwMbps = &v
}

// GetMaxWritesBwMbps returns the MaxWritesBwMbps field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetMaxWritesBwMbps() int32 {
	if o == nil || IsNil(o.MaxWritesBwMbps) {
		var ret int32
		return ret
	}
	return *o.MaxWritesBwMbps
}

// GetMaxWritesBwMbpsOk returns a tuple with the MaxWritesBwMbps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetMaxWritesBwMbpsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxWritesBwMbps) {
		return nil, false
	}
	return o.MaxWritesBwMbps, true
}

// HasMaxWritesBwMbps returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasMaxWritesBwMbps() bool {
	if o != nil && !IsNil(o.MaxWritesBwMbps) {
		return true
	}

	return false
}

// SetMaxWritesBwMbps gets a reference to the given int32 and assigns it to the MaxWritesBwMbps field.
func (o *RequestQOSStaticLimits) SetMaxWritesBwMbps(v int32) {
	o.MaxWritesBwMbps = &v
}

// GetMinReadsIops returns the MinReadsIops field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetMinReadsIops() int32 {
	if o == nil || IsNil(o.MinReadsIops) {
		var ret int32
		return ret
	}
	return *o.MinReadsIops
}

// GetMinReadsIopsOk returns a tuple with the MinReadsIops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetMinReadsIopsOk() (*int32, bool) {
	if o == nil || IsNil(o.MinReadsIops) {
		return nil, false
	}
	return o.MinReadsIops, true
}

// HasMinReadsIops returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasMinReadsIops() bool {
	if o != nil && !IsNil(o.MinReadsIops) {
		return true
	}

	return false
}

// SetMinReadsIops gets a reference to the given int32 and assigns it to the MinReadsIops field.
func (o *RequestQOSStaticLimits) SetMinReadsIops(v int32) {
	o.MinReadsIops = &v
}

// GetMaxReadsIops returns the MaxReadsIops field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetMaxReadsIops() int32 {
	if o == nil || IsNil(o.MaxReadsIops) {
		var ret int32
		return ret
	}
	return *o.MaxReadsIops
}

// GetMaxReadsIopsOk returns a tuple with the MaxReadsIops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetMaxReadsIopsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxReadsIops) {
		return nil, false
	}
	return o.MaxReadsIops, true
}

// HasMaxReadsIops returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasMaxReadsIops() bool {
	if o != nil && !IsNil(o.MaxReadsIops) {
		return true
	}

	return false
}

// SetMaxReadsIops gets a reference to the given int32 and assigns it to the MaxReadsIops field.
func (o *RequestQOSStaticLimits) SetMaxReadsIops(v int32) {
	o.MaxReadsIops = &v
}

// GetMinWritesIops returns the MinWritesIops field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetMinWritesIops() int32 {
	if o == nil || IsNil(o.MinWritesIops) {
		var ret int32
		return ret
	}
	return *o.MinWritesIops
}

// GetMinWritesIopsOk returns a tuple with the MinWritesIops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetMinWritesIopsOk() (*int32, bool) {
	if o == nil || IsNil(o.MinWritesIops) {
		return nil, false
	}
	return o.MinWritesIops, true
}

// HasMinWritesIops returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasMinWritesIops() bool {
	if o != nil && !IsNil(o.MinWritesIops) {
		return true
	}

	return false
}

// SetMinWritesIops gets a reference to the given int32 and assigns it to the MinWritesIops field.
func (o *RequestQOSStaticLimits) SetMinWritesIops(v int32) {
	o.MinWritesIops = &v
}

// GetMaxWritesIops returns the MaxWritesIops field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetMaxWritesIops() int32 {
	if o == nil || IsNil(o.MaxWritesIops) {
		var ret int32
		return ret
	}
	return *o.MaxWritesIops
}

// GetMaxWritesIopsOk returns a tuple with the MaxWritesIops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetMaxWritesIopsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxWritesIops) {
		return nil, false
	}
	return o.MaxWritesIops, true
}

// HasMaxWritesIops returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasMaxWritesIops() bool {
	if o != nil && !IsNil(o.MaxWritesIops) {
		return true
	}

	return false
}

// SetMaxWritesIops gets a reference to the given int32 and assigns it to the MaxWritesIops field.
func (o *RequestQOSStaticLimits) SetMaxWritesIops(v int32) {
	o.MaxWritesIops = &v
}

// GetBurstReadsBwMb returns the BurstReadsBwMb field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetBurstReadsBwMb() int32 {
	if o == nil || IsNil(o.BurstReadsBwMb) {
		var ret int32
		return ret
	}
	return *o.BurstReadsBwMb
}

// GetBurstReadsBwMbOk returns a tuple with the BurstReadsBwMb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetBurstReadsBwMbOk() (*int32, bool) {
	if o == nil || IsNil(o.BurstReadsBwMb) {
		return nil, false
	}
	return o.BurstReadsBwMb, true
}

// HasBurstReadsBwMb returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasBurstReadsBwMb() bool {
	if o != nil && !IsNil(o.BurstReadsBwMb) {
		return true
	}

	return false
}

// SetBurstReadsBwMb gets a reference to the given int32 and assigns it to the BurstReadsBwMb field.
func (o *RequestQOSStaticLimits) SetBurstReadsBwMb(v int32) {
	o.BurstReadsBwMb = &v
}

// GetBurstWritesBwMb returns the BurstWritesBwMb field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetBurstWritesBwMb() int32 {
	if o == nil || IsNil(o.BurstWritesBwMb) {
		var ret int32
		return ret
	}
	return *o.BurstWritesBwMb
}

// GetBurstWritesBwMbOk returns a tuple with the BurstWritesBwMb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetBurstWritesBwMbOk() (*int32, bool) {
	if o == nil || IsNil(o.BurstWritesBwMb) {
		return nil, false
	}
	return o.BurstWritesBwMb, true
}

// HasBurstWritesBwMb returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasBurstWritesBwMb() bool {
	if o != nil && !IsNil(o.BurstWritesBwMb) {
		return true
	}

	return false
}

// SetBurstWritesBwMb gets a reference to the given int32 and assigns it to the BurstWritesBwMb field.
func (o *RequestQOSStaticLimits) SetBurstWritesBwMb(v int32) {
	o.BurstWritesBwMb = &v
}

// GetBurstReadsLoanMb returns the BurstReadsLoanMb field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetBurstReadsLoanMb() int32 {
	if o == nil || IsNil(o.BurstReadsLoanMb) {
		var ret int32
		return ret
	}
	return *o.BurstReadsLoanMb
}

// GetBurstReadsLoanMbOk returns a tuple with the BurstReadsLoanMb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetBurstReadsLoanMbOk() (*int32, bool) {
	if o == nil || IsNil(o.BurstReadsLoanMb) {
		return nil, false
	}
	return o.BurstReadsLoanMb, true
}

// HasBurstReadsLoanMb returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasBurstReadsLoanMb() bool {
	if o != nil && !IsNil(o.BurstReadsLoanMb) {
		return true
	}

	return false
}

// SetBurstReadsLoanMb gets a reference to the given int32 and assigns it to the BurstReadsLoanMb field.
func (o *RequestQOSStaticLimits) SetBurstReadsLoanMb(v int32) {
	o.BurstReadsLoanMb = &v
}

// GetBurstWritesLoanMb returns the BurstWritesLoanMb field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetBurstWritesLoanMb() int32 {
	if o == nil || IsNil(o.BurstWritesLoanMb) {
		var ret int32
		return ret
	}
	return *o.BurstWritesLoanMb
}

// GetBurstWritesLoanMbOk returns a tuple with the BurstWritesLoanMb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetBurstWritesLoanMbOk() (*int32, bool) {
	if o == nil || IsNil(o.BurstWritesLoanMb) {
		return nil, false
	}
	return o.BurstWritesLoanMb, true
}

// HasBurstWritesLoanMb returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasBurstWritesLoanMb() bool {
	if o != nil && !IsNil(o.BurstWritesLoanMb) {
		return true
	}

	return false
}

// SetBurstWritesLoanMb gets a reference to the given int32 and assigns it to the BurstWritesLoanMb field.
func (o *RequestQOSStaticLimits) SetBurstWritesLoanMb(v int32) {
	o.BurstWritesLoanMb = &v
}

// GetBurstReadsIops returns the BurstReadsIops field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetBurstReadsIops() int32 {
	if o == nil || IsNil(o.BurstReadsIops) {
		var ret int32
		return ret
	}
	return *o.BurstReadsIops
}

// GetBurstReadsIopsOk returns a tuple with the BurstReadsIops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetBurstReadsIopsOk() (*int32, bool) {
	if o == nil || IsNil(o.BurstReadsIops) {
		return nil, false
	}
	return o.BurstReadsIops, true
}

// HasBurstReadsIops returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasBurstReadsIops() bool {
	if o != nil && !IsNil(o.BurstReadsIops) {
		return true
	}

	return false
}

// SetBurstReadsIops gets a reference to the given int32 and assigns it to the BurstReadsIops field.
func (o *RequestQOSStaticLimits) SetBurstReadsIops(v int32) {
	o.BurstReadsIops = &v
}

// GetBurstWritesIops returns the BurstWritesIops field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetBurstWritesIops() int32 {
	if o == nil || IsNil(o.BurstWritesIops) {
		var ret int32
		return ret
	}
	return *o.BurstWritesIops
}

// GetBurstWritesIopsOk returns a tuple with the BurstWritesIops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetBurstWritesIopsOk() (*int32, bool) {
	if o == nil || IsNil(o.BurstWritesIops) {
		return nil, false
	}
	return o.BurstWritesIops, true
}

// HasBurstWritesIops returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasBurstWritesIops() bool {
	if o != nil && !IsNil(o.BurstWritesIops) {
		return true
	}

	return false
}

// SetBurstWritesIops gets a reference to the given int32 and assigns it to the BurstWritesIops field.
func (o *RequestQOSStaticLimits) SetBurstWritesIops(v int32) {
	o.BurstWritesIops = &v
}

// GetBurstReadsLoanIops returns the BurstReadsLoanIops field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetBurstReadsLoanIops() int32 {
	if o == nil || IsNil(o.BurstReadsLoanIops) {
		var ret int32
		return ret
	}
	return *o.BurstReadsLoanIops
}

// GetBurstReadsLoanIopsOk returns a tuple with the BurstReadsLoanIops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetBurstReadsLoanIopsOk() (*int32, bool) {
	if o == nil || IsNil(o.BurstReadsLoanIops) {
		return nil, false
	}
	return o.BurstReadsLoanIops, true
}

// HasBurstReadsLoanIops returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasBurstReadsLoanIops() bool {
	if o != nil && !IsNil(o.BurstReadsLoanIops) {
		return true
	}

	return false
}

// SetBurstReadsLoanIops gets a reference to the given int32 and assigns it to the BurstReadsLoanIops field.
func (o *RequestQOSStaticLimits) SetBurstReadsLoanIops(v int32) {
	o.BurstReadsLoanIops = &v
}

// GetBurstWritesLoanIops returns the BurstWritesLoanIops field value if set, zero value otherwise.
func (o *RequestQOSStaticLimits) GetBurstWritesLoanIops() int32 {
	if o == nil || IsNil(o.BurstWritesLoanIops) {
		var ret int32
		return ret
	}
	return *o.BurstWritesLoanIops
}

// GetBurstWritesLoanIopsOk returns a tuple with the BurstWritesLoanIops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestQOSStaticLimits) GetBurstWritesLoanIopsOk() (*int32, bool) {
	if o == nil || IsNil(o.BurstWritesLoanIops) {
		return nil, false
	}
	return o.BurstWritesLoanIops, true
}

// HasBurstWritesLoanIops returns a boolean if a field has been set.
func (o *RequestQOSStaticLimits) HasBurstWritesLoanIops() bool {
	if o != nil && !IsNil(o.BurstWritesLoanIops) {
		return true
	}

	return false
}

// SetBurstWritesLoanIops gets a reference to the given int32 and assigns it to the BurstWritesLoanIops field.
func (o *RequestQOSStaticLimits) SetBurstWritesLoanIops(v int32) {
	o.BurstWritesLoanIops = &v
}

func (o RequestQOSStaticLimits) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestQOSStaticLimits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MinReadsBwMbps) {
		toSerialize["min_reads_bw_mbps"] = o.MinReadsBwMbps
	}
	if !IsNil(o.MaxReadsBwMbps) {
		toSerialize["max_reads_bw_mbps"] = o.MaxReadsBwMbps
	}
	if !IsNil(o.MinWritesBwMbps) {
		toSerialize["min_writes_bw_mbps"] = o.MinWritesBwMbps
	}
	if !IsNil(o.MaxWritesBwMbps) {
		toSerialize["max_writes_bw_mbps"] = o.MaxWritesBwMbps
	}
	if !IsNil(o.MinReadsIops) {
		toSerialize["min_reads_iops"] = o.MinReadsIops
	}
	if !IsNil(o.MaxReadsIops) {
		toSerialize["max_reads_iops"] = o.MaxReadsIops
	}
	if !IsNil(o.MinWritesIops) {
		toSerialize["min_writes_iops"] = o.MinWritesIops
	}
	if !IsNil(o.MaxWritesIops) {
		toSerialize["max_writes_iops"] = o.MaxWritesIops
	}
	if !IsNil(o.BurstReadsBwMb) {
		toSerialize["burst_reads_bw_mb"] = o.BurstReadsBwMb
	}
	if !IsNil(o.BurstWritesBwMb) {
		toSerialize["burst_writes_bw_mb"] = o.BurstWritesBwMb
	}
	if !IsNil(o.BurstReadsLoanMb) {
		toSerialize["burst_reads_loan_mb"] = o.BurstReadsLoanMb
	}
	if !IsNil(o.BurstWritesLoanMb) {
		toSerialize["burst_writes_loan_mb"] = o.BurstWritesLoanMb
	}
	if !IsNil(o.BurstReadsIops) {
		toSerialize["burst_reads_iops"] = o.BurstReadsIops
	}
	if !IsNil(o.BurstWritesIops) {
		toSerialize["burst_writes_iops"] = o.BurstWritesIops
	}
	if !IsNil(o.BurstReadsLoanIops) {
		toSerialize["burst_reads_loan_iops"] = o.BurstReadsLoanIops
	}
	if !IsNil(o.BurstWritesLoanIops) {
		toSerialize["burst_writes_loan_iops"] = o.BurstWritesLoanIops
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RequestQOSStaticLimits) UnmarshalJSON(data []byte) (err error) {
	varRequestQOSStaticLimits := _RequestQOSStaticLimits{}

	err = json.Unmarshal(data, &varRequestQOSStaticLimits)

	if err != nil {
		return err
	}

	*o = RequestQOSStaticLimits(varRequestQOSStaticLimits)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "min_reads_bw_mbps")
		delete(additionalProperties, "max_reads_bw_mbps")
		delete(additionalProperties, "min_writes_bw_mbps")
		delete(additionalProperties, "max_writes_bw_mbps")
		delete(additionalProperties, "min_reads_iops")
		delete(additionalProperties, "max_reads_iops")
		delete(additionalProperties, "min_writes_iops")
		delete(additionalProperties, "max_writes_iops")
		delete(additionalProperties, "burst_reads_bw_mb")
		delete(additionalProperties, "burst_writes_bw_mb")
		delete(additionalProperties, "burst_reads_loan_mb")
		delete(additionalProperties, "burst_writes_loan_mb")
		delete(additionalProperties, "burst_reads_iops")
		delete(additionalProperties, "burst_writes_iops")
		delete(additionalProperties, "burst_reads_loan_iops")
		delete(additionalProperties, "burst_writes_loan_iops")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRequestQOSStaticLimits struct {
	value *RequestQOSStaticLimits
	isSet bool
}

func (v NullableRequestQOSStaticLimits) Get() *RequestQOSStaticLimits {
	return v.value
}

func (v *NullableRequestQOSStaticLimits) Set(val *RequestQOSStaticLimits) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestQOSStaticLimits) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestQOSStaticLimits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestQOSStaticLimits(val *RequestQOSStaticLimits) *NullableRequestQOSStaticLimits {
	return &NullableRequestQOSStaticLimits{value: val, isSet: true}
}

func (v NullableRequestQOSStaticLimits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestQOSStaticLimits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


