/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VIPPoolIPRanges type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VIPPoolIPRanges{}

// VIPPoolIPRanges Array of IP ranges of VIP Pools that can be used with the tenant.
type VIPPoolIPRanges struct {
	VippoolIpRanges []string `json:"vippool_ip_ranges,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VIPPoolIPRanges VIPPoolIPRanges

// NewVIPPoolIPRanges instantiates a new VIPPoolIPRanges object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVIPPoolIPRanges() *VIPPoolIPRanges {
	this := VIPPoolIPRanges{}
	return &this
}

// NewVIPPoolIPRangesWithDefaults instantiates a new VIPPoolIPRanges object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVIPPoolIPRangesWithDefaults() *VIPPoolIPRanges {
	this := VIPPoolIPRanges{}
	return &this
}

// GetVippoolIpRanges returns the VippoolIpRanges field value if set, zero value otherwise.
func (o *VIPPoolIPRanges) GetVippoolIpRanges() []string {
	if o == nil || IsNil(o.VippoolIpRanges) {
		var ret []string
		return ret
	}
	return o.VippoolIpRanges
}

// GetVippoolIpRangesOk returns a tuple with the VippoolIpRanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VIPPoolIPRanges) GetVippoolIpRangesOk() ([]string, bool) {
	if o == nil || IsNil(o.VippoolIpRanges) {
		return nil, false
	}
	return o.VippoolIpRanges, true
}

// HasVippoolIpRanges returns a boolean if a field has been set.
func (o *VIPPoolIPRanges) HasVippoolIpRanges() bool {
	if o != nil && !IsNil(o.VippoolIpRanges) {
		return true
	}

	return false
}

// SetVippoolIpRanges gets a reference to the given []string and assigns it to the VippoolIpRanges field.
func (o *VIPPoolIPRanges) SetVippoolIpRanges(v []string) {
	o.VippoolIpRanges = v
}

func (o VIPPoolIPRanges) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VIPPoolIPRanges) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VippoolIpRanges) {
		toSerialize["vippool_ip_ranges"] = o.VippoolIpRanges
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VIPPoolIPRanges) UnmarshalJSON(data []byte) (err error) {
	varVIPPoolIPRanges := _VIPPoolIPRanges{}

	err = json.Unmarshal(data, &varVIPPoolIPRanges)

	if err != nil {
		return err
	}

	*o = VIPPoolIPRanges(varVIPPoolIPRanges)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "vippool_ip_ranges")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVIPPoolIPRanges struct {
	value *VIPPoolIPRanges
	isSet bool
}

func (v NullableVIPPoolIPRanges) Get() *VIPPoolIPRanges {
	return v.value
}

func (v *NullableVIPPoolIPRanges) Set(val *VIPPoolIPRanges) {
	v.value = val
	v.isSet = true
}

func (v NullableVIPPoolIPRanges) IsSet() bool {
	return v.isSet
}

func (v *NullableVIPPoolIPRanges) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVIPPoolIPRanges(val *VIPPoolIPRanges) *NullableVIPPoolIPRanges {
	return &NullableVIPPoolIPRanges{value: val, isSet: true}
}

func (v NullableVIPPoolIPRanges) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVIPPoolIPRanges) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


