/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProtectedpathsRestoreRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProtectedpathsRestoreRequest{}

// ProtectedpathsRestoreRequest struct for ProtectedpathsRestoreRequest
type ProtectedpathsRestoreRequest struct {
	// 
	Name *string `json:"name,omitempty"`
	// Id of Snapshot to restore
	LoaneeSnapshotId *int32 `json:"loanee_snapshot_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProtectedpathsRestoreRequest ProtectedpathsRestoreRequest

// NewProtectedpathsRestoreRequest instantiates a new ProtectedpathsRestoreRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtectedpathsRestoreRequest() *ProtectedpathsRestoreRequest {
	this := ProtectedpathsRestoreRequest{}
	return &this
}

// NewProtectedpathsRestoreRequestWithDefaults instantiates a new ProtectedpathsRestoreRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtectedpathsRestoreRequestWithDefaults() *ProtectedpathsRestoreRequest {
	this := ProtectedpathsRestoreRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProtectedpathsRestoreRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectedpathsRestoreRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProtectedpathsRestoreRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProtectedpathsRestoreRequest) SetName(v string) {
	o.Name = &v
}

// GetLoaneeSnapshotId returns the LoaneeSnapshotId field value if set, zero value otherwise.
func (o *ProtectedpathsRestoreRequest) GetLoaneeSnapshotId() int32 {
	if o == nil || IsNil(o.LoaneeSnapshotId) {
		var ret int32
		return ret
	}
	return *o.LoaneeSnapshotId
}

// GetLoaneeSnapshotIdOk returns a tuple with the LoaneeSnapshotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectedpathsRestoreRequest) GetLoaneeSnapshotIdOk() (*int32, bool) {
	if o == nil || IsNil(o.LoaneeSnapshotId) {
		return nil, false
	}
	return o.LoaneeSnapshotId, true
}

// HasLoaneeSnapshotId returns a boolean if a field has been set.
func (o *ProtectedpathsRestoreRequest) HasLoaneeSnapshotId() bool {
	if o != nil && !IsNil(o.LoaneeSnapshotId) {
		return true
	}

	return false
}

// SetLoaneeSnapshotId gets a reference to the given int32 and assigns it to the LoaneeSnapshotId field.
func (o *ProtectedpathsRestoreRequest) SetLoaneeSnapshotId(v int32) {
	o.LoaneeSnapshotId = &v
}

func (o ProtectedpathsRestoreRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProtectedpathsRestoreRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.LoaneeSnapshotId) {
		toSerialize["loanee_snapshot_id"] = o.LoaneeSnapshotId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProtectedpathsRestoreRequest) UnmarshalJSON(data []byte) (err error) {
	varProtectedpathsRestoreRequest := _ProtectedpathsRestoreRequest{}

	err = json.Unmarshal(data, &varProtectedpathsRestoreRequest)

	if err != nil {
		return err
	}

	*o = ProtectedpathsRestoreRequest(varProtectedpathsRestoreRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "loanee_snapshot_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProtectedpathsRestoreRequest struct {
	value *ProtectedpathsRestoreRequest
	isSet bool
}

func (v NullableProtectedpathsRestoreRequest) Get() *ProtectedpathsRestoreRequest {
	return v.value
}

func (v *NullableProtectedpathsRestoreRequest) Set(val *ProtectedpathsRestoreRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProtectedpathsRestoreRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProtectedpathsRestoreRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtectedpathsRestoreRequest(val *ProtectedpathsRestoreRequest) *NullableProtectedpathsRestoreRequest {
	return &NullableProtectedpathsRestoreRequest{value: val, isSet: true}
}

func (v NullableProtectedpathsRestoreRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtectedpathsRestoreRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


