/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the TokenRefreshRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenRefreshRequest{}

// TokenRefreshRequest struct for TokenRefreshRequest
type TokenRefreshRequest struct {
	// Long lived access token
	Refresh string `json:"refresh"`
	AdditionalProperties map[string]interface{}
}

type _TokenRefreshRequest TokenRefreshRequest

// NewTokenRefreshRequest instantiates a new TokenRefreshRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenRefreshRequest(refresh string) *TokenRefreshRequest {
	this := TokenRefreshRequest{}
	this.Refresh = refresh
	return &this
}

// NewTokenRefreshRequestWithDefaults instantiates a new TokenRefreshRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenRefreshRequestWithDefaults() *TokenRefreshRequest {
	this := TokenRefreshRequest{}
	return &this
}

// GetRefresh returns the Refresh field value
func (o *TokenRefreshRequest) GetRefresh() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Refresh
}

// GetRefreshOk returns a tuple with the Refresh field value
// and a boolean to check if the value has been set.
func (o *TokenRefreshRequest) GetRefreshOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Refresh, true
}

// SetRefresh sets field value
func (o *TokenRefreshRequest) SetRefresh(v string) {
	o.Refresh = v
}

func (o TokenRefreshRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenRefreshRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["refresh"] = o.Refresh

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TokenRefreshRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"refresh",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenRefreshRequest := _TokenRefreshRequest{}

	err = json.Unmarshal(data, &varTokenRefreshRequest)

	if err != nil {
		return err
	}

	*o = TokenRefreshRequest(varTokenRefreshRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "refresh")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTokenRefreshRequest struct {
	value *TokenRefreshRequest
	isSet bool
}

func (v NullableTokenRefreshRequest) Get() *TokenRefreshRequest {
	return v.value
}

func (v *NullableTokenRefreshRequest) Set(val *TokenRefreshRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenRefreshRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenRefreshRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenRefreshRequest(val *TokenRefreshRequest) *NullableTokenRefreshRequest {
	return &NullableTokenRefreshRequest{value: val, isSet: true}
}

func (v NullableTokenRefreshRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenRefreshRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


