/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ActiveDirectory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActiveDirectory{}

// ActiveDirectory struct for ActiveDirectory
type ActiveDirectory struct {
	Id *int32 `json:"id,omitempty"`
	// GUID
	Guid *string `json:"guid,omitempty"`
	Name *string `json:"name,omitempty"`
	Url *string `json:"url,omitempty"`
	Title *string `json:"title,omitempty"`
	// Name of the computer object/machine account to add. Recommended to be the name of the cluster.
	MachineAccountName *string `json:"machine_account_name,omitempty"`
	// Organizational Unit within AD where the Cluster Machine account will be created. If left empty, it will go into default Computers OU 
	OrganizationalUnit *string `json:"organizational_unit,omitempty"`
	// List of Domain Controllers to prefer for authentication. DCs listed here will be queried exclusively unless they fail or do not respond. In such a case, other DCs will be consulted. Specify as a comma-separated list. Each entry can be a fully-qualified hostname or an IP address. 
	PreferredDcList map[string]interface{} `json:"preferred_dc_list,omitempty"`
	// FQDN of the domain.
	DomainName *string `json:"domain_name,omitempty"`
	// the id of the attached LDAP object
	LdapId *int32 `json:"ldap_id,omitempty"`
	// enabled/disabled
	Enabled *bool `json:"enabled,omitempty"`
	// Active Directory state
	State *string `json:"state,omitempty"`
	// Indicates if AD is allowed for SMB.
	SmbAllowed *bool `json:"smb_allowed,omitempty"`
	// Manages support of NTLM authentication method for SMB protocol.
	NtlmEnabled *bool `json:"ntlm_enabled,omitempty"`
	TenantId *int32 `json:"tenant_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ActiveDirectory ActiveDirectory

// NewActiveDirectory instantiates a new ActiveDirectory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActiveDirectory() *ActiveDirectory {
	this := ActiveDirectory{}
	var smbAllowed bool = false
	this.SmbAllowed = &smbAllowed
	var ntlmEnabled bool = true
	this.NtlmEnabled = &ntlmEnabled
	return &this
}

// NewActiveDirectoryWithDefaults instantiates a new ActiveDirectory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActiveDirectoryWithDefaults() *ActiveDirectory {
	this := ActiveDirectory{}
	var smbAllowed bool = false
	this.SmbAllowed = &smbAllowed
	var ntlmEnabled bool = true
	this.NtlmEnabled = &ntlmEnabled
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ActiveDirectory) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveDirectory) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ActiveDirectory) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ActiveDirectory) SetId(v int32) {
	o.Id = &v
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *ActiveDirectory) GetGuid() string {
	if o == nil || IsNil(o.Guid) {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveDirectory) GetGuidOk() (*string, bool) {
	if o == nil || IsNil(o.Guid) {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *ActiveDirectory) HasGuid() bool {
	if o != nil && !IsNil(o.Guid) {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *ActiveDirectory) SetGuid(v string) {
	o.Guid = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ActiveDirectory) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveDirectory) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ActiveDirectory) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ActiveDirectory) SetName(v string) {
	o.Name = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ActiveDirectory) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveDirectory) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ActiveDirectory) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ActiveDirectory) SetUrl(v string) {
	o.Url = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ActiveDirectory) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveDirectory) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ActiveDirectory) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ActiveDirectory) SetTitle(v string) {
	o.Title = &v
}

// GetMachineAccountName returns the MachineAccountName field value if set, zero value otherwise.
func (o *ActiveDirectory) GetMachineAccountName() string {
	if o == nil || IsNil(o.MachineAccountName) {
		var ret string
		return ret
	}
	return *o.MachineAccountName
}

// GetMachineAccountNameOk returns a tuple with the MachineAccountName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveDirectory) GetMachineAccountNameOk() (*string, bool) {
	if o == nil || IsNil(o.MachineAccountName) {
		return nil, false
	}
	return o.MachineAccountName, true
}

// HasMachineAccountName returns a boolean if a field has been set.
func (o *ActiveDirectory) HasMachineAccountName() bool {
	if o != nil && !IsNil(o.MachineAccountName) {
		return true
	}

	return false
}

// SetMachineAccountName gets a reference to the given string and assigns it to the MachineAccountName field.
func (o *ActiveDirectory) SetMachineAccountName(v string) {
	o.MachineAccountName = &v
}

// GetOrganizationalUnit returns the OrganizationalUnit field value if set, zero value otherwise.
func (o *ActiveDirectory) GetOrganizationalUnit() string {
	if o == nil || IsNil(o.OrganizationalUnit) {
		var ret string
		return ret
	}
	return *o.OrganizationalUnit
}

// GetOrganizationalUnitOk returns a tuple with the OrganizationalUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveDirectory) GetOrganizationalUnitOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationalUnit) {
		return nil, false
	}
	return o.OrganizationalUnit, true
}

// HasOrganizationalUnit returns a boolean if a field has been set.
func (o *ActiveDirectory) HasOrganizationalUnit() bool {
	if o != nil && !IsNil(o.OrganizationalUnit) {
		return true
	}

	return false
}

// SetOrganizationalUnit gets a reference to the given string and assigns it to the OrganizationalUnit field.
func (o *ActiveDirectory) SetOrganizationalUnit(v string) {
	o.OrganizationalUnit = &v
}

// GetPreferredDcList returns the PreferredDcList field value if set, zero value otherwise.
func (o *ActiveDirectory) GetPreferredDcList() map[string]interface{} {
	if o == nil || IsNil(o.PreferredDcList) {
		var ret map[string]interface{}
		return ret
	}
	return o.PreferredDcList
}

// GetPreferredDcListOk returns a tuple with the PreferredDcList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveDirectory) GetPreferredDcListOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.PreferredDcList) {
		return map[string]interface{}{}, false
	}
	return o.PreferredDcList, true
}

// HasPreferredDcList returns a boolean if a field has been set.
func (o *ActiveDirectory) HasPreferredDcList() bool {
	if o != nil && !IsNil(o.PreferredDcList) {
		return true
	}

	return false
}

// SetPreferredDcList gets a reference to the given map[string]interface{} and assigns it to the PreferredDcList field.
func (o *ActiveDirectory) SetPreferredDcList(v map[string]interface{}) {
	o.PreferredDcList = v
}

// GetDomainName returns the DomainName field value if set, zero value otherwise.
func (o *ActiveDirectory) GetDomainName() string {
	if o == nil || IsNil(o.DomainName) {
		var ret string
		return ret
	}
	return *o.DomainName
}

// GetDomainNameOk returns a tuple with the DomainName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveDirectory) GetDomainNameOk() (*string, bool) {
	if o == nil || IsNil(o.DomainName) {
		return nil, false
	}
	return o.DomainName, true
}

// HasDomainName returns a boolean if a field has been set.
func (o *ActiveDirectory) HasDomainName() bool {
	if o != nil && !IsNil(o.DomainName) {
		return true
	}

	return false
}

// SetDomainName gets a reference to the given string and assigns it to the DomainName field.
func (o *ActiveDirectory) SetDomainName(v string) {
	o.DomainName = &v
}

// GetLdapId returns the LdapId field value if set, zero value otherwise.
func (o *ActiveDirectory) GetLdapId() int32 {
	if o == nil || IsNil(o.LdapId) {
		var ret int32
		return ret
	}
	return *o.LdapId
}

// GetLdapIdOk returns a tuple with the LdapId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveDirectory) GetLdapIdOk() (*int32, bool) {
	if o == nil || IsNil(o.LdapId) {
		return nil, false
	}
	return o.LdapId, true
}

// HasLdapId returns a boolean if a field has been set.
func (o *ActiveDirectory) HasLdapId() bool {
	if o != nil && !IsNil(o.LdapId) {
		return true
	}

	return false
}

// SetLdapId gets a reference to the given int32 and assigns it to the LdapId field.
func (o *ActiveDirectory) SetLdapId(v int32) {
	o.LdapId = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *ActiveDirectory) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveDirectory) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *ActiveDirectory) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *ActiveDirectory) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ActiveDirectory) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveDirectory) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ActiveDirectory) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *ActiveDirectory) SetState(v string) {
	o.State = &v
}

// GetSmbAllowed returns the SmbAllowed field value if set, zero value otherwise.
func (o *ActiveDirectory) GetSmbAllowed() bool {
	if o == nil || IsNil(o.SmbAllowed) {
		var ret bool
		return ret
	}
	return *o.SmbAllowed
}

// GetSmbAllowedOk returns a tuple with the SmbAllowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveDirectory) GetSmbAllowedOk() (*bool, bool) {
	if o == nil || IsNil(o.SmbAllowed) {
		return nil, false
	}
	return o.SmbAllowed, true
}

// HasSmbAllowed returns a boolean if a field has been set.
func (o *ActiveDirectory) HasSmbAllowed() bool {
	if o != nil && !IsNil(o.SmbAllowed) {
		return true
	}

	return false
}

// SetSmbAllowed gets a reference to the given bool and assigns it to the SmbAllowed field.
func (o *ActiveDirectory) SetSmbAllowed(v bool) {
	o.SmbAllowed = &v
}

// GetNtlmEnabled returns the NtlmEnabled field value if set, zero value otherwise.
func (o *ActiveDirectory) GetNtlmEnabled() bool {
	if o == nil || IsNil(o.NtlmEnabled) {
		var ret bool
		return ret
	}
	return *o.NtlmEnabled
}

// GetNtlmEnabledOk returns a tuple with the NtlmEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveDirectory) GetNtlmEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.NtlmEnabled) {
		return nil, false
	}
	return o.NtlmEnabled, true
}

// HasNtlmEnabled returns a boolean if a field has been set.
func (o *ActiveDirectory) HasNtlmEnabled() bool {
	if o != nil && !IsNil(o.NtlmEnabled) {
		return true
	}

	return false
}

// SetNtlmEnabled gets a reference to the given bool and assigns it to the NtlmEnabled field.
func (o *ActiveDirectory) SetNtlmEnabled(v bool) {
	o.NtlmEnabled = &v
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *ActiveDirectory) GetTenantId() int32 {
	if o == nil || IsNil(o.TenantId) {
		var ret int32
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ActiveDirectory) GetTenantIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *ActiveDirectory) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given int32 and assigns it to the TenantId field.
func (o *ActiveDirectory) SetTenantId(v int32) {
	o.TenantId = &v
}

func (o ActiveDirectory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActiveDirectory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Guid) {
		toSerialize["guid"] = o.Guid
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.MachineAccountName) {
		toSerialize["machine_account_name"] = o.MachineAccountName
	}
	if !IsNil(o.OrganizationalUnit) {
		toSerialize["organizational_unit"] = o.OrganizationalUnit
	}
	if !IsNil(o.PreferredDcList) {
		toSerialize["preferred_dc_list"] = o.PreferredDcList
	}
	if !IsNil(o.DomainName) {
		toSerialize["domain_name"] = o.DomainName
	}
	if !IsNil(o.LdapId) {
		toSerialize["ldap_id"] = o.LdapId
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.SmbAllowed) {
		toSerialize["smb_allowed"] = o.SmbAllowed
	}
	if !IsNil(o.NtlmEnabled) {
		toSerialize["ntlm_enabled"] = o.NtlmEnabled
	}
	if !IsNil(o.TenantId) {
		toSerialize["tenant_id"] = o.TenantId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ActiveDirectory) UnmarshalJSON(data []byte) (err error) {
	varActiveDirectory := _ActiveDirectory{}

	err = json.Unmarshal(data, &varActiveDirectory)

	if err != nil {
		return err
	}

	*o = ActiveDirectory(varActiveDirectory)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "guid")
		delete(additionalProperties, "name")
		delete(additionalProperties, "url")
		delete(additionalProperties, "title")
		delete(additionalProperties, "machine_account_name")
		delete(additionalProperties, "organizational_unit")
		delete(additionalProperties, "preferred_dc_list")
		delete(additionalProperties, "domain_name")
		delete(additionalProperties, "ldap_id")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "state")
		delete(additionalProperties, "smb_allowed")
		delete(additionalProperties, "ntlm_enabled")
		delete(additionalProperties, "tenant_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableActiveDirectory struct {
	value *ActiveDirectory
	isSet bool
}

func (v NullableActiveDirectory) Get() *ActiveDirectory {
	return v.value
}

func (v *NullableActiveDirectory) Set(val *ActiveDirectory) {
	v.value = val
	v.isSet = true
}

func (v NullableActiveDirectory) IsSet() bool {
	return v.isSet
}

func (v *NullableActiveDirectory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActiveDirectory(val *ActiveDirectory) *NullableActiveDirectory {
	return &NullableActiveDirectory{value: val, isSet: true}
}

func (v NullableActiveDirectory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActiveDirectory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


