/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RotateMasterEncryptionGroupKey503Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RotateMasterEncryptionGroupKey503Response{}

// RotateMasterEncryptionGroupKey503Response struct for RotateMasterEncryptionGroupKey503Response
type RotateMasterEncryptionGroupKey503Response struct {
	Detail *string `json:"detail,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RotateMasterEncryptionGroupKey503Response RotateMasterEncryptionGroupKey503Response

// NewRotateMasterEncryptionGroupKey503Response instantiates a new RotateMasterEncryptionGroupKey503Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotateMasterEncryptionGroupKey503Response() *RotateMasterEncryptionGroupKey503Response {
	this := RotateMasterEncryptionGroupKey503Response{}
	return &this
}

// NewRotateMasterEncryptionGroupKey503ResponseWithDefaults instantiates a new RotateMasterEncryptionGroupKey503Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotateMasterEncryptionGroupKey503ResponseWithDefaults() *RotateMasterEncryptionGroupKey503Response {
	this := RotateMasterEncryptionGroupKey503Response{}
	return &this
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *RotateMasterEncryptionGroupKey503Response) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotateMasterEncryptionGroupKey503Response) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *RotateMasterEncryptionGroupKey503Response) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *RotateMasterEncryptionGroupKey503Response) SetDetail(v string) {
	o.Detail = &v
}

func (o RotateMasterEncryptionGroupKey503Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RotateMasterEncryptionGroupKey503Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RotateMasterEncryptionGroupKey503Response) UnmarshalJSON(data []byte) (err error) {
	varRotateMasterEncryptionGroupKey503Response := _RotateMasterEncryptionGroupKey503Response{}

	err = json.Unmarshal(data, &varRotateMasterEncryptionGroupKey503Response)

	if err != nil {
		return err
	}

	*o = RotateMasterEncryptionGroupKey503Response(varRotateMasterEncryptionGroupKey503Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "detail")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRotateMasterEncryptionGroupKey503Response struct {
	value *RotateMasterEncryptionGroupKey503Response
	isSet bool
}

func (v NullableRotateMasterEncryptionGroupKey503Response) Get() *RotateMasterEncryptionGroupKey503Response {
	return v.value
}

func (v *NullableRotateMasterEncryptionGroupKey503Response) Set(val *RotateMasterEncryptionGroupKey503Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRotateMasterEncryptionGroupKey503Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRotateMasterEncryptionGroupKey503Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotateMasterEncryptionGroupKey503Response(val *RotateMasterEncryptionGroupKey503Response) *NullableRotateMasterEncryptionGroupKey503Response {
	return &NullableRotateMasterEncryptionGroupKey503Response{value: val, isSet: true}
}

func (v NullableRotateMasterEncryptionGroupKey503Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotateMasterEncryptionGroupKey503Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


