/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the ClustersUpgradeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClustersUpgradeRequest{}

// ClustersUpgradeRequest struct for ClustersUpgradeRequest
type ClustersUpgradeRequest struct {
	// Specifies the build for upgrade
	Build string `json:"build"`
	// OS upgrade
	OsUpgrade *bool `json:"os_upgrade,omitempty"`
	// BMC upgrade
	BmcUpgrade *bool `json:"bmc_upgrade,omitempty"`
	// Enables data reduction (DR) for a cluster without DR enabled prior to upgrade
	EnableDr *bool `json:"enable_dr,omitempty"`
	// Forces upgrade regardless of version or upgrade state
	Force *bool `json:"force,omitempty"`
	// Skips validation of hardware component health. Use with caution since component redundancy is important in NDU. Do not use with OS upgrade.
	SkipHwCheck *bool `json:"skip_hw_check,omitempty"`
	// Skips SW validations (e.g. deny list)
	SkipSwValidations *bool `json:"skip_sw_validations,omitempty"`
	// Pull docker images only
	Prepare *bool `json:"prepare,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ClustersUpgradeRequest ClustersUpgradeRequest

// NewClustersUpgradeRequest instantiates a new ClustersUpgradeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClustersUpgradeRequest(build string) *ClustersUpgradeRequest {
	this := ClustersUpgradeRequest{}
	this.Build = build
	return &this
}

// NewClustersUpgradeRequestWithDefaults instantiates a new ClustersUpgradeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClustersUpgradeRequestWithDefaults() *ClustersUpgradeRequest {
	this := ClustersUpgradeRequest{}
	return &this
}

// GetBuild returns the Build field value
func (o *ClustersUpgradeRequest) GetBuild() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Build
}

// GetBuildOk returns a tuple with the Build field value
// and a boolean to check if the value has been set.
func (o *ClustersUpgradeRequest) GetBuildOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Build, true
}

// SetBuild sets field value
func (o *ClustersUpgradeRequest) SetBuild(v string) {
	o.Build = v
}

// GetOsUpgrade returns the OsUpgrade field value if set, zero value otherwise.
func (o *ClustersUpgradeRequest) GetOsUpgrade() bool {
	if o == nil || IsNil(o.OsUpgrade) {
		var ret bool
		return ret
	}
	return *o.OsUpgrade
}

// GetOsUpgradeOk returns a tuple with the OsUpgrade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersUpgradeRequest) GetOsUpgradeOk() (*bool, bool) {
	if o == nil || IsNil(o.OsUpgrade) {
		return nil, false
	}
	return o.OsUpgrade, true
}

// HasOsUpgrade returns a boolean if a field has been set.
func (o *ClustersUpgradeRequest) HasOsUpgrade() bool {
	if o != nil && !IsNil(o.OsUpgrade) {
		return true
	}

	return false
}

// SetOsUpgrade gets a reference to the given bool and assigns it to the OsUpgrade field.
func (o *ClustersUpgradeRequest) SetOsUpgrade(v bool) {
	o.OsUpgrade = &v
}

// GetBmcUpgrade returns the BmcUpgrade field value if set, zero value otherwise.
func (o *ClustersUpgradeRequest) GetBmcUpgrade() bool {
	if o == nil || IsNil(o.BmcUpgrade) {
		var ret bool
		return ret
	}
	return *o.BmcUpgrade
}

// GetBmcUpgradeOk returns a tuple with the BmcUpgrade field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersUpgradeRequest) GetBmcUpgradeOk() (*bool, bool) {
	if o == nil || IsNil(o.BmcUpgrade) {
		return nil, false
	}
	return o.BmcUpgrade, true
}

// HasBmcUpgrade returns a boolean if a field has been set.
func (o *ClustersUpgradeRequest) HasBmcUpgrade() bool {
	if o != nil && !IsNil(o.BmcUpgrade) {
		return true
	}

	return false
}

// SetBmcUpgrade gets a reference to the given bool and assigns it to the BmcUpgrade field.
func (o *ClustersUpgradeRequest) SetBmcUpgrade(v bool) {
	o.BmcUpgrade = &v
}

// GetEnableDr returns the EnableDr field value if set, zero value otherwise.
func (o *ClustersUpgradeRequest) GetEnableDr() bool {
	if o == nil || IsNil(o.EnableDr) {
		var ret bool
		return ret
	}
	return *o.EnableDr
}

// GetEnableDrOk returns a tuple with the EnableDr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersUpgradeRequest) GetEnableDrOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableDr) {
		return nil, false
	}
	return o.EnableDr, true
}

// HasEnableDr returns a boolean if a field has been set.
func (o *ClustersUpgradeRequest) HasEnableDr() bool {
	if o != nil && !IsNil(o.EnableDr) {
		return true
	}

	return false
}

// SetEnableDr gets a reference to the given bool and assigns it to the EnableDr field.
func (o *ClustersUpgradeRequest) SetEnableDr(v bool) {
	o.EnableDr = &v
}

// GetForce returns the Force field value if set, zero value otherwise.
func (o *ClustersUpgradeRequest) GetForce() bool {
	if o == nil || IsNil(o.Force) {
		var ret bool
		return ret
	}
	return *o.Force
}

// GetForceOk returns a tuple with the Force field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersUpgradeRequest) GetForceOk() (*bool, bool) {
	if o == nil || IsNil(o.Force) {
		return nil, false
	}
	return o.Force, true
}

// HasForce returns a boolean if a field has been set.
func (o *ClustersUpgradeRequest) HasForce() bool {
	if o != nil && !IsNil(o.Force) {
		return true
	}

	return false
}

// SetForce gets a reference to the given bool and assigns it to the Force field.
func (o *ClustersUpgradeRequest) SetForce(v bool) {
	o.Force = &v
}

// GetSkipHwCheck returns the SkipHwCheck field value if set, zero value otherwise.
func (o *ClustersUpgradeRequest) GetSkipHwCheck() bool {
	if o == nil || IsNil(o.SkipHwCheck) {
		var ret bool
		return ret
	}
	return *o.SkipHwCheck
}

// GetSkipHwCheckOk returns a tuple with the SkipHwCheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersUpgradeRequest) GetSkipHwCheckOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipHwCheck) {
		return nil, false
	}
	return o.SkipHwCheck, true
}

// HasSkipHwCheck returns a boolean if a field has been set.
func (o *ClustersUpgradeRequest) HasSkipHwCheck() bool {
	if o != nil && !IsNil(o.SkipHwCheck) {
		return true
	}

	return false
}

// SetSkipHwCheck gets a reference to the given bool and assigns it to the SkipHwCheck field.
func (o *ClustersUpgradeRequest) SetSkipHwCheck(v bool) {
	o.SkipHwCheck = &v
}

// GetSkipSwValidations returns the SkipSwValidations field value if set, zero value otherwise.
func (o *ClustersUpgradeRequest) GetSkipSwValidations() bool {
	if o == nil || IsNil(o.SkipSwValidations) {
		var ret bool
		return ret
	}
	return *o.SkipSwValidations
}

// GetSkipSwValidationsOk returns a tuple with the SkipSwValidations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersUpgradeRequest) GetSkipSwValidationsOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipSwValidations) {
		return nil, false
	}
	return o.SkipSwValidations, true
}

// HasSkipSwValidations returns a boolean if a field has been set.
func (o *ClustersUpgradeRequest) HasSkipSwValidations() bool {
	if o != nil && !IsNil(o.SkipSwValidations) {
		return true
	}

	return false
}

// SetSkipSwValidations gets a reference to the given bool and assigns it to the SkipSwValidations field.
func (o *ClustersUpgradeRequest) SetSkipSwValidations(v bool) {
	o.SkipSwValidations = &v
}

// GetPrepare returns the Prepare field value if set, zero value otherwise.
func (o *ClustersUpgradeRequest) GetPrepare() bool {
	if o == nil || IsNil(o.Prepare) {
		var ret bool
		return ret
	}
	return *o.Prepare
}

// GetPrepareOk returns a tuple with the Prepare field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClustersUpgradeRequest) GetPrepareOk() (*bool, bool) {
	if o == nil || IsNil(o.Prepare) {
		return nil, false
	}
	return o.Prepare, true
}

// HasPrepare returns a boolean if a field has been set.
func (o *ClustersUpgradeRequest) HasPrepare() bool {
	if o != nil && !IsNil(o.Prepare) {
		return true
	}

	return false
}

// SetPrepare gets a reference to the given bool and assigns it to the Prepare field.
func (o *ClustersUpgradeRequest) SetPrepare(v bool) {
	o.Prepare = &v
}

func (o ClustersUpgradeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClustersUpgradeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["build"] = o.Build
	if !IsNil(o.OsUpgrade) {
		toSerialize["os_upgrade"] = o.OsUpgrade
	}
	if !IsNil(o.BmcUpgrade) {
		toSerialize["bmc_upgrade"] = o.BmcUpgrade
	}
	if !IsNil(o.EnableDr) {
		toSerialize["enable_dr"] = o.EnableDr
	}
	if !IsNil(o.Force) {
		toSerialize["force"] = o.Force
	}
	if !IsNil(o.SkipHwCheck) {
		toSerialize["skip_hw_check"] = o.SkipHwCheck
	}
	if !IsNil(o.SkipSwValidations) {
		toSerialize["skip_sw_validations"] = o.SkipSwValidations
	}
	if !IsNil(o.Prepare) {
		toSerialize["prepare"] = o.Prepare
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClustersUpgradeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"build",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClustersUpgradeRequest := _ClustersUpgradeRequest{}

	err = json.Unmarshal(data, &varClustersUpgradeRequest)

	if err != nil {
		return err
	}

	*o = ClustersUpgradeRequest(varClustersUpgradeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "build")
		delete(additionalProperties, "os_upgrade")
		delete(additionalProperties, "bmc_upgrade")
		delete(additionalProperties, "enable_dr")
		delete(additionalProperties, "force")
		delete(additionalProperties, "skip_hw_check")
		delete(additionalProperties, "skip_sw_validations")
		delete(additionalProperties, "prepare")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClustersUpgradeRequest struct {
	value *ClustersUpgradeRequest
	isSet bool
}

func (v NullableClustersUpgradeRequest) Get() *ClustersUpgradeRequest {
	return v.value
}

func (v *NullableClustersUpgradeRequest) Set(val *ClustersUpgradeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableClustersUpgradeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableClustersUpgradeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClustersUpgradeRequest(val *ClustersUpgradeRequest) *NullableClustersUpgradeRequest {
	return &NullableClustersUpgradeRequest{value: val, isSet: true}
}

func (v NullableClustersUpgradeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClustersUpgradeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


