/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the UsersAddRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersAddRequest{}

// UsersAddRequest struct for UsersAddRequest
type UsersAddRequest struct {
	// User name
	Name string `json:"name"`
	// NFS UID
	Uid int32 `json:"uid"`
	// Leading GID
	LeadingGid *int32 `json:"leading_gid,omitempty"`
	// list of GIDs
	Gids []int32 `json:"gids,omitempty"`
	// 
	Local *bool `json:"local,omitempty"`
	// Set to true to give the user permission to create S3 buckets
	AllowCreateBucket *bool `json:"allow_create_bucket,omitempty"`
	// Set to true to give the user permission to delete S3 buckets
	AllowDeleteBucket *bool `json:"allow_delete_bucket,omitempty"`
	// Set to true to give the user S3 superuser permission
	S3Superuser *bool `json:"s3_superuser,omitempty"`
	// list of s3 policy ids
	S3PoliciesIds map[string]interface{} `json:"s3_policies_ids,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _UsersAddRequest UsersAddRequest

// NewUsersAddRequest instantiates a new UsersAddRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersAddRequest(name string, uid int32) *UsersAddRequest {
	this := UsersAddRequest{}
	this.Name = name
	this.Uid = uid
	return &this
}

// NewUsersAddRequestWithDefaults instantiates a new UsersAddRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersAddRequestWithDefaults() *UsersAddRequest {
	this := UsersAddRequest{}
	return &this
}

// GetName returns the Name field value
func (o *UsersAddRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UsersAddRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UsersAddRequest) SetName(v string) {
	o.Name = v
}

// GetUid returns the Uid field value
func (o *UsersAddRequest) GetUid() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Uid
}

// GetUidOk returns a tuple with the Uid field value
// and a boolean to check if the value has been set.
func (o *UsersAddRequest) GetUidOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uid, true
}

// SetUid sets field value
func (o *UsersAddRequest) SetUid(v int32) {
	o.Uid = v
}

// GetLeadingGid returns the LeadingGid field value if set, zero value otherwise.
func (o *UsersAddRequest) GetLeadingGid() int32 {
	if o == nil || IsNil(o.LeadingGid) {
		var ret int32
		return ret
	}
	return *o.LeadingGid
}

// GetLeadingGidOk returns a tuple with the LeadingGid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersAddRequest) GetLeadingGidOk() (*int32, bool) {
	if o == nil || IsNil(o.LeadingGid) {
		return nil, false
	}
	return o.LeadingGid, true
}

// HasLeadingGid returns a boolean if a field has been set.
func (o *UsersAddRequest) HasLeadingGid() bool {
	if o != nil && !IsNil(o.LeadingGid) {
		return true
	}

	return false
}

// SetLeadingGid gets a reference to the given int32 and assigns it to the LeadingGid field.
func (o *UsersAddRequest) SetLeadingGid(v int32) {
	o.LeadingGid = &v
}

// GetGids returns the Gids field value if set, zero value otherwise.
func (o *UsersAddRequest) GetGids() []int32 {
	if o == nil || IsNil(o.Gids) {
		var ret []int32
		return ret
	}
	return o.Gids
}

// GetGidsOk returns a tuple with the Gids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersAddRequest) GetGidsOk() ([]int32, bool) {
	if o == nil || IsNil(o.Gids) {
		return nil, false
	}
	return o.Gids, true
}

// HasGids returns a boolean if a field has been set.
func (o *UsersAddRequest) HasGids() bool {
	if o != nil && !IsNil(o.Gids) {
		return true
	}

	return false
}

// SetGids gets a reference to the given []int32 and assigns it to the Gids field.
func (o *UsersAddRequest) SetGids(v []int32) {
	o.Gids = v
}

// GetLocal returns the Local field value if set, zero value otherwise.
func (o *UsersAddRequest) GetLocal() bool {
	if o == nil || IsNil(o.Local) {
		var ret bool
		return ret
	}
	return *o.Local
}

// GetLocalOk returns a tuple with the Local field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersAddRequest) GetLocalOk() (*bool, bool) {
	if o == nil || IsNil(o.Local) {
		return nil, false
	}
	return o.Local, true
}

// HasLocal returns a boolean if a field has been set.
func (o *UsersAddRequest) HasLocal() bool {
	if o != nil && !IsNil(o.Local) {
		return true
	}

	return false
}

// SetLocal gets a reference to the given bool and assigns it to the Local field.
func (o *UsersAddRequest) SetLocal(v bool) {
	o.Local = &v
}

// GetAllowCreateBucket returns the AllowCreateBucket field value if set, zero value otherwise.
func (o *UsersAddRequest) GetAllowCreateBucket() bool {
	if o == nil || IsNil(o.AllowCreateBucket) {
		var ret bool
		return ret
	}
	return *o.AllowCreateBucket
}

// GetAllowCreateBucketOk returns a tuple with the AllowCreateBucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersAddRequest) GetAllowCreateBucketOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowCreateBucket) {
		return nil, false
	}
	return o.AllowCreateBucket, true
}

// HasAllowCreateBucket returns a boolean if a field has been set.
func (o *UsersAddRequest) HasAllowCreateBucket() bool {
	if o != nil && !IsNil(o.AllowCreateBucket) {
		return true
	}

	return false
}

// SetAllowCreateBucket gets a reference to the given bool and assigns it to the AllowCreateBucket field.
func (o *UsersAddRequest) SetAllowCreateBucket(v bool) {
	o.AllowCreateBucket = &v
}

// GetAllowDeleteBucket returns the AllowDeleteBucket field value if set, zero value otherwise.
func (o *UsersAddRequest) GetAllowDeleteBucket() bool {
	if o == nil || IsNil(o.AllowDeleteBucket) {
		var ret bool
		return ret
	}
	return *o.AllowDeleteBucket
}

// GetAllowDeleteBucketOk returns a tuple with the AllowDeleteBucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersAddRequest) GetAllowDeleteBucketOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowDeleteBucket) {
		return nil, false
	}
	return o.AllowDeleteBucket, true
}

// HasAllowDeleteBucket returns a boolean if a field has been set.
func (o *UsersAddRequest) HasAllowDeleteBucket() bool {
	if o != nil && !IsNil(o.AllowDeleteBucket) {
		return true
	}

	return false
}

// SetAllowDeleteBucket gets a reference to the given bool and assigns it to the AllowDeleteBucket field.
func (o *UsersAddRequest) SetAllowDeleteBucket(v bool) {
	o.AllowDeleteBucket = &v
}

// GetS3Superuser returns the S3Superuser field value if set, zero value otherwise.
func (o *UsersAddRequest) GetS3Superuser() bool {
	if o == nil || IsNil(o.S3Superuser) {
		var ret bool
		return ret
	}
	return *o.S3Superuser
}

// GetS3SuperuserOk returns a tuple with the S3Superuser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersAddRequest) GetS3SuperuserOk() (*bool, bool) {
	if o == nil || IsNil(o.S3Superuser) {
		return nil, false
	}
	return o.S3Superuser, true
}

// HasS3Superuser returns a boolean if a field has been set.
func (o *UsersAddRequest) HasS3Superuser() bool {
	if o != nil && !IsNil(o.S3Superuser) {
		return true
	}

	return false
}

// SetS3Superuser gets a reference to the given bool and assigns it to the S3Superuser field.
func (o *UsersAddRequest) SetS3Superuser(v bool) {
	o.S3Superuser = &v
}

// GetS3PoliciesIds returns the S3PoliciesIds field value if set, zero value otherwise.
func (o *UsersAddRequest) GetS3PoliciesIds() map[string]interface{} {
	if o == nil || IsNil(o.S3PoliciesIds) {
		var ret map[string]interface{}
		return ret
	}
	return o.S3PoliciesIds
}

// GetS3PoliciesIdsOk returns a tuple with the S3PoliciesIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UsersAddRequest) GetS3PoliciesIdsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.S3PoliciesIds) {
		return map[string]interface{}{}, false
	}
	return o.S3PoliciesIds, true
}

// HasS3PoliciesIds returns a boolean if a field has been set.
func (o *UsersAddRequest) HasS3PoliciesIds() bool {
	if o != nil && !IsNil(o.S3PoliciesIds) {
		return true
	}

	return false
}

// SetS3PoliciesIds gets a reference to the given map[string]interface{} and assigns it to the S3PoliciesIds field.
func (o *UsersAddRequest) SetS3PoliciesIds(v map[string]interface{}) {
	o.S3PoliciesIds = v
}

func (o UsersAddRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersAddRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["uid"] = o.Uid
	if !IsNil(o.LeadingGid) {
		toSerialize["leading_gid"] = o.LeadingGid
	}
	if !IsNil(o.Gids) {
		toSerialize["gids"] = o.Gids
	}
	if !IsNil(o.Local) {
		toSerialize["local"] = o.Local
	}
	if !IsNil(o.AllowCreateBucket) {
		toSerialize["allow_create_bucket"] = o.AllowCreateBucket
	}
	if !IsNil(o.AllowDeleteBucket) {
		toSerialize["allow_delete_bucket"] = o.AllowDeleteBucket
	}
	if !IsNil(o.S3Superuser) {
		toSerialize["s3_superuser"] = o.S3Superuser
	}
	if !IsNil(o.S3PoliciesIds) {
		toSerialize["s3_policies_ids"] = o.S3PoliciesIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UsersAddRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"uid",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersAddRequest := _UsersAddRequest{}

	err = json.Unmarshal(data, &varUsersAddRequest)

	if err != nil {
		return err
	}

	*o = UsersAddRequest(varUsersAddRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "uid")
		delete(additionalProperties, "leading_gid")
		delete(additionalProperties, "gids")
		delete(additionalProperties, "local")
		delete(additionalProperties, "allow_create_bucket")
		delete(additionalProperties, "allow_delete_bucket")
		delete(additionalProperties, "s3_superuser")
		delete(additionalProperties, "s3_policies_ids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUsersAddRequest struct {
	value *UsersAddRequest
	isSet bool
}

func (v NullableUsersAddRequest) Get() *UsersAddRequest {
	return v.value
}

func (v *NullableUsersAddRequest) Set(val *UsersAddRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersAddRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersAddRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersAddRequest(val *UsersAddRequest) *NullableUsersAddRequest {
	return &NullableUsersAddRequest{value: val, isSet: true}
}

func (v NullableUsersAddRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersAddRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


