/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the User type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &User{}

// User struct for User
type User struct {
	Id *int32 `json:"id,omitempty"`
	Guid *string `json:"guid,omitempty"`
	// The name of the user
	Name *string `json:"name,omitempty"`
	Url *string `json:"url,omitempty"`
	Title *string `json:"title,omitempty"`
	Vid *int32 `json:"vid,omitempty"`
	// UID
	Uid *int32 `json:"uid,omitempty"`
	// Leading GID
	LeadingGid *int32 `json:"leading_gid,omitempty"`
	// GID list
	Gids []int32 `json:"gids,omitempty"`
	// Group list
	Groups []string `json:"groups,omitempty"`
	// Group Count
	GroupCount *int32 `json:"group_count,omitempty"`
	// Leading Group
	LeadingGroupName *string `json:"leading_group_name,omitempty"`
	// Leading Group GID
	LeadingGroupGid *int32 `json:"leading_group_gid,omitempty"`
	// SID
	Sid *string `json:"sid,omitempty"`
	// Primary group SID
	PrimaryGroupSid *string `json:"primary_group_sid,omitempty"`
	// SID list
	Sids []string `json:"sids,omitempty"`
	Local *bool `json:"local,omitempty"`
	// Access Keys
	AccessKeys []map[string]interface{} `json:"access_keys,omitempty"`
	// Allow create bucket
	AllowCreateBucket *bool `json:"allow_create_bucket,omitempty"`
	// Allow delete bucket
	AllowDeleteBucket *bool `json:"allow_delete_bucket,omitempty"`
	// S3 superuser
	S3Superuser *bool `json:"s3_superuser,omitempty"`
	// S3 policies IDs
	S3PoliciesIds []int32 `json:"s3_policies_ids,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _User User

// NewUser instantiates a new User object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUser() *User {
	this := User{}
	return &this
}

// NewUserWithDefaults instantiates a new User object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWithDefaults() *User {
	this := User{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *User) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *User) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *User) SetId(v int32) {
	o.Id = &v
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *User) GetGuid() string {
	if o == nil || IsNil(o.Guid) {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetGuidOk() (*string, bool) {
	if o == nil || IsNil(o.Guid) {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *User) HasGuid() bool {
	if o != nil && !IsNil(o.Guid) {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *User) SetGuid(v string) {
	o.Guid = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *User) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *User) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *User) SetName(v string) {
	o.Name = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *User) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *User) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *User) SetUrl(v string) {
	o.Url = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *User) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *User) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *User) SetTitle(v string) {
	o.Title = &v
}

// GetVid returns the Vid field value if set, zero value otherwise.
func (o *User) GetVid() int32 {
	if o == nil || IsNil(o.Vid) {
		var ret int32
		return ret
	}
	return *o.Vid
}

// GetVidOk returns a tuple with the Vid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetVidOk() (*int32, bool) {
	if o == nil || IsNil(o.Vid) {
		return nil, false
	}
	return o.Vid, true
}

// HasVid returns a boolean if a field has been set.
func (o *User) HasVid() bool {
	if o != nil && !IsNil(o.Vid) {
		return true
	}

	return false
}

// SetVid gets a reference to the given int32 and assigns it to the Vid field.
func (o *User) SetVid(v int32) {
	o.Vid = &v
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *User) GetUid() int32 {
	if o == nil || IsNil(o.Uid) {
		var ret int32
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetUidOk() (*int32, bool) {
	if o == nil || IsNil(o.Uid) {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *User) HasUid() bool {
	if o != nil && !IsNil(o.Uid) {
		return true
	}

	return false
}

// SetUid gets a reference to the given int32 and assigns it to the Uid field.
func (o *User) SetUid(v int32) {
	o.Uid = &v
}

// GetLeadingGid returns the LeadingGid field value if set, zero value otherwise.
func (o *User) GetLeadingGid() int32 {
	if o == nil || IsNil(o.LeadingGid) {
		var ret int32
		return ret
	}
	return *o.LeadingGid
}

// GetLeadingGidOk returns a tuple with the LeadingGid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLeadingGidOk() (*int32, bool) {
	if o == nil || IsNil(o.LeadingGid) {
		return nil, false
	}
	return o.LeadingGid, true
}

// HasLeadingGid returns a boolean if a field has been set.
func (o *User) HasLeadingGid() bool {
	if o != nil && !IsNil(o.LeadingGid) {
		return true
	}

	return false
}

// SetLeadingGid gets a reference to the given int32 and assigns it to the LeadingGid field.
func (o *User) SetLeadingGid(v int32) {
	o.LeadingGid = &v
}

// GetGids returns the Gids field value if set, zero value otherwise.
func (o *User) GetGids() []int32 {
	if o == nil || IsNil(o.Gids) {
		var ret []int32
		return ret
	}
	return o.Gids
}

// GetGidsOk returns a tuple with the Gids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetGidsOk() ([]int32, bool) {
	if o == nil || IsNil(o.Gids) {
		return nil, false
	}
	return o.Gids, true
}

// HasGids returns a boolean if a field has been set.
func (o *User) HasGids() bool {
	if o != nil && !IsNil(o.Gids) {
		return true
	}

	return false
}

// SetGids gets a reference to the given []int32 and assigns it to the Gids field.
func (o *User) SetGids(v []int32) {
	o.Gids = v
}

// GetGroups returns the Groups field value if set, zero value otherwise.
func (o *User) GetGroups() []string {
	if o == nil || IsNil(o.Groups) {
		var ret []string
		return ret
	}
	return o.Groups
}

// GetGroupsOk returns a tuple with the Groups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetGroupsOk() ([]string, bool) {
	if o == nil || IsNil(o.Groups) {
		return nil, false
	}
	return o.Groups, true
}

// HasGroups returns a boolean if a field has been set.
func (o *User) HasGroups() bool {
	if o != nil && !IsNil(o.Groups) {
		return true
	}

	return false
}

// SetGroups gets a reference to the given []string and assigns it to the Groups field.
func (o *User) SetGroups(v []string) {
	o.Groups = v
}

// GetGroupCount returns the GroupCount field value if set, zero value otherwise.
func (o *User) GetGroupCount() int32 {
	if o == nil || IsNil(o.GroupCount) {
		var ret int32
		return ret
	}
	return *o.GroupCount
}

// GetGroupCountOk returns a tuple with the GroupCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetGroupCountOk() (*int32, bool) {
	if o == nil || IsNil(o.GroupCount) {
		return nil, false
	}
	return o.GroupCount, true
}

// HasGroupCount returns a boolean if a field has been set.
func (o *User) HasGroupCount() bool {
	if o != nil && !IsNil(o.GroupCount) {
		return true
	}

	return false
}

// SetGroupCount gets a reference to the given int32 and assigns it to the GroupCount field.
func (o *User) SetGroupCount(v int32) {
	o.GroupCount = &v
}

// GetLeadingGroupName returns the LeadingGroupName field value if set, zero value otherwise.
func (o *User) GetLeadingGroupName() string {
	if o == nil || IsNil(o.LeadingGroupName) {
		var ret string
		return ret
	}
	return *o.LeadingGroupName
}

// GetLeadingGroupNameOk returns a tuple with the LeadingGroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLeadingGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.LeadingGroupName) {
		return nil, false
	}
	return o.LeadingGroupName, true
}

// HasLeadingGroupName returns a boolean if a field has been set.
func (o *User) HasLeadingGroupName() bool {
	if o != nil && !IsNil(o.LeadingGroupName) {
		return true
	}

	return false
}

// SetLeadingGroupName gets a reference to the given string and assigns it to the LeadingGroupName field.
func (o *User) SetLeadingGroupName(v string) {
	o.LeadingGroupName = &v
}

// GetLeadingGroupGid returns the LeadingGroupGid field value if set, zero value otherwise.
func (o *User) GetLeadingGroupGid() int32 {
	if o == nil || IsNil(o.LeadingGroupGid) {
		var ret int32
		return ret
	}
	return *o.LeadingGroupGid
}

// GetLeadingGroupGidOk returns a tuple with the LeadingGroupGid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLeadingGroupGidOk() (*int32, bool) {
	if o == nil || IsNil(o.LeadingGroupGid) {
		return nil, false
	}
	return o.LeadingGroupGid, true
}

// HasLeadingGroupGid returns a boolean if a field has been set.
func (o *User) HasLeadingGroupGid() bool {
	if o != nil && !IsNil(o.LeadingGroupGid) {
		return true
	}

	return false
}

// SetLeadingGroupGid gets a reference to the given int32 and assigns it to the LeadingGroupGid field.
func (o *User) SetLeadingGroupGid(v int32) {
	o.LeadingGroupGid = &v
}

// GetSid returns the Sid field value if set, zero value otherwise.
func (o *User) GetSid() string {
	if o == nil || IsNil(o.Sid) {
		var ret string
		return ret
	}
	return *o.Sid
}

// GetSidOk returns a tuple with the Sid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetSidOk() (*string, bool) {
	if o == nil || IsNil(o.Sid) {
		return nil, false
	}
	return o.Sid, true
}

// HasSid returns a boolean if a field has been set.
func (o *User) HasSid() bool {
	if o != nil && !IsNil(o.Sid) {
		return true
	}

	return false
}

// SetSid gets a reference to the given string and assigns it to the Sid field.
func (o *User) SetSid(v string) {
	o.Sid = &v
}

// GetPrimaryGroupSid returns the PrimaryGroupSid field value if set, zero value otherwise.
func (o *User) GetPrimaryGroupSid() string {
	if o == nil || IsNil(o.PrimaryGroupSid) {
		var ret string
		return ret
	}
	return *o.PrimaryGroupSid
}

// GetPrimaryGroupSidOk returns a tuple with the PrimaryGroupSid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetPrimaryGroupSidOk() (*string, bool) {
	if o == nil || IsNil(o.PrimaryGroupSid) {
		return nil, false
	}
	return o.PrimaryGroupSid, true
}

// HasPrimaryGroupSid returns a boolean if a field has been set.
func (o *User) HasPrimaryGroupSid() bool {
	if o != nil && !IsNil(o.PrimaryGroupSid) {
		return true
	}

	return false
}

// SetPrimaryGroupSid gets a reference to the given string and assigns it to the PrimaryGroupSid field.
func (o *User) SetPrimaryGroupSid(v string) {
	o.PrimaryGroupSid = &v
}

// GetSids returns the Sids field value if set, zero value otherwise.
func (o *User) GetSids() []string {
	if o == nil || IsNil(o.Sids) {
		var ret []string
		return ret
	}
	return o.Sids
}

// GetSidsOk returns a tuple with the Sids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetSidsOk() ([]string, bool) {
	if o == nil || IsNil(o.Sids) {
		return nil, false
	}
	return o.Sids, true
}

// HasSids returns a boolean if a field has been set.
func (o *User) HasSids() bool {
	if o != nil && !IsNil(o.Sids) {
		return true
	}

	return false
}

// SetSids gets a reference to the given []string and assigns it to the Sids field.
func (o *User) SetSids(v []string) {
	o.Sids = v
}

// GetLocal returns the Local field value if set, zero value otherwise.
func (o *User) GetLocal() bool {
	if o == nil || IsNil(o.Local) {
		var ret bool
		return ret
	}
	return *o.Local
}

// GetLocalOk returns a tuple with the Local field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetLocalOk() (*bool, bool) {
	if o == nil || IsNil(o.Local) {
		return nil, false
	}
	return o.Local, true
}

// HasLocal returns a boolean if a field has been set.
func (o *User) HasLocal() bool {
	if o != nil && !IsNil(o.Local) {
		return true
	}

	return false
}

// SetLocal gets a reference to the given bool and assigns it to the Local field.
func (o *User) SetLocal(v bool) {
	o.Local = &v
}

// GetAccessKeys returns the AccessKeys field value if set, zero value otherwise.
func (o *User) GetAccessKeys() []map[string]interface{} {
	if o == nil || IsNil(o.AccessKeys) {
		var ret []map[string]interface{}
		return ret
	}
	return o.AccessKeys
}

// GetAccessKeysOk returns a tuple with the AccessKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetAccessKeysOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.AccessKeys) {
		return nil, false
	}
	return o.AccessKeys, true
}

// HasAccessKeys returns a boolean if a field has been set.
func (o *User) HasAccessKeys() bool {
	if o != nil && !IsNil(o.AccessKeys) {
		return true
	}

	return false
}

// SetAccessKeys gets a reference to the given []map[string]interface{} and assigns it to the AccessKeys field.
func (o *User) SetAccessKeys(v []map[string]interface{}) {
	o.AccessKeys = v
}

// GetAllowCreateBucket returns the AllowCreateBucket field value if set, zero value otherwise.
func (o *User) GetAllowCreateBucket() bool {
	if o == nil || IsNil(o.AllowCreateBucket) {
		var ret bool
		return ret
	}
	return *o.AllowCreateBucket
}

// GetAllowCreateBucketOk returns a tuple with the AllowCreateBucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetAllowCreateBucketOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowCreateBucket) {
		return nil, false
	}
	return o.AllowCreateBucket, true
}

// HasAllowCreateBucket returns a boolean if a field has been set.
func (o *User) HasAllowCreateBucket() bool {
	if o != nil && !IsNil(o.AllowCreateBucket) {
		return true
	}

	return false
}

// SetAllowCreateBucket gets a reference to the given bool and assigns it to the AllowCreateBucket field.
func (o *User) SetAllowCreateBucket(v bool) {
	o.AllowCreateBucket = &v
}

// GetAllowDeleteBucket returns the AllowDeleteBucket field value if set, zero value otherwise.
func (o *User) GetAllowDeleteBucket() bool {
	if o == nil || IsNil(o.AllowDeleteBucket) {
		var ret bool
		return ret
	}
	return *o.AllowDeleteBucket
}

// GetAllowDeleteBucketOk returns a tuple with the AllowDeleteBucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetAllowDeleteBucketOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowDeleteBucket) {
		return nil, false
	}
	return o.AllowDeleteBucket, true
}

// HasAllowDeleteBucket returns a boolean if a field has been set.
func (o *User) HasAllowDeleteBucket() bool {
	if o != nil && !IsNil(o.AllowDeleteBucket) {
		return true
	}

	return false
}

// SetAllowDeleteBucket gets a reference to the given bool and assigns it to the AllowDeleteBucket field.
func (o *User) SetAllowDeleteBucket(v bool) {
	o.AllowDeleteBucket = &v
}

// GetS3Superuser returns the S3Superuser field value if set, zero value otherwise.
func (o *User) GetS3Superuser() bool {
	if o == nil || IsNil(o.S3Superuser) {
		var ret bool
		return ret
	}
	return *o.S3Superuser
}

// GetS3SuperuserOk returns a tuple with the S3Superuser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetS3SuperuserOk() (*bool, bool) {
	if o == nil || IsNil(o.S3Superuser) {
		return nil, false
	}
	return o.S3Superuser, true
}

// HasS3Superuser returns a boolean if a field has been set.
func (o *User) HasS3Superuser() bool {
	if o != nil && !IsNil(o.S3Superuser) {
		return true
	}

	return false
}

// SetS3Superuser gets a reference to the given bool and assigns it to the S3Superuser field.
func (o *User) SetS3Superuser(v bool) {
	o.S3Superuser = &v
}

// GetS3PoliciesIds returns the S3PoliciesIds field value if set, zero value otherwise.
func (o *User) GetS3PoliciesIds() []int32 {
	if o == nil || IsNil(o.S3PoliciesIds) {
		var ret []int32
		return ret
	}
	return o.S3PoliciesIds
}

// GetS3PoliciesIdsOk returns a tuple with the S3PoliciesIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetS3PoliciesIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.S3PoliciesIds) {
		return nil, false
	}
	return o.S3PoliciesIds, true
}

// HasS3PoliciesIds returns a boolean if a field has been set.
func (o *User) HasS3PoliciesIds() bool {
	if o != nil && !IsNil(o.S3PoliciesIds) {
		return true
	}

	return false
}

// SetS3PoliciesIds gets a reference to the given []int32 and assigns it to the S3PoliciesIds field.
func (o *User) SetS3PoliciesIds(v []int32) {
	o.S3PoliciesIds = v
}

func (o User) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o User) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Guid) {
		toSerialize["guid"] = o.Guid
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Vid) {
		toSerialize["vid"] = o.Vid
	}
	if !IsNil(o.Uid) {
		toSerialize["uid"] = o.Uid
	}
	if !IsNil(o.LeadingGid) {
		toSerialize["leading_gid"] = o.LeadingGid
	}
	if !IsNil(o.Gids) {
		toSerialize["gids"] = o.Gids
	}
	if !IsNil(o.Groups) {
		toSerialize["groups"] = o.Groups
	}
	if !IsNil(o.GroupCount) {
		toSerialize["group_count"] = o.GroupCount
	}
	if !IsNil(o.LeadingGroupName) {
		toSerialize["leading_group_name"] = o.LeadingGroupName
	}
	if !IsNil(o.LeadingGroupGid) {
		toSerialize["leading_group_gid"] = o.LeadingGroupGid
	}
	if !IsNil(o.Sid) {
		toSerialize["sid"] = o.Sid
	}
	if !IsNil(o.PrimaryGroupSid) {
		toSerialize["primary_group_sid"] = o.PrimaryGroupSid
	}
	if !IsNil(o.Sids) {
		toSerialize["sids"] = o.Sids
	}
	if !IsNil(o.Local) {
		toSerialize["local"] = o.Local
	}
	if !IsNil(o.AccessKeys) {
		toSerialize["access_keys"] = o.AccessKeys
	}
	if !IsNil(o.AllowCreateBucket) {
		toSerialize["allow_create_bucket"] = o.AllowCreateBucket
	}
	if !IsNil(o.AllowDeleteBucket) {
		toSerialize["allow_delete_bucket"] = o.AllowDeleteBucket
	}
	if !IsNil(o.S3Superuser) {
		toSerialize["s3_superuser"] = o.S3Superuser
	}
	if !IsNil(o.S3PoliciesIds) {
		toSerialize["s3_policies_ids"] = o.S3PoliciesIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *User) UnmarshalJSON(data []byte) (err error) {
	varUser := _User{}

	err = json.Unmarshal(data, &varUser)

	if err != nil {
		return err
	}

	*o = User(varUser)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "guid")
		delete(additionalProperties, "name")
		delete(additionalProperties, "url")
		delete(additionalProperties, "title")
		delete(additionalProperties, "vid")
		delete(additionalProperties, "uid")
		delete(additionalProperties, "leading_gid")
		delete(additionalProperties, "gids")
		delete(additionalProperties, "groups")
		delete(additionalProperties, "group_count")
		delete(additionalProperties, "leading_group_name")
		delete(additionalProperties, "leading_group_gid")
		delete(additionalProperties, "sid")
		delete(additionalProperties, "primary_group_sid")
		delete(additionalProperties, "sids")
		delete(additionalProperties, "local")
		delete(additionalProperties, "access_keys")
		delete(additionalProperties, "allow_create_bucket")
		delete(additionalProperties, "allow_delete_bucket")
		delete(additionalProperties, "s3_superuser")
		delete(additionalProperties, "s3_policies_ids")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUser struct {
	value *User
	isSet bool
}

func (v NullableUser) Get() *User {
	return v.value
}

func (v *NullableUser) Set(val *User) {
	v.value = val
	v.isSet = true
}

func (v NullableUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUser(val *User) *NullableUser {
	return &NullableUser{value: val, isSet: true}
}

func (v NullableUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


