/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProtectionpoliciesCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProtectionpoliciesCreateRequest{}

// ProtectionpoliciesCreateRequest struct for ProtectionpoliciesCreateRequest
type ProtectionpoliciesCreateRequest struct {
	// Do not specify this parameter.
	Id *int32 `json:"id,omitempty"`
	// 
	Name *string `json:"name,omitempty"`
	// Do not specify this parameter.
	Guid *string `json:"guid,omitempty"`
	// ID of the remote peer. Specify ID of a ReplicationTarget (aka S3 replication peer) if clone_type is CLOUD_REPLICATION. Specify the ID of a NativeReplicationRemoteTarget if clone_type is NATIVE_REPLICATION.
	TargetObjectId *int32 `json:"target_object_id,omitempty"`
	// Defines the schedule for snapshot creation and the local and remote retention policies.
	Frames map[string]interface{} `json:"frames,omitempty"`
	// The prefix for names of snapshots created by the policy
	Prefix *string `json:"prefix,omitempty"`
	// Specify the type of data protection. CLOUD_REPLICATION is S3 backup. LOCAL means local snapshots without replication.
	CloneType *string `json:"clone_type,omitempty"`
	// Indestructible the Protection policy from being deleted
	Indestructible *bool `json:"indestructible,omitempty"`
	// Indicates if Protection Policy will be used for vast catalogue. There may only be 1 such policy.
	BigCatalog *bool `json:"big_catalog,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProtectionpoliciesCreateRequest ProtectionpoliciesCreateRequest

// NewProtectionpoliciesCreateRequest instantiates a new ProtectionpoliciesCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtectionpoliciesCreateRequest() *ProtectionpoliciesCreateRequest {
	this := ProtectionpoliciesCreateRequest{}
	return &this
}

// NewProtectionpoliciesCreateRequestWithDefaults instantiates a new ProtectionpoliciesCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtectionpoliciesCreateRequestWithDefaults() *ProtectionpoliciesCreateRequest {
	this := ProtectionpoliciesCreateRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProtectionpoliciesCreateRequest) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectionpoliciesCreateRequest) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProtectionpoliciesCreateRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ProtectionpoliciesCreateRequest) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProtectionpoliciesCreateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectionpoliciesCreateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProtectionpoliciesCreateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProtectionpoliciesCreateRequest) SetName(v string) {
	o.Name = &v
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *ProtectionpoliciesCreateRequest) GetGuid() string {
	if o == nil || IsNil(o.Guid) {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectionpoliciesCreateRequest) GetGuidOk() (*string, bool) {
	if o == nil || IsNil(o.Guid) {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *ProtectionpoliciesCreateRequest) HasGuid() bool {
	if o != nil && !IsNil(o.Guid) {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *ProtectionpoliciesCreateRequest) SetGuid(v string) {
	o.Guid = &v
}

// GetTargetObjectId returns the TargetObjectId field value if set, zero value otherwise.
func (o *ProtectionpoliciesCreateRequest) GetTargetObjectId() int32 {
	if o == nil || IsNil(o.TargetObjectId) {
		var ret int32
		return ret
	}
	return *o.TargetObjectId
}

// GetTargetObjectIdOk returns a tuple with the TargetObjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectionpoliciesCreateRequest) GetTargetObjectIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TargetObjectId) {
		return nil, false
	}
	return o.TargetObjectId, true
}

// HasTargetObjectId returns a boolean if a field has been set.
func (o *ProtectionpoliciesCreateRequest) HasTargetObjectId() bool {
	if o != nil && !IsNil(o.TargetObjectId) {
		return true
	}

	return false
}

// SetTargetObjectId gets a reference to the given int32 and assigns it to the TargetObjectId field.
func (o *ProtectionpoliciesCreateRequest) SetTargetObjectId(v int32) {
	o.TargetObjectId = &v
}

// GetFrames returns the Frames field value if set, zero value otherwise.
func (o *ProtectionpoliciesCreateRequest) GetFrames() map[string]interface{} {
	if o == nil || IsNil(o.Frames) {
		var ret map[string]interface{}
		return ret
	}
	return o.Frames
}

// GetFramesOk returns a tuple with the Frames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectionpoliciesCreateRequest) GetFramesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Frames) {
		return map[string]interface{}{}, false
	}
	return o.Frames, true
}

// HasFrames returns a boolean if a field has been set.
func (o *ProtectionpoliciesCreateRequest) HasFrames() bool {
	if o != nil && !IsNil(o.Frames) {
		return true
	}

	return false
}

// SetFrames gets a reference to the given map[string]interface{} and assigns it to the Frames field.
func (o *ProtectionpoliciesCreateRequest) SetFrames(v map[string]interface{}) {
	o.Frames = v
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *ProtectionpoliciesCreateRequest) GetPrefix() string {
	if o == nil || IsNil(o.Prefix) {
		var ret string
		return ret
	}
	return *o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectionpoliciesCreateRequest) GetPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.Prefix) {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *ProtectionpoliciesCreateRequest) HasPrefix() bool {
	if o != nil && !IsNil(o.Prefix) {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given string and assigns it to the Prefix field.
func (o *ProtectionpoliciesCreateRequest) SetPrefix(v string) {
	o.Prefix = &v
}

// GetCloneType returns the CloneType field value if set, zero value otherwise.
func (o *ProtectionpoliciesCreateRequest) GetCloneType() string {
	if o == nil || IsNil(o.CloneType) {
		var ret string
		return ret
	}
	return *o.CloneType
}

// GetCloneTypeOk returns a tuple with the CloneType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectionpoliciesCreateRequest) GetCloneTypeOk() (*string, bool) {
	if o == nil || IsNil(o.CloneType) {
		return nil, false
	}
	return o.CloneType, true
}

// HasCloneType returns a boolean if a field has been set.
func (o *ProtectionpoliciesCreateRequest) HasCloneType() bool {
	if o != nil && !IsNil(o.CloneType) {
		return true
	}

	return false
}

// SetCloneType gets a reference to the given string and assigns it to the CloneType field.
func (o *ProtectionpoliciesCreateRequest) SetCloneType(v string) {
	o.CloneType = &v
}

// GetIndestructible returns the Indestructible field value if set, zero value otherwise.
func (o *ProtectionpoliciesCreateRequest) GetIndestructible() bool {
	if o == nil || IsNil(o.Indestructible) {
		var ret bool
		return ret
	}
	return *o.Indestructible
}

// GetIndestructibleOk returns a tuple with the Indestructible field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectionpoliciesCreateRequest) GetIndestructibleOk() (*bool, bool) {
	if o == nil || IsNil(o.Indestructible) {
		return nil, false
	}
	return o.Indestructible, true
}

// HasIndestructible returns a boolean if a field has been set.
func (o *ProtectionpoliciesCreateRequest) HasIndestructible() bool {
	if o != nil && !IsNil(o.Indestructible) {
		return true
	}

	return false
}

// SetIndestructible gets a reference to the given bool and assigns it to the Indestructible field.
func (o *ProtectionpoliciesCreateRequest) SetIndestructible(v bool) {
	o.Indestructible = &v
}

// GetBigCatalog returns the BigCatalog field value if set, zero value otherwise.
func (o *ProtectionpoliciesCreateRequest) GetBigCatalog() bool {
	if o == nil || IsNil(o.BigCatalog) {
		var ret bool
		return ret
	}
	return *o.BigCatalog
}

// GetBigCatalogOk returns a tuple with the BigCatalog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectionpoliciesCreateRequest) GetBigCatalogOk() (*bool, bool) {
	if o == nil || IsNil(o.BigCatalog) {
		return nil, false
	}
	return o.BigCatalog, true
}

// HasBigCatalog returns a boolean if a field has been set.
func (o *ProtectionpoliciesCreateRequest) HasBigCatalog() bool {
	if o != nil && !IsNil(o.BigCatalog) {
		return true
	}

	return false
}

// SetBigCatalog gets a reference to the given bool and assigns it to the BigCatalog field.
func (o *ProtectionpoliciesCreateRequest) SetBigCatalog(v bool) {
	o.BigCatalog = &v
}

func (o ProtectionpoliciesCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProtectionpoliciesCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Guid) {
		toSerialize["guid"] = o.Guid
	}
	if !IsNil(o.TargetObjectId) {
		toSerialize["target_object_id"] = o.TargetObjectId
	}
	if !IsNil(o.Frames) {
		toSerialize["frames"] = o.Frames
	}
	if !IsNil(o.Prefix) {
		toSerialize["prefix"] = o.Prefix
	}
	if !IsNil(o.CloneType) {
		toSerialize["clone_type"] = o.CloneType
	}
	if !IsNil(o.Indestructible) {
		toSerialize["indestructible"] = o.Indestructible
	}
	if !IsNil(o.BigCatalog) {
		toSerialize["big_catalog"] = o.BigCatalog
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProtectionpoliciesCreateRequest) UnmarshalJSON(data []byte) (err error) {
	varProtectionpoliciesCreateRequest := _ProtectionpoliciesCreateRequest{}

	err = json.Unmarshal(data, &varProtectionpoliciesCreateRequest)

	if err != nil {
		return err
	}

	*o = ProtectionpoliciesCreateRequest(varProtectionpoliciesCreateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "guid")
		delete(additionalProperties, "target_object_id")
		delete(additionalProperties, "frames")
		delete(additionalProperties, "prefix")
		delete(additionalProperties, "clone_type")
		delete(additionalProperties, "indestructible")
		delete(additionalProperties, "big_catalog")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProtectionpoliciesCreateRequest struct {
	value *ProtectionpoliciesCreateRequest
	isSet bool
}

func (v NullableProtectionpoliciesCreateRequest) Get() *ProtectionpoliciesCreateRequest {
	return v.value
}

func (v *NullableProtectionpoliciesCreateRequest) Set(val *ProtectionpoliciesCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProtectionpoliciesCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProtectionpoliciesCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtectionpoliciesCreateRequest(val *ProtectionpoliciesCreateRequest) *NullableProtectionpoliciesCreateRequest {
	return &NullableProtectionpoliciesCreateRequest{value: val, isSet: true}
}

func (v NullableProtectionpoliciesCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtectionpoliciesCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


