/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ClusterAdvanced type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterAdvanced{}

// ClusterAdvanced struct for ClusterAdvanced
type ClusterAdvanced struct {
	// Number of shards
	NumberOfShares *int32 `json:"number_of_shares,omitempty"`
	// Total cluster capacity in GiB
	TotalCapacityInGib *float32 `json:"total_capacity_in_gib,omitempty"`
	// Used cluster capacity in GiB
	UsedCapacityInGib *float32 `json:"used_capacity_in_gib,omitempty"`
	// Number of protected shards
	NumberOfProtectedShares *int32 `json:"number_of_protected_shares,omitempty"`
	// Number of unprotected shares
	NumberOfUnprotectedShares *int32 `json:"number_of_unprotected_shares,omitempty"`
	// Number of files and directories
	NumberOfFilesAndDirectories *int32 `json:"number_of_files_and_directories,omitempty"`
	ReadIopsPerSec *int32 `json:"read_iops_per_sec,omitempty"`
	ReadLatencyInMillisec *float32 `json:"read_latency_in_millisec,omitempty"`
	ReadBandwidthInBytesPerSec *int32 `json:"read_bandwidth_in_bytes_per_sec,omitempty"`
	WriteIopsPerSec *int32 `json:"write_iops_per_sec,omitempty"`
	WriteLatencyInMillisec *float32 `json:"write_latency_in_millisec,omitempty"`
	WriteBandwidthInBytesPerSec *int32 `json:"write_bandwidth_in_bytes_per_sec,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ClusterAdvanced ClusterAdvanced

// NewClusterAdvanced instantiates a new ClusterAdvanced object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterAdvanced() *ClusterAdvanced {
	this := ClusterAdvanced{}
	return &this
}

// NewClusterAdvancedWithDefaults instantiates a new ClusterAdvanced object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterAdvancedWithDefaults() *ClusterAdvanced {
	this := ClusterAdvanced{}
	return &this
}

// GetNumberOfShares returns the NumberOfShares field value if set, zero value otherwise.
func (o *ClusterAdvanced) GetNumberOfShares() int32 {
	if o == nil || IsNil(o.NumberOfShares) {
		var ret int32
		return ret
	}
	return *o.NumberOfShares
}

// GetNumberOfSharesOk returns a tuple with the NumberOfShares field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAdvanced) GetNumberOfSharesOk() (*int32, bool) {
	if o == nil || IsNil(o.NumberOfShares) {
		return nil, false
	}
	return o.NumberOfShares, true
}

// HasNumberOfShares returns a boolean if a field has been set.
func (o *ClusterAdvanced) HasNumberOfShares() bool {
	if o != nil && !IsNil(o.NumberOfShares) {
		return true
	}

	return false
}

// SetNumberOfShares gets a reference to the given int32 and assigns it to the NumberOfShares field.
func (o *ClusterAdvanced) SetNumberOfShares(v int32) {
	o.NumberOfShares = &v
}

// GetTotalCapacityInGib returns the TotalCapacityInGib field value if set, zero value otherwise.
func (o *ClusterAdvanced) GetTotalCapacityInGib() float32 {
	if o == nil || IsNil(o.TotalCapacityInGib) {
		var ret float32
		return ret
	}
	return *o.TotalCapacityInGib
}

// GetTotalCapacityInGibOk returns a tuple with the TotalCapacityInGib field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAdvanced) GetTotalCapacityInGibOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalCapacityInGib) {
		return nil, false
	}
	return o.TotalCapacityInGib, true
}

// HasTotalCapacityInGib returns a boolean if a field has been set.
func (o *ClusterAdvanced) HasTotalCapacityInGib() bool {
	if o != nil && !IsNil(o.TotalCapacityInGib) {
		return true
	}

	return false
}

// SetTotalCapacityInGib gets a reference to the given float32 and assigns it to the TotalCapacityInGib field.
func (o *ClusterAdvanced) SetTotalCapacityInGib(v float32) {
	o.TotalCapacityInGib = &v
}

// GetUsedCapacityInGib returns the UsedCapacityInGib field value if set, zero value otherwise.
func (o *ClusterAdvanced) GetUsedCapacityInGib() float32 {
	if o == nil || IsNil(o.UsedCapacityInGib) {
		var ret float32
		return ret
	}
	return *o.UsedCapacityInGib
}

// GetUsedCapacityInGibOk returns a tuple with the UsedCapacityInGib field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAdvanced) GetUsedCapacityInGibOk() (*float32, bool) {
	if o == nil || IsNil(o.UsedCapacityInGib) {
		return nil, false
	}
	return o.UsedCapacityInGib, true
}

// HasUsedCapacityInGib returns a boolean if a field has been set.
func (o *ClusterAdvanced) HasUsedCapacityInGib() bool {
	if o != nil && !IsNil(o.UsedCapacityInGib) {
		return true
	}

	return false
}

// SetUsedCapacityInGib gets a reference to the given float32 and assigns it to the UsedCapacityInGib field.
func (o *ClusterAdvanced) SetUsedCapacityInGib(v float32) {
	o.UsedCapacityInGib = &v
}

// GetNumberOfProtectedShares returns the NumberOfProtectedShares field value if set, zero value otherwise.
func (o *ClusterAdvanced) GetNumberOfProtectedShares() int32 {
	if o == nil || IsNil(o.NumberOfProtectedShares) {
		var ret int32
		return ret
	}
	return *o.NumberOfProtectedShares
}

// GetNumberOfProtectedSharesOk returns a tuple with the NumberOfProtectedShares field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAdvanced) GetNumberOfProtectedSharesOk() (*int32, bool) {
	if o == nil || IsNil(o.NumberOfProtectedShares) {
		return nil, false
	}
	return o.NumberOfProtectedShares, true
}

// HasNumberOfProtectedShares returns a boolean if a field has been set.
func (o *ClusterAdvanced) HasNumberOfProtectedShares() bool {
	if o != nil && !IsNil(o.NumberOfProtectedShares) {
		return true
	}

	return false
}

// SetNumberOfProtectedShares gets a reference to the given int32 and assigns it to the NumberOfProtectedShares field.
func (o *ClusterAdvanced) SetNumberOfProtectedShares(v int32) {
	o.NumberOfProtectedShares = &v
}

// GetNumberOfUnprotectedShares returns the NumberOfUnprotectedShares field value if set, zero value otherwise.
func (o *ClusterAdvanced) GetNumberOfUnprotectedShares() int32 {
	if o == nil || IsNil(o.NumberOfUnprotectedShares) {
		var ret int32
		return ret
	}
	return *o.NumberOfUnprotectedShares
}

// GetNumberOfUnprotectedSharesOk returns a tuple with the NumberOfUnprotectedShares field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAdvanced) GetNumberOfUnprotectedSharesOk() (*int32, bool) {
	if o == nil || IsNil(o.NumberOfUnprotectedShares) {
		return nil, false
	}
	return o.NumberOfUnprotectedShares, true
}

// HasNumberOfUnprotectedShares returns a boolean if a field has been set.
func (o *ClusterAdvanced) HasNumberOfUnprotectedShares() bool {
	if o != nil && !IsNil(o.NumberOfUnprotectedShares) {
		return true
	}

	return false
}

// SetNumberOfUnprotectedShares gets a reference to the given int32 and assigns it to the NumberOfUnprotectedShares field.
func (o *ClusterAdvanced) SetNumberOfUnprotectedShares(v int32) {
	o.NumberOfUnprotectedShares = &v
}

// GetNumberOfFilesAndDirectories returns the NumberOfFilesAndDirectories field value if set, zero value otherwise.
func (o *ClusterAdvanced) GetNumberOfFilesAndDirectories() int32 {
	if o == nil || IsNil(o.NumberOfFilesAndDirectories) {
		var ret int32
		return ret
	}
	return *o.NumberOfFilesAndDirectories
}

// GetNumberOfFilesAndDirectoriesOk returns a tuple with the NumberOfFilesAndDirectories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAdvanced) GetNumberOfFilesAndDirectoriesOk() (*int32, bool) {
	if o == nil || IsNil(o.NumberOfFilesAndDirectories) {
		return nil, false
	}
	return o.NumberOfFilesAndDirectories, true
}

// HasNumberOfFilesAndDirectories returns a boolean if a field has been set.
func (o *ClusterAdvanced) HasNumberOfFilesAndDirectories() bool {
	if o != nil && !IsNil(o.NumberOfFilesAndDirectories) {
		return true
	}

	return false
}

// SetNumberOfFilesAndDirectories gets a reference to the given int32 and assigns it to the NumberOfFilesAndDirectories field.
func (o *ClusterAdvanced) SetNumberOfFilesAndDirectories(v int32) {
	o.NumberOfFilesAndDirectories = &v
}

// GetReadIopsPerSec returns the ReadIopsPerSec field value if set, zero value otherwise.
func (o *ClusterAdvanced) GetReadIopsPerSec() int32 {
	if o == nil || IsNil(o.ReadIopsPerSec) {
		var ret int32
		return ret
	}
	return *o.ReadIopsPerSec
}

// GetReadIopsPerSecOk returns a tuple with the ReadIopsPerSec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAdvanced) GetReadIopsPerSecOk() (*int32, bool) {
	if o == nil || IsNil(o.ReadIopsPerSec) {
		return nil, false
	}
	return o.ReadIopsPerSec, true
}

// HasReadIopsPerSec returns a boolean if a field has been set.
func (o *ClusterAdvanced) HasReadIopsPerSec() bool {
	if o != nil && !IsNil(o.ReadIopsPerSec) {
		return true
	}

	return false
}

// SetReadIopsPerSec gets a reference to the given int32 and assigns it to the ReadIopsPerSec field.
func (o *ClusterAdvanced) SetReadIopsPerSec(v int32) {
	o.ReadIopsPerSec = &v
}

// GetReadLatencyInMillisec returns the ReadLatencyInMillisec field value if set, zero value otherwise.
func (o *ClusterAdvanced) GetReadLatencyInMillisec() float32 {
	if o == nil || IsNil(o.ReadLatencyInMillisec) {
		var ret float32
		return ret
	}
	return *o.ReadLatencyInMillisec
}

// GetReadLatencyInMillisecOk returns a tuple with the ReadLatencyInMillisec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAdvanced) GetReadLatencyInMillisecOk() (*float32, bool) {
	if o == nil || IsNil(o.ReadLatencyInMillisec) {
		return nil, false
	}
	return o.ReadLatencyInMillisec, true
}

// HasReadLatencyInMillisec returns a boolean if a field has been set.
func (o *ClusterAdvanced) HasReadLatencyInMillisec() bool {
	if o != nil && !IsNil(o.ReadLatencyInMillisec) {
		return true
	}

	return false
}

// SetReadLatencyInMillisec gets a reference to the given float32 and assigns it to the ReadLatencyInMillisec field.
func (o *ClusterAdvanced) SetReadLatencyInMillisec(v float32) {
	o.ReadLatencyInMillisec = &v
}

// GetReadBandwidthInBytesPerSec returns the ReadBandwidthInBytesPerSec field value if set, zero value otherwise.
func (o *ClusterAdvanced) GetReadBandwidthInBytesPerSec() int32 {
	if o == nil || IsNil(o.ReadBandwidthInBytesPerSec) {
		var ret int32
		return ret
	}
	return *o.ReadBandwidthInBytesPerSec
}

// GetReadBandwidthInBytesPerSecOk returns a tuple with the ReadBandwidthInBytesPerSec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAdvanced) GetReadBandwidthInBytesPerSecOk() (*int32, bool) {
	if o == nil || IsNil(o.ReadBandwidthInBytesPerSec) {
		return nil, false
	}
	return o.ReadBandwidthInBytesPerSec, true
}

// HasReadBandwidthInBytesPerSec returns a boolean if a field has been set.
func (o *ClusterAdvanced) HasReadBandwidthInBytesPerSec() bool {
	if o != nil && !IsNil(o.ReadBandwidthInBytesPerSec) {
		return true
	}

	return false
}

// SetReadBandwidthInBytesPerSec gets a reference to the given int32 and assigns it to the ReadBandwidthInBytesPerSec field.
func (o *ClusterAdvanced) SetReadBandwidthInBytesPerSec(v int32) {
	o.ReadBandwidthInBytesPerSec = &v
}

// GetWriteIopsPerSec returns the WriteIopsPerSec field value if set, zero value otherwise.
func (o *ClusterAdvanced) GetWriteIopsPerSec() int32 {
	if o == nil || IsNil(o.WriteIopsPerSec) {
		var ret int32
		return ret
	}
	return *o.WriteIopsPerSec
}

// GetWriteIopsPerSecOk returns a tuple with the WriteIopsPerSec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAdvanced) GetWriteIopsPerSecOk() (*int32, bool) {
	if o == nil || IsNil(o.WriteIopsPerSec) {
		return nil, false
	}
	return o.WriteIopsPerSec, true
}

// HasWriteIopsPerSec returns a boolean if a field has been set.
func (o *ClusterAdvanced) HasWriteIopsPerSec() bool {
	if o != nil && !IsNil(o.WriteIopsPerSec) {
		return true
	}

	return false
}

// SetWriteIopsPerSec gets a reference to the given int32 and assigns it to the WriteIopsPerSec field.
func (o *ClusterAdvanced) SetWriteIopsPerSec(v int32) {
	o.WriteIopsPerSec = &v
}

// GetWriteLatencyInMillisec returns the WriteLatencyInMillisec field value if set, zero value otherwise.
func (o *ClusterAdvanced) GetWriteLatencyInMillisec() float32 {
	if o == nil || IsNil(o.WriteLatencyInMillisec) {
		var ret float32
		return ret
	}
	return *o.WriteLatencyInMillisec
}

// GetWriteLatencyInMillisecOk returns a tuple with the WriteLatencyInMillisec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAdvanced) GetWriteLatencyInMillisecOk() (*float32, bool) {
	if o == nil || IsNil(o.WriteLatencyInMillisec) {
		return nil, false
	}
	return o.WriteLatencyInMillisec, true
}

// HasWriteLatencyInMillisec returns a boolean if a field has been set.
func (o *ClusterAdvanced) HasWriteLatencyInMillisec() bool {
	if o != nil && !IsNil(o.WriteLatencyInMillisec) {
		return true
	}

	return false
}

// SetWriteLatencyInMillisec gets a reference to the given float32 and assigns it to the WriteLatencyInMillisec field.
func (o *ClusterAdvanced) SetWriteLatencyInMillisec(v float32) {
	o.WriteLatencyInMillisec = &v
}

// GetWriteBandwidthInBytesPerSec returns the WriteBandwidthInBytesPerSec field value if set, zero value otherwise.
func (o *ClusterAdvanced) GetWriteBandwidthInBytesPerSec() int32 {
	if o == nil || IsNil(o.WriteBandwidthInBytesPerSec) {
		var ret int32
		return ret
	}
	return *o.WriteBandwidthInBytesPerSec
}

// GetWriteBandwidthInBytesPerSecOk returns a tuple with the WriteBandwidthInBytesPerSec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterAdvanced) GetWriteBandwidthInBytesPerSecOk() (*int32, bool) {
	if o == nil || IsNil(o.WriteBandwidthInBytesPerSec) {
		return nil, false
	}
	return o.WriteBandwidthInBytesPerSec, true
}

// HasWriteBandwidthInBytesPerSec returns a boolean if a field has been set.
func (o *ClusterAdvanced) HasWriteBandwidthInBytesPerSec() bool {
	if o != nil && !IsNil(o.WriteBandwidthInBytesPerSec) {
		return true
	}

	return false
}

// SetWriteBandwidthInBytesPerSec gets a reference to the given int32 and assigns it to the WriteBandwidthInBytesPerSec field.
func (o *ClusterAdvanced) SetWriteBandwidthInBytesPerSec(v int32) {
	o.WriteBandwidthInBytesPerSec = &v
}

func (o ClusterAdvanced) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterAdvanced) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NumberOfShares) {
		toSerialize["number_of_shares"] = o.NumberOfShares
	}
	if !IsNil(o.TotalCapacityInGib) {
		toSerialize["total_capacity_in_gib"] = o.TotalCapacityInGib
	}
	if !IsNil(o.UsedCapacityInGib) {
		toSerialize["used_capacity_in_gib"] = o.UsedCapacityInGib
	}
	if !IsNil(o.NumberOfProtectedShares) {
		toSerialize["number_of_protected_shares"] = o.NumberOfProtectedShares
	}
	if !IsNil(o.NumberOfUnprotectedShares) {
		toSerialize["number_of_unprotected_shares"] = o.NumberOfUnprotectedShares
	}
	if !IsNil(o.NumberOfFilesAndDirectories) {
		toSerialize["number_of_files_and_directories"] = o.NumberOfFilesAndDirectories
	}
	if !IsNil(o.ReadIopsPerSec) {
		toSerialize["read_iops_per_sec"] = o.ReadIopsPerSec
	}
	if !IsNil(o.ReadLatencyInMillisec) {
		toSerialize["read_latency_in_millisec"] = o.ReadLatencyInMillisec
	}
	if !IsNil(o.ReadBandwidthInBytesPerSec) {
		toSerialize["read_bandwidth_in_bytes_per_sec"] = o.ReadBandwidthInBytesPerSec
	}
	if !IsNil(o.WriteIopsPerSec) {
		toSerialize["write_iops_per_sec"] = o.WriteIopsPerSec
	}
	if !IsNil(o.WriteLatencyInMillisec) {
		toSerialize["write_latency_in_millisec"] = o.WriteLatencyInMillisec
	}
	if !IsNil(o.WriteBandwidthInBytesPerSec) {
		toSerialize["write_bandwidth_in_bytes_per_sec"] = o.WriteBandwidthInBytesPerSec
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ClusterAdvanced) UnmarshalJSON(data []byte) (err error) {
	varClusterAdvanced := _ClusterAdvanced{}

	err = json.Unmarshal(data, &varClusterAdvanced)

	if err != nil {
		return err
	}

	*o = ClusterAdvanced(varClusterAdvanced)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "number_of_shares")
		delete(additionalProperties, "total_capacity_in_gib")
		delete(additionalProperties, "used_capacity_in_gib")
		delete(additionalProperties, "number_of_protected_shares")
		delete(additionalProperties, "number_of_unprotected_shares")
		delete(additionalProperties, "number_of_files_and_directories")
		delete(additionalProperties, "read_iops_per_sec")
		delete(additionalProperties, "read_latency_in_millisec")
		delete(additionalProperties, "read_bandwidth_in_bytes_per_sec")
		delete(additionalProperties, "write_iops_per_sec")
		delete(additionalProperties, "write_latency_in_millisec")
		delete(additionalProperties, "write_bandwidth_in_bytes_per_sec")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableClusterAdvanced struct {
	value *ClusterAdvanced
	isSet bool
}

func (v NullableClusterAdvanced) Get() *ClusterAdvanced {
	return v.value
}

func (v *NullableClusterAdvanced) Set(val *ClusterAdvanced) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterAdvanced) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterAdvanced) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterAdvanced(val *ClusterAdvanced) *NullableClusterAdvanced {
	return &NullableClusterAdvanced{value: val, isSet: true}
}

func (v NullableClusterAdvanced) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterAdvanced) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


