/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the Vms type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Vms{}

// Vms struct for Vms
type Vms struct {
	Id *int32 `json:"id,omitempty"`
	// Data Bond IP
	Ip *string `json:"ip,omitempty"`
	// Data IP1
	Ip1 *string `json:"ip1,omitempty"`
	// Data IP2
	Ip2 *string `json:"ip2,omitempty"`
	// Management IP
	MgmtIp *string `json:"mgmt_ip,omitempty"`
	// Management VIP
	MgmtVip *string `json:"mgmt_vip,omitempty"`
	// Management IPv6 VIP
	MgmtVipIpv6 *string `json:"mgmt_vip_ipv6,omitempty"`
	// Management CNode
	MgmtCnode *string `json:"mgmt_cnode,omitempty"`
	// VMS inner (NFS) vip
	MgmtInnerVip *string `json:"mgmt_inner_vip,omitempty"`
	// VMS inner VIP CNode
	MgmtInnerVipCnode *string `json:"mgmt_inner_vip_cnode,omitempty"`
	Name string `json:"name"`
	Build *string `json:"build,omitempty"`
	SwVersion *string `json:"sw_version,omitempty"`
	SslCertificate *string `json:"ssl_certificate,omitempty"`
	SslKeyfile *string `json:"ssl_keyfile,omitempty"`
	SslPort *int32 `json:"ssl_port,omitempty"`
	Title *string `json:"title,omitempty"`
	AutoLogoutTimeout *int32 `json:"auto_logout_timeout,omitempty"`
	Created *time.Time `json:"created,omitempty"`
	State *string `json:"state,omitempty"`
	Url *string `json:"url,omitempty"`
	// Is Management HA disabled?
	DisableMgmtHa *bool `json:"disable_mgmt_ha,omitempty"`
	// Disable vms metrics collection
	DisableVmsMetrics *bool `json:"disable_vms_metrics,omitempty"`
	// Format capacity properties to base 10
	CapacityBase10 *bool `json:"capacity_base_10,omitempty"`
	// Format performance properties to base 10
	PerformanceBase10 *bool `json:"performance_base_10,omitempty"`
	// Minimum supported TLS version (e.g.: 1.2)
	MinTlsVersion *string `json:"min_tls_version,omitempty"`
	// The reason for VMS degraded state
	DegradedReason *string `json:"degraded_reason,omitempty"`
	// Validity duration for JWT access token, specify as [DD [HH:[MM:]]]ss
	AccessTokenLifetime *string `json:"access_token_lifetime,omitempty"`
	// Validity duration for JWT refresh token, specify as [DD [HH:[MM:]]]ss
	RefreshTokenLifetime *string `json:"refresh_token_lifetime,omitempty"`
	// Customize login banner for VMS Web UI and CLI
	LoginBanner *string `json:"login_banner,omitempty"`
	// the remaining capacity out of the active capacity
	TotalUsageCapacityPercentage *float32 `json:"total_usage_capacity_percentage,omitempty"`
	// sum of all active licenses capacity
	TotalActiveCapacity *float32 `json:"total_active_capacity,omitempty"`
	// the total active capacity minus the system capacity
	TotalRemainingCapacity *float32 `json:"total_remaining_capacity,omitempty"`
	CapacityUsable *bool `json:"capacity_usable,omitempty"`
	Guid *string `json:"guid,omitempty"`
	// Parameter that controls everything related to database
	TabularSupport *string `json:"tabular_support,omitempty"`
	// Parameter that controls visibility of ipv6 fields for VIP Pools
	Ipv6Support *bool `json:"ipv6_support,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _Vms Vms

// NewVms instantiates a new Vms object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVms(name string) *Vms {
	this := Vms{}
	this.Name = name
	return &this
}

// NewVmsWithDefaults instantiates a new Vms object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVmsWithDefaults() *Vms {
	this := Vms{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Vms) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Vms) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *Vms) SetId(v int32) {
	o.Id = &v
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *Vms) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *Vms) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *Vms) SetIp(v string) {
	o.Ip = &v
}

// GetIp1 returns the Ip1 field value if set, zero value otherwise.
func (o *Vms) GetIp1() string {
	if o == nil || IsNil(o.Ip1) {
		var ret string
		return ret
	}
	return *o.Ip1
}

// GetIp1Ok returns a tuple with the Ip1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetIp1Ok() (*string, bool) {
	if o == nil || IsNil(o.Ip1) {
		return nil, false
	}
	return o.Ip1, true
}

// HasIp1 returns a boolean if a field has been set.
func (o *Vms) HasIp1() bool {
	if o != nil && !IsNil(o.Ip1) {
		return true
	}

	return false
}

// SetIp1 gets a reference to the given string and assigns it to the Ip1 field.
func (o *Vms) SetIp1(v string) {
	o.Ip1 = &v
}

// GetIp2 returns the Ip2 field value if set, zero value otherwise.
func (o *Vms) GetIp2() string {
	if o == nil || IsNil(o.Ip2) {
		var ret string
		return ret
	}
	return *o.Ip2
}

// GetIp2Ok returns a tuple with the Ip2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetIp2Ok() (*string, bool) {
	if o == nil || IsNil(o.Ip2) {
		return nil, false
	}
	return o.Ip2, true
}

// HasIp2 returns a boolean if a field has been set.
func (o *Vms) HasIp2() bool {
	if o != nil && !IsNil(o.Ip2) {
		return true
	}

	return false
}

// SetIp2 gets a reference to the given string and assigns it to the Ip2 field.
func (o *Vms) SetIp2(v string) {
	o.Ip2 = &v
}

// GetMgmtIp returns the MgmtIp field value if set, zero value otherwise.
func (o *Vms) GetMgmtIp() string {
	if o == nil || IsNil(o.MgmtIp) {
		var ret string
		return ret
	}
	return *o.MgmtIp
}

// GetMgmtIpOk returns a tuple with the MgmtIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetMgmtIpOk() (*string, bool) {
	if o == nil || IsNil(o.MgmtIp) {
		return nil, false
	}
	return o.MgmtIp, true
}

// HasMgmtIp returns a boolean if a field has been set.
func (o *Vms) HasMgmtIp() bool {
	if o != nil && !IsNil(o.MgmtIp) {
		return true
	}

	return false
}

// SetMgmtIp gets a reference to the given string and assigns it to the MgmtIp field.
func (o *Vms) SetMgmtIp(v string) {
	o.MgmtIp = &v
}

// GetMgmtVip returns the MgmtVip field value if set, zero value otherwise.
func (o *Vms) GetMgmtVip() string {
	if o == nil || IsNil(o.MgmtVip) {
		var ret string
		return ret
	}
	return *o.MgmtVip
}

// GetMgmtVipOk returns a tuple with the MgmtVip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetMgmtVipOk() (*string, bool) {
	if o == nil || IsNil(o.MgmtVip) {
		return nil, false
	}
	return o.MgmtVip, true
}

// HasMgmtVip returns a boolean if a field has been set.
func (o *Vms) HasMgmtVip() bool {
	if o != nil && !IsNil(o.MgmtVip) {
		return true
	}

	return false
}

// SetMgmtVip gets a reference to the given string and assigns it to the MgmtVip field.
func (o *Vms) SetMgmtVip(v string) {
	o.MgmtVip = &v
}

// GetMgmtVipIpv6 returns the MgmtVipIpv6 field value if set, zero value otherwise.
func (o *Vms) GetMgmtVipIpv6() string {
	if o == nil || IsNil(o.MgmtVipIpv6) {
		var ret string
		return ret
	}
	return *o.MgmtVipIpv6
}

// GetMgmtVipIpv6Ok returns a tuple with the MgmtVipIpv6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetMgmtVipIpv6Ok() (*string, bool) {
	if o == nil || IsNil(o.MgmtVipIpv6) {
		return nil, false
	}
	return o.MgmtVipIpv6, true
}

// HasMgmtVipIpv6 returns a boolean if a field has been set.
func (o *Vms) HasMgmtVipIpv6() bool {
	if o != nil && !IsNil(o.MgmtVipIpv6) {
		return true
	}

	return false
}

// SetMgmtVipIpv6 gets a reference to the given string and assigns it to the MgmtVipIpv6 field.
func (o *Vms) SetMgmtVipIpv6(v string) {
	o.MgmtVipIpv6 = &v
}

// GetMgmtCnode returns the MgmtCnode field value if set, zero value otherwise.
func (o *Vms) GetMgmtCnode() string {
	if o == nil || IsNil(o.MgmtCnode) {
		var ret string
		return ret
	}
	return *o.MgmtCnode
}

// GetMgmtCnodeOk returns a tuple with the MgmtCnode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetMgmtCnodeOk() (*string, bool) {
	if o == nil || IsNil(o.MgmtCnode) {
		return nil, false
	}
	return o.MgmtCnode, true
}

// HasMgmtCnode returns a boolean if a field has been set.
func (o *Vms) HasMgmtCnode() bool {
	if o != nil && !IsNil(o.MgmtCnode) {
		return true
	}

	return false
}

// SetMgmtCnode gets a reference to the given string and assigns it to the MgmtCnode field.
func (o *Vms) SetMgmtCnode(v string) {
	o.MgmtCnode = &v
}

// GetMgmtInnerVip returns the MgmtInnerVip field value if set, zero value otherwise.
func (o *Vms) GetMgmtInnerVip() string {
	if o == nil || IsNil(o.MgmtInnerVip) {
		var ret string
		return ret
	}
	return *o.MgmtInnerVip
}

// GetMgmtInnerVipOk returns a tuple with the MgmtInnerVip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetMgmtInnerVipOk() (*string, bool) {
	if o == nil || IsNil(o.MgmtInnerVip) {
		return nil, false
	}
	return o.MgmtInnerVip, true
}

// HasMgmtInnerVip returns a boolean if a field has been set.
func (o *Vms) HasMgmtInnerVip() bool {
	if o != nil && !IsNil(o.MgmtInnerVip) {
		return true
	}

	return false
}

// SetMgmtInnerVip gets a reference to the given string and assigns it to the MgmtInnerVip field.
func (o *Vms) SetMgmtInnerVip(v string) {
	o.MgmtInnerVip = &v
}

// GetMgmtInnerVipCnode returns the MgmtInnerVipCnode field value if set, zero value otherwise.
func (o *Vms) GetMgmtInnerVipCnode() string {
	if o == nil || IsNil(o.MgmtInnerVipCnode) {
		var ret string
		return ret
	}
	return *o.MgmtInnerVipCnode
}

// GetMgmtInnerVipCnodeOk returns a tuple with the MgmtInnerVipCnode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetMgmtInnerVipCnodeOk() (*string, bool) {
	if o == nil || IsNil(o.MgmtInnerVipCnode) {
		return nil, false
	}
	return o.MgmtInnerVipCnode, true
}

// HasMgmtInnerVipCnode returns a boolean if a field has been set.
func (o *Vms) HasMgmtInnerVipCnode() bool {
	if o != nil && !IsNil(o.MgmtInnerVipCnode) {
		return true
	}

	return false
}

// SetMgmtInnerVipCnode gets a reference to the given string and assigns it to the MgmtInnerVipCnode field.
func (o *Vms) SetMgmtInnerVipCnode(v string) {
	o.MgmtInnerVipCnode = &v
}

// GetName returns the Name field value
func (o *Vms) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Vms) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Vms) SetName(v string) {
	o.Name = v
}

// GetBuild returns the Build field value if set, zero value otherwise.
func (o *Vms) GetBuild() string {
	if o == nil || IsNil(o.Build) {
		var ret string
		return ret
	}
	return *o.Build
}

// GetBuildOk returns a tuple with the Build field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetBuildOk() (*string, bool) {
	if o == nil || IsNil(o.Build) {
		return nil, false
	}
	return o.Build, true
}

// HasBuild returns a boolean if a field has been set.
func (o *Vms) HasBuild() bool {
	if o != nil && !IsNil(o.Build) {
		return true
	}

	return false
}

// SetBuild gets a reference to the given string and assigns it to the Build field.
func (o *Vms) SetBuild(v string) {
	o.Build = &v
}

// GetSwVersion returns the SwVersion field value if set, zero value otherwise.
func (o *Vms) GetSwVersion() string {
	if o == nil || IsNil(o.SwVersion) {
		var ret string
		return ret
	}
	return *o.SwVersion
}

// GetSwVersionOk returns a tuple with the SwVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetSwVersionOk() (*string, bool) {
	if o == nil || IsNil(o.SwVersion) {
		return nil, false
	}
	return o.SwVersion, true
}

// HasSwVersion returns a boolean if a field has been set.
func (o *Vms) HasSwVersion() bool {
	if o != nil && !IsNil(o.SwVersion) {
		return true
	}

	return false
}

// SetSwVersion gets a reference to the given string and assigns it to the SwVersion field.
func (o *Vms) SetSwVersion(v string) {
	o.SwVersion = &v
}

// GetSslCertificate returns the SslCertificate field value if set, zero value otherwise.
func (o *Vms) GetSslCertificate() string {
	if o == nil || IsNil(o.SslCertificate) {
		var ret string
		return ret
	}
	return *o.SslCertificate
}

// GetSslCertificateOk returns a tuple with the SslCertificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetSslCertificateOk() (*string, bool) {
	if o == nil || IsNil(o.SslCertificate) {
		return nil, false
	}
	return o.SslCertificate, true
}

// HasSslCertificate returns a boolean if a field has been set.
func (o *Vms) HasSslCertificate() bool {
	if o != nil && !IsNil(o.SslCertificate) {
		return true
	}

	return false
}

// SetSslCertificate gets a reference to the given string and assigns it to the SslCertificate field.
func (o *Vms) SetSslCertificate(v string) {
	o.SslCertificate = &v
}

// GetSslKeyfile returns the SslKeyfile field value if set, zero value otherwise.
func (o *Vms) GetSslKeyfile() string {
	if o == nil || IsNil(o.SslKeyfile) {
		var ret string
		return ret
	}
	return *o.SslKeyfile
}

// GetSslKeyfileOk returns a tuple with the SslKeyfile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetSslKeyfileOk() (*string, bool) {
	if o == nil || IsNil(o.SslKeyfile) {
		return nil, false
	}
	return o.SslKeyfile, true
}

// HasSslKeyfile returns a boolean if a field has been set.
func (o *Vms) HasSslKeyfile() bool {
	if o != nil && !IsNil(o.SslKeyfile) {
		return true
	}

	return false
}

// SetSslKeyfile gets a reference to the given string and assigns it to the SslKeyfile field.
func (o *Vms) SetSslKeyfile(v string) {
	o.SslKeyfile = &v
}

// GetSslPort returns the SslPort field value if set, zero value otherwise.
func (o *Vms) GetSslPort() int32 {
	if o == nil || IsNil(o.SslPort) {
		var ret int32
		return ret
	}
	return *o.SslPort
}

// GetSslPortOk returns a tuple with the SslPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetSslPortOk() (*int32, bool) {
	if o == nil || IsNil(o.SslPort) {
		return nil, false
	}
	return o.SslPort, true
}

// HasSslPort returns a boolean if a field has been set.
func (o *Vms) HasSslPort() bool {
	if o != nil && !IsNil(o.SslPort) {
		return true
	}

	return false
}

// SetSslPort gets a reference to the given int32 and assigns it to the SslPort field.
func (o *Vms) SetSslPort(v int32) {
	o.SslPort = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Vms) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Vms) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Vms) SetTitle(v string) {
	o.Title = &v
}

// GetAutoLogoutTimeout returns the AutoLogoutTimeout field value if set, zero value otherwise.
func (o *Vms) GetAutoLogoutTimeout() int32 {
	if o == nil || IsNil(o.AutoLogoutTimeout) {
		var ret int32
		return ret
	}
	return *o.AutoLogoutTimeout
}

// GetAutoLogoutTimeoutOk returns a tuple with the AutoLogoutTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetAutoLogoutTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.AutoLogoutTimeout) {
		return nil, false
	}
	return o.AutoLogoutTimeout, true
}

// HasAutoLogoutTimeout returns a boolean if a field has been set.
func (o *Vms) HasAutoLogoutTimeout() bool {
	if o != nil && !IsNil(o.AutoLogoutTimeout) {
		return true
	}

	return false
}

// SetAutoLogoutTimeout gets a reference to the given int32 and assigns it to the AutoLogoutTimeout field.
func (o *Vms) SetAutoLogoutTimeout(v int32) {
	o.AutoLogoutTimeout = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *Vms) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *Vms) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *Vms) SetCreated(v time.Time) {
	o.Created = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *Vms) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *Vms) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *Vms) SetState(v string) {
	o.State = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *Vms) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *Vms) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *Vms) SetUrl(v string) {
	o.Url = &v
}

// GetDisableMgmtHa returns the DisableMgmtHa field value if set, zero value otherwise.
func (o *Vms) GetDisableMgmtHa() bool {
	if o == nil || IsNil(o.DisableMgmtHa) {
		var ret bool
		return ret
	}
	return *o.DisableMgmtHa
}

// GetDisableMgmtHaOk returns a tuple with the DisableMgmtHa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetDisableMgmtHaOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableMgmtHa) {
		return nil, false
	}
	return o.DisableMgmtHa, true
}

// HasDisableMgmtHa returns a boolean if a field has been set.
func (o *Vms) HasDisableMgmtHa() bool {
	if o != nil && !IsNil(o.DisableMgmtHa) {
		return true
	}

	return false
}

// SetDisableMgmtHa gets a reference to the given bool and assigns it to the DisableMgmtHa field.
func (o *Vms) SetDisableMgmtHa(v bool) {
	o.DisableMgmtHa = &v
}

// GetDisableVmsMetrics returns the DisableVmsMetrics field value if set, zero value otherwise.
func (o *Vms) GetDisableVmsMetrics() bool {
	if o == nil || IsNil(o.DisableVmsMetrics) {
		var ret bool
		return ret
	}
	return *o.DisableVmsMetrics
}

// GetDisableVmsMetricsOk returns a tuple with the DisableVmsMetrics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetDisableVmsMetricsOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableVmsMetrics) {
		return nil, false
	}
	return o.DisableVmsMetrics, true
}

// HasDisableVmsMetrics returns a boolean if a field has been set.
func (o *Vms) HasDisableVmsMetrics() bool {
	if o != nil && !IsNil(o.DisableVmsMetrics) {
		return true
	}

	return false
}

// SetDisableVmsMetrics gets a reference to the given bool and assigns it to the DisableVmsMetrics field.
func (o *Vms) SetDisableVmsMetrics(v bool) {
	o.DisableVmsMetrics = &v
}

// GetCapacityBase10 returns the CapacityBase10 field value if set, zero value otherwise.
func (o *Vms) GetCapacityBase10() bool {
	if o == nil || IsNil(o.CapacityBase10) {
		var ret bool
		return ret
	}
	return *o.CapacityBase10
}

// GetCapacityBase10Ok returns a tuple with the CapacityBase10 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetCapacityBase10Ok() (*bool, bool) {
	if o == nil || IsNil(o.CapacityBase10) {
		return nil, false
	}
	return o.CapacityBase10, true
}

// HasCapacityBase10 returns a boolean if a field has been set.
func (o *Vms) HasCapacityBase10() bool {
	if o != nil && !IsNil(o.CapacityBase10) {
		return true
	}

	return false
}

// SetCapacityBase10 gets a reference to the given bool and assigns it to the CapacityBase10 field.
func (o *Vms) SetCapacityBase10(v bool) {
	o.CapacityBase10 = &v
}

// GetPerformanceBase10 returns the PerformanceBase10 field value if set, zero value otherwise.
func (o *Vms) GetPerformanceBase10() bool {
	if o == nil || IsNil(o.PerformanceBase10) {
		var ret bool
		return ret
	}
	return *o.PerformanceBase10
}

// GetPerformanceBase10Ok returns a tuple with the PerformanceBase10 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetPerformanceBase10Ok() (*bool, bool) {
	if o == nil || IsNil(o.PerformanceBase10) {
		return nil, false
	}
	return o.PerformanceBase10, true
}

// HasPerformanceBase10 returns a boolean if a field has been set.
func (o *Vms) HasPerformanceBase10() bool {
	if o != nil && !IsNil(o.PerformanceBase10) {
		return true
	}

	return false
}

// SetPerformanceBase10 gets a reference to the given bool and assigns it to the PerformanceBase10 field.
func (o *Vms) SetPerformanceBase10(v bool) {
	o.PerformanceBase10 = &v
}

// GetMinTlsVersion returns the MinTlsVersion field value if set, zero value otherwise.
func (o *Vms) GetMinTlsVersion() string {
	if o == nil || IsNil(o.MinTlsVersion) {
		var ret string
		return ret
	}
	return *o.MinTlsVersion
}

// GetMinTlsVersionOk returns a tuple with the MinTlsVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetMinTlsVersionOk() (*string, bool) {
	if o == nil || IsNil(o.MinTlsVersion) {
		return nil, false
	}
	return o.MinTlsVersion, true
}

// HasMinTlsVersion returns a boolean if a field has been set.
func (o *Vms) HasMinTlsVersion() bool {
	if o != nil && !IsNil(o.MinTlsVersion) {
		return true
	}

	return false
}

// SetMinTlsVersion gets a reference to the given string and assigns it to the MinTlsVersion field.
func (o *Vms) SetMinTlsVersion(v string) {
	o.MinTlsVersion = &v
}

// GetDegradedReason returns the DegradedReason field value if set, zero value otherwise.
func (o *Vms) GetDegradedReason() string {
	if o == nil || IsNil(o.DegradedReason) {
		var ret string
		return ret
	}
	return *o.DegradedReason
}

// GetDegradedReasonOk returns a tuple with the DegradedReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetDegradedReasonOk() (*string, bool) {
	if o == nil || IsNil(o.DegradedReason) {
		return nil, false
	}
	return o.DegradedReason, true
}

// HasDegradedReason returns a boolean if a field has been set.
func (o *Vms) HasDegradedReason() bool {
	if o != nil && !IsNil(o.DegradedReason) {
		return true
	}

	return false
}

// SetDegradedReason gets a reference to the given string and assigns it to the DegradedReason field.
func (o *Vms) SetDegradedReason(v string) {
	o.DegradedReason = &v
}

// GetAccessTokenLifetime returns the AccessTokenLifetime field value if set, zero value otherwise.
func (o *Vms) GetAccessTokenLifetime() string {
	if o == nil || IsNil(o.AccessTokenLifetime) {
		var ret string
		return ret
	}
	return *o.AccessTokenLifetime
}

// GetAccessTokenLifetimeOk returns a tuple with the AccessTokenLifetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetAccessTokenLifetimeOk() (*string, bool) {
	if o == nil || IsNil(o.AccessTokenLifetime) {
		return nil, false
	}
	return o.AccessTokenLifetime, true
}

// HasAccessTokenLifetime returns a boolean if a field has been set.
func (o *Vms) HasAccessTokenLifetime() bool {
	if o != nil && !IsNil(o.AccessTokenLifetime) {
		return true
	}

	return false
}

// SetAccessTokenLifetime gets a reference to the given string and assigns it to the AccessTokenLifetime field.
func (o *Vms) SetAccessTokenLifetime(v string) {
	o.AccessTokenLifetime = &v
}

// GetRefreshTokenLifetime returns the RefreshTokenLifetime field value if set, zero value otherwise.
func (o *Vms) GetRefreshTokenLifetime() string {
	if o == nil || IsNil(o.RefreshTokenLifetime) {
		var ret string
		return ret
	}
	return *o.RefreshTokenLifetime
}

// GetRefreshTokenLifetimeOk returns a tuple with the RefreshTokenLifetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetRefreshTokenLifetimeOk() (*string, bool) {
	if o == nil || IsNil(o.RefreshTokenLifetime) {
		return nil, false
	}
	return o.RefreshTokenLifetime, true
}

// HasRefreshTokenLifetime returns a boolean if a field has been set.
func (o *Vms) HasRefreshTokenLifetime() bool {
	if o != nil && !IsNil(o.RefreshTokenLifetime) {
		return true
	}

	return false
}

// SetRefreshTokenLifetime gets a reference to the given string and assigns it to the RefreshTokenLifetime field.
func (o *Vms) SetRefreshTokenLifetime(v string) {
	o.RefreshTokenLifetime = &v
}

// GetLoginBanner returns the LoginBanner field value if set, zero value otherwise.
func (o *Vms) GetLoginBanner() string {
	if o == nil || IsNil(o.LoginBanner) {
		var ret string
		return ret
	}
	return *o.LoginBanner
}

// GetLoginBannerOk returns a tuple with the LoginBanner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetLoginBannerOk() (*string, bool) {
	if o == nil || IsNil(o.LoginBanner) {
		return nil, false
	}
	return o.LoginBanner, true
}

// HasLoginBanner returns a boolean if a field has been set.
func (o *Vms) HasLoginBanner() bool {
	if o != nil && !IsNil(o.LoginBanner) {
		return true
	}

	return false
}

// SetLoginBanner gets a reference to the given string and assigns it to the LoginBanner field.
func (o *Vms) SetLoginBanner(v string) {
	o.LoginBanner = &v
}

// GetTotalUsageCapacityPercentage returns the TotalUsageCapacityPercentage field value if set, zero value otherwise.
func (o *Vms) GetTotalUsageCapacityPercentage() float32 {
	if o == nil || IsNil(o.TotalUsageCapacityPercentage) {
		var ret float32
		return ret
	}
	return *o.TotalUsageCapacityPercentage
}

// GetTotalUsageCapacityPercentageOk returns a tuple with the TotalUsageCapacityPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetTotalUsageCapacityPercentageOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalUsageCapacityPercentage) {
		return nil, false
	}
	return o.TotalUsageCapacityPercentage, true
}

// HasTotalUsageCapacityPercentage returns a boolean if a field has been set.
func (o *Vms) HasTotalUsageCapacityPercentage() bool {
	if o != nil && !IsNil(o.TotalUsageCapacityPercentage) {
		return true
	}

	return false
}

// SetTotalUsageCapacityPercentage gets a reference to the given float32 and assigns it to the TotalUsageCapacityPercentage field.
func (o *Vms) SetTotalUsageCapacityPercentage(v float32) {
	o.TotalUsageCapacityPercentage = &v
}

// GetTotalActiveCapacity returns the TotalActiveCapacity field value if set, zero value otherwise.
func (o *Vms) GetTotalActiveCapacity() float32 {
	if o == nil || IsNil(o.TotalActiveCapacity) {
		var ret float32
		return ret
	}
	return *o.TotalActiveCapacity
}

// GetTotalActiveCapacityOk returns a tuple with the TotalActiveCapacity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetTotalActiveCapacityOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalActiveCapacity) {
		return nil, false
	}
	return o.TotalActiveCapacity, true
}

// HasTotalActiveCapacity returns a boolean if a field has been set.
func (o *Vms) HasTotalActiveCapacity() bool {
	if o != nil && !IsNil(o.TotalActiveCapacity) {
		return true
	}

	return false
}

// SetTotalActiveCapacity gets a reference to the given float32 and assigns it to the TotalActiveCapacity field.
func (o *Vms) SetTotalActiveCapacity(v float32) {
	o.TotalActiveCapacity = &v
}

// GetTotalRemainingCapacity returns the TotalRemainingCapacity field value if set, zero value otherwise.
func (o *Vms) GetTotalRemainingCapacity() float32 {
	if o == nil || IsNil(o.TotalRemainingCapacity) {
		var ret float32
		return ret
	}
	return *o.TotalRemainingCapacity
}

// GetTotalRemainingCapacityOk returns a tuple with the TotalRemainingCapacity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetTotalRemainingCapacityOk() (*float32, bool) {
	if o == nil || IsNil(o.TotalRemainingCapacity) {
		return nil, false
	}
	return o.TotalRemainingCapacity, true
}

// HasTotalRemainingCapacity returns a boolean if a field has been set.
func (o *Vms) HasTotalRemainingCapacity() bool {
	if o != nil && !IsNil(o.TotalRemainingCapacity) {
		return true
	}

	return false
}

// SetTotalRemainingCapacity gets a reference to the given float32 and assigns it to the TotalRemainingCapacity field.
func (o *Vms) SetTotalRemainingCapacity(v float32) {
	o.TotalRemainingCapacity = &v
}

// GetCapacityUsable returns the CapacityUsable field value if set, zero value otherwise.
func (o *Vms) GetCapacityUsable() bool {
	if o == nil || IsNil(o.CapacityUsable) {
		var ret bool
		return ret
	}
	return *o.CapacityUsable
}

// GetCapacityUsableOk returns a tuple with the CapacityUsable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetCapacityUsableOk() (*bool, bool) {
	if o == nil || IsNil(o.CapacityUsable) {
		return nil, false
	}
	return o.CapacityUsable, true
}

// HasCapacityUsable returns a boolean if a field has been set.
func (o *Vms) HasCapacityUsable() bool {
	if o != nil && !IsNil(o.CapacityUsable) {
		return true
	}

	return false
}

// SetCapacityUsable gets a reference to the given bool and assigns it to the CapacityUsable field.
func (o *Vms) SetCapacityUsable(v bool) {
	o.CapacityUsable = &v
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *Vms) GetGuid() string {
	if o == nil || IsNil(o.Guid) {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetGuidOk() (*string, bool) {
	if o == nil || IsNil(o.Guid) {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *Vms) HasGuid() bool {
	if o != nil && !IsNil(o.Guid) {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *Vms) SetGuid(v string) {
	o.Guid = &v
}

// GetTabularSupport returns the TabularSupport field value if set, zero value otherwise.
func (o *Vms) GetTabularSupport() string {
	if o == nil || IsNil(o.TabularSupport) {
		var ret string
		return ret
	}
	return *o.TabularSupport
}

// GetTabularSupportOk returns a tuple with the TabularSupport field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetTabularSupportOk() (*string, bool) {
	if o == nil || IsNil(o.TabularSupport) {
		return nil, false
	}
	return o.TabularSupport, true
}

// HasTabularSupport returns a boolean if a field has been set.
func (o *Vms) HasTabularSupport() bool {
	if o != nil && !IsNil(o.TabularSupport) {
		return true
	}

	return false
}

// SetTabularSupport gets a reference to the given string and assigns it to the TabularSupport field.
func (o *Vms) SetTabularSupport(v string) {
	o.TabularSupport = &v
}

// GetIpv6Support returns the Ipv6Support field value if set, zero value otherwise.
func (o *Vms) GetIpv6Support() bool {
	if o == nil || IsNil(o.Ipv6Support) {
		var ret bool
		return ret
	}
	return *o.Ipv6Support
}

// GetIpv6SupportOk returns a tuple with the Ipv6Support field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Vms) GetIpv6SupportOk() (*bool, bool) {
	if o == nil || IsNil(o.Ipv6Support) {
		return nil, false
	}
	return o.Ipv6Support, true
}

// HasIpv6Support returns a boolean if a field has been set.
func (o *Vms) HasIpv6Support() bool {
	if o != nil && !IsNil(o.Ipv6Support) {
		return true
	}

	return false
}

// SetIpv6Support gets a reference to the given bool and assigns it to the Ipv6Support field.
func (o *Vms) SetIpv6Support(v bool) {
	o.Ipv6Support = &v
}

func (o Vms) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Vms) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Ip1) {
		toSerialize["ip1"] = o.Ip1
	}
	if !IsNil(o.Ip2) {
		toSerialize["ip2"] = o.Ip2
	}
	if !IsNil(o.MgmtIp) {
		toSerialize["mgmt_ip"] = o.MgmtIp
	}
	if !IsNil(o.MgmtVip) {
		toSerialize["mgmt_vip"] = o.MgmtVip
	}
	if !IsNil(o.MgmtVipIpv6) {
		toSerialize["mgmt_vip_ipv6"] = o.MgmtVipIpv6
	}
	if !IsNil(o.MgmtCnode) {
		toSerialize["mgmt_cnode"] = o.MgmtCnode
	}
	if !IsNil(o.MgmtInnerVip) {
		toSerialize["mgmt_inner_vip"] = o.MgmtInnerVip
	}
	if !IsNil(o.MgmtInnerVipCnode) {
		toSerialize["mgmt_inner_vip_cnode"] = o.MgmtInnerVipCnode
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Build) {
		toSerialize["build"] = o.Build
	}
	if !IsNil(o.SwVersion) {
		toSerialize["sw_version"] = o.SwVersion
	}
	if !IsNil(o.SslCertificate) {
		toSerialize["ssl_certificate"] = o.SslCertificate
	}
	if !IsNil(o.SslKeyfile) {
		toSerialize["ssl_keyfile"] = o.SslKeyfile
	}
	if !IsNil(o.SslPort) {
		toSerialize["ssl_port"] = o.SslPort
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.AutoLogoutTimeout) {
		toSerialize["auto_logout_timeout"] = o.AutoLogoutTimeout
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.DisableMgmtHa) {
		toSerialize["disable_mgmt_ha"] = o.DisableMgmtHa
	}
	if !IsNil(o.DisableVmsMetrics) {
		toSerialize["disable_vms_metrics"] = o.DisableVmsMetrics
	}
	if !IsNil(o.CapacityBase10) {
		toSerialize["capacity_base_10"] = o.CapacityBase10
	}
	if !IsNil(o.PerformanceBase10) {
		toSerialize["performance_base_10"] = o.PerformanceBase10
	}
	if !IsNil(o.MinTlsVersion) {
		toSerialize["min_tls_version"] = o.MinTlsVersion
	}
	if !IsNil(o.DegradedReason) {
		toSerialize["degraded_reason"] = o.DegradedReason
	}
	if !IsNil(o.AccessTokenLifetime) {
		toSerialize["access_token_lifetime"] = o.AccessTokenLifetime
	}
	if !IsNil(o.RefreshTokenLifetime) {
		toSerialize["refresh_token_lifetime"] = o.RefreshTokenLifetime
	}
	if !IsNil(o.LoginBanner) {
		toSerialize["login_banner"] = o.LoginBanner
	}
	if !IsNil(o.TotalUsageCapacityPercentage) {
		toSerialize["total_usage_capacity_percentage"] = o.TotalUsageCapacityPercentage
	}
	if !IsNil(o.TotalActiveCapacity) {
		toSerialize["total_active_capacity"] = o.TotalActiveCapacity
	}
	if !IsNil(o.TotalRemainingCapacity) {
		toSerialize["total_remaining_capacity"] = o.TotalRemainingCapacity
	}
	if !IsNil(o.CapacityUsable) {
		toSerialize["capacity_usable"] = o.CapacityUsable
	}
	if !IsNil(o.Guid) {
		toSerialize["guid"] = o.Guid
	}
	if !IsNil(o.TabularSupport) {
		toSerialize["tabular_support"] = o.TabularSupport
	}
	if !IsNil(o.Ipv6Support) {
		toSerialize["ipv6_support"] = o.Ipv6Support
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Vms) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVms := _Vms{}

	err = json.Unmarshal(data, &varVms)

	if err != nil {
		return err
	}

	*o = Vms(varVms)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "ip")
		delete(additionalProperties, "ip1")
		delete(additionalProperties, "ip2")
		delete(additionalProperties, "mgmt_ip")
		delete(additionalProperties, "mgmt_vip")
		delete(additionalProperties, "mgmt_vip_ipv6")
		delete(additionalProperties, "mgmt_cnode")
		delete(additionalProperties, "mgmt_inner_vip")
		delete(additionalProperties, "mgmt_inner_vip_cnode")
		delete(additionalProperties, "name")
		delete(additionalProperties, "build")
		delete(additionalProperties, "sw_version")
		delete(additionalProperties, "ssl_certificate")
		delete(additionalProperties, "ssl_keyfile")
		delete(additionalProperties, "ssl_port")
		delete(additionalProperties, "title")
		delete(additionalProperties, "auto_logout_timeout")
		delete(additionalProperties, "created")
		delete(additionalProperties, "state")
		delete(additionalProperties, "url")
		delete(additionalProperties, "disable_mgmt_ha")
		delete(additionalProperties, "disable_vms_metrics")
		delete(additionalProperties, "capacity_base_10")
		delete(additionalProperties, "performance_base_10")
		delete(additionalProperties, "min_tls_version")
		delete(additionalProperties, "degraded_reason")
		delete(additionalProperties, "access_token_lifetime")
		delete(additionalProperties, "refresh_token_lifetime")
		delete(additionalProperties, "login_banner")
		delete(additionalProperties, "total_usage_capacity_percentage")
		delete(additionalProperties, "total_active_capacity")
		delete(additionalProperties, "total_remaining_capacity")
		delete(additionalProperties, "capacity_usable")
		delete(additionalProperties, "guid")
		delete(additionalProperties, "tabular_support")
		delete(additionalProperties, "ipv6_support")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVms struct {
	value *Vms
	isSet bool
}

func (v NullableVms) Get() *Vms {
	return v.value
}

func (v *NullableVms) Set(val *Vms) {
	v.value = val
	v.isSet = true
}

func (v NullableVms) IsSet() bool {
	return v.isSet
}

func (v *NullableVms) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVms(val *Vms) *NullableVms {
	return &NullableVms{value: val, isSet: true}
}

func (v NullableVms) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVms) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


