/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ViewsPartialUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewsPartialUpdateRequest{}

// ViewsPartialUpdateRequest struct for ViewsPartialUpdateRequest
type ViewsPartialUpdateRequest struct {
	// View name
	Name *string `json:"name,omitempty"`
	// View path
	Path *string `json:"path,omitempty"`
	// Create a directory at the specified path
	CreateDir *bool `json:"create_dir,omitempty"`
	// For NFS-enabled views, a view alias for NFSv3 clients.
	Alias *string `json:"alias,omitempty"`
	// Not yet implemented
	Bucket *string `json:"bucket,omitempty"`
	S3ObjectOwnershipRule *string `json:"s3_object_ownership_rule,omitempty"`
	// Enabled client access protocols
	Protocols []string `json:"protocols,omitempty"`
	// SMB share name
	Share *string `json:"share,omitempty"`
	// View policy ID.
	PolicyId *int32 `json:"policy_id,omitempty"`
	// S3 Versioning
	S3Versioning *bool `json:"s3_versioning,omitempty"`
	// S3 Unverified Lookup
	S3UnverifiedLookup *bool `json:"s3_unverified_lookup,omitempty"`
	// Allow S3 anonymous access
	AllowAnonymousAccess *bool `json:"allow_anonymous_access,omitempty"`
	// Allow S3 anonymous access
	AllowS3AnonymousAccess *bool `json:"allow_s3_anonymous_access,omitempty"`
	// S3 Bucket owner
	BucketOwner *string `json:"bucket_owner,omitempty"`
	// Object Locking
	Locking *bool `json:"locking,omitempty"`
	// The retention mode for new object versions stored in this bucket. You can override this if you upload a new object version with an explicit retention mode and period.
	S3LocksRetentionMode *string `json:"s3_locks_retention_mode,omitempty"`
	// The amount of time in which the file/object is protected. This is mandatory if an S3 retention mode is set.
	DefaultRetentionPeriod *string `json:"default_retention_period,omitempty"`
	// Indicates whether the view should support simultaneous access to NFS3/NFS4/SMB protocols.
	NfsInteropFlags *string `json:"nfs_interop_flags,omitempty"`
	BucketCreators []string `json:"bucket_creators,omitempty"`
	BucketCreatorsGroups []string `json:"bucket_creators_groups,omitempty"`
	// Share-level ACL details
	ShareAcl map[string]interface{} `json:"share_acl,omitempty"`
	SelectForLiveMonitoring *bool `json:"select_for_live_monitoring,omitempty"`
	// QoS Policy ID
	QosPolicyId NullableInt32 `json:"qos_policy_id,omitempty"`
	// QoS Policy
	QosPolicy *string `json:"qos_policy,omitempty"`
	// Protocols for which ABE is enabled
	AbeProtocols []string `json:"abe_protocols,omitempty"`
	// The maximum depth of folders under the view on which the ABE feature is enabled
	AbeMaxDepth *int32 `json:"abe_max_depth,omitempty"`
	// supports seamless connection between peers
	IsSeamless *bool `json:"is_seamless,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ViewsPartialUpdateRequest ViewsPartialUpdateRequest

// NewViewsPartialUpdateRequest instantiates a new ViewsPartialUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewsPartialUpdateRequest() *ViewsPartialUpdateRequest {
	this := ViewsPartialUpdateRequest{}
	return &this
}

// NewViewsPartialUpdateRequestWithDefaults instantiates a new ViewsPartialUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewsPartialUpdateRequestWithDefaults() *ViewsPartialUpdateRequest {
	this := ViewsPartialUpdateRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ViewsPartialUpdateRequest) SetName(v string) {
	o.Name = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *ViewsPartialUpdateRequest) SetPath(v string) {
	o.Path = &v
}

// GetCreateDir returns the CreateDir field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetCreateDir() bool {
	if o == nil || IsNil(o.CreateDir) {
		var ret bool
		return ret
	}
	return *o.CreateDir
}

// GetCreateDirOk returns a tuple with the CreateDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetCreateDirOk() (*bool, bool) {
	if o == nil || IsNil(o.CreateDir) {
		return nil, false
	}
	return o.CreateDir, true
}

// HasCreateDir returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasCreateDir() bool {
	if o != nil && !IsNil(o.CreateDir) {
		return true
	}

	return false
}

// SetCreateDir gets a reference to the given bool and assigns it to the CreateDir field.
func (o *ViewsPartialUpdateRequest) SetCreateDir(v bool) {
	o.CreateDir = &v
}

// GetAlias returns the Alias field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetAlias() string {
	if o == nil || IsNil(o.Alias) {
		var ret string
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetAliasOk() (*string, bool) {
	if o == nil || IsNil(o.Alias) {
		return nil, false
	}
	return o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasAlias() bool {
	if o != nil && !IsNil(o.Alias) {
		return true
	}

	return false
}

// SetAlias gets a reference to the given string and assigns it to the Alias field.
func (o *ViewsPartialUpdateRequest) SetAlias(v string) {
	o.Alias = &v
}

// GetBucket returns the Bucket field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetBucket() string {
	if o == nil || IsNil(o.Bucket) {
		var ret string
		return ret
	}
	return *o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetBucketOk() (*string, bool) {
	if o == nil || IsNil(o.Bucket) {
		return nil, false
	}
	return o.Bucket, true
}

// HasBucket returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasBucket() bool {
	if o != nil && !IsNil(o.Bucket) {
		return true
	}

	return false
}

// SetBucket gets a reference to the given string and assigns it to the Bucket field.
func (o *ViewsPartialUpdateRequest) SetBucket(v string) {
	o.Bucket = &v
}

// GetS3ObjectOwnershipRule returns the S3ObjectOwnershipRule field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetS3ObjectOwnershipRule() string {
	if o == nil || IsNil(o.S3ObjectOwnershipRule) {
		var ret string
		return ret
	}
	return *o.S3ObjectOwnershipRule
}

// GetS3ObjectOwnershipRuleOk returns a tuple with the S3ObjectOwnershipRule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetS3ObjectOwnershipRuleOk() (*string, bool) {
	if o == nil || IsNil(o.S3ObjectOwnershipRule) {
		return nil, false
	}
	return o.S3ObjectOwnershipRule, true
}

// HasS3ObjectOwnershipRule returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasS3ObjectOwnershipRule() bool {
	if o != nil && !IsNil(o.S3ObjectOwnershipRule) {
		return true
	}

	return false
}

// SetS3ObjectOwnershipRule gets a reference to the given string and assigns it to the S3ObjectOwnershipRule field.
func (o *ViewsPartialUpdateRequest) SetS3ObjectOwnershipRule(v string) {
	o.S3ObjectOwnershipRule = &v
}

// GetProtocols returns the Protocols field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetProtocols() []string {
	if o == nil || IsNil(o.Protocols) {
		var ret []string
		return ret
	}
	return o.Protocols
}

// GetProtocolsOk returns a tuple with the Protocols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetProtocolsOk() ([]string, bool) {
	if o == nil || IsNil(o.Protocols) {
		return nil, false
	}
	return o.Protocols, true
}

// HasProtocols returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasProtocols() bool {
	if o != nil && !IsNil(o.Protocols) {
		return true
	}

	return false
}

// SetProtocols gets a reference to the given []string and assigns it to the Protocols field.
func (o *ViewsPartialUpdateRequest) SetProtocols(v []string) {
	o.Protocols = v
}

// GetShare returns the Share field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetShare() string {
	if o == nil || IsNil(o.Share) {
		var ret string
		return ret
	}
	return *o.Share
}

// GetShareOk returns a tuple with the Share field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetShareOk() (*string, bool) {
	if o == nil || IsNil(o.Share) {
		return nil, false
	}
	return o.Share, true
}

// HasShare returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasShare() bool {
	if o != nil && !IsNil(o.Share) {
		return true
	}

	return false
}

// SetShare gets a reference to the given string and assigns it to the Share field.
func (o *ViewsPartialUpdateRequest) SetShare(v string) {
	o.Share = &v
}

// GetPolicyId returns the PolicyId field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetPolicyId() int32 {
	if o == nil || IsNil(o.PolicyId) {
		var ret int32
		return ret
	}
	return *o.PolicyId
}

// GetPolicyIdOk returns a tuple with the PolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetPolicyIdOk() (*int32, bool) {
	if o == nil || IsNil(o.PolicyId) {
		return nil, false
	}
	return o.PolicyId, true
}

// HasPolicyId returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasPolicyId() bool {
	if o != nil && !IsNil(o.PolicyId) {
		return true
	}

	return false
}

// SetPolicyId gets a reference to the given int32 and assigns it to the PolicyId field.
func (o *ViewsPartialUpdateRequest) SetPolicyId(v int32) {
	o.PolicyId = &v
}

// GetS3Versioning returns the S3Versioning field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetS3Versioning() bool {
	if o == nil || IsNil(o.S3Versioning) {
		var ret bool
		return ret
	}
	return *o.S3Versioning
}

// GetS3VersioningOk returns a tuple with the S3Versioning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetS3VersioningOk() (*bool, bool) {
	if o == nil || IsNil(o.S3Versioning) {
		return nil, false
	}
	return o.S3Versioning, true
}

// HasS3Versioning returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasS3Versioning() bool {
	if o != nil && !IsNil(o.S3Versioning) {
		return true
	}

	return false
}

// SetS3Versioning gets a reference to the given bool and assigns it to the S3Versioning field.
func (o *ViewsPartialUpdateRequest) SetS3Versioning(v bool) {
	o.S3Versioning = &v
}

// GetS3UnverifiedLookup returns the S3UnverifiedLookup field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetS3UnverifiedLookup() bool {
	if o == nil || IsNil(o.S3UnverifiedLookup) {
		var ret bool
		return ret
	}
	return *o.S3UnverifiedLookup
}

// GetS3UnverifiedLookupOk returns a tuple with the S3UnverifiedLookup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetS3UnverifiedLookupOk() (*bool, bool) {
	if o == nil || IsNil(o.S3UnverifiedLookup) {
		return nil, false
	}
	return o.S3UnverifiedLookup, true
}

// HasS3UnverifiedLookup returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasS3UnverifiedLookup() bool {
	if o != nil && !IsNil(o.S3UnverifiedLookup) {
		return true
	}

	return false
}

// SetS3UnverifiedLookup gets a reference to the given bool and assigns it to the S3UnverifiedLookup field.
func (o *ViewsPartialUpdateRequest) SetS3UnverifiedLookup(v bool) {
	o.S3UnverifiedLookup = &v
}

// GetAllowAnonymousAccess returns the AllowAnonymousAccess field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetAllowAnonymousAccess() bool {
	if o == nil || IsNil(o.AllowAnonymousAccess) {
		var ret bool
		return ret
	}
	return *o.AllowAnonymousAccess
}

// GetAllowAnonymousAccessOk returns a tuple with the AllowAnonymousAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetAllowAnonymousAccessOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowAnonymousAccess) {
		return nil, false
	}
	return o.AllowAnonymousAccess, true
}

// HasAllowAnonymousAccess returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasAllowAnonymousAccess() bool {
	if o != nil && !IsNil(o.AllowAnonymousAccess) {
		return true
	}

	return false
}

// SetAllowAnonymousAccess gets a reference to the given bool and assigns it to the AllowAnonymousAccess field.
func (o *ViewsPartialUpdateRequest) SetAllowAnonymousAccess(v bool) {
	o.AllowAnonymousAccess = &v
}

// GetAllowS3AnonymousAccess returns the AllowS3AnonymousAccess field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetAllowS3AnonymousAccess() bool {
	if o == nil || IsNil(o.AllowS3AnonymousAccess) {
		var ret bool
		return ret
	}
	return *o.AllowS3AnonymousAccess
}

// GetAllowS3AnonymousAccessOk returns a tuple with the AllowS3AnonymousAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetAllowS3AnonymousAccessOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowS3AnonymousAccess) {
		return nil, false
	}
	return o.AllowS3AnonymousAccess, true
}

// HasAllowS3AnonymousAccess returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasAllowS3AnonymousAccess() bool {
	if o != nil && !IsNil(o.AllowS3AnonymousAccess) {
		return true
	}

	return false
}

// SetAllowS3AnonymousAccess gets a reference to the given bool and assigns it to the AllowS3AnonymousAccess field.
func (o *ViewsPartialUpdateRequest) SetAllowS3AnonymousAccess(v bool) {
	o.AllowS3AnonymousAccess = &v
}

// GetBucketOwner returns the BucketOwner field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetBucketOwner() string {
	if o == nil || IsNil(o.BucketOwner) {
		var ret string
		return ret
	}
	return *o.BucketOwner
}

// GetBucketOwnerOk returns a tuple with the BucketOwner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetBucketOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.BucketOwner) {
		return nil, false
	}
	return o.BucketOwner, true
}

// HasBucketOwner returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasBucketOwner() bool {
	if o != nil && !IsNil(o.BucketOwner) {
		return true
	}

	return false
}

// SetBucketOwner gets a reference to the given string and assigns it to the BucketOwner field.
func (o *ViewsPartialUpdateRequest) SetBucketOwner(v string) {
	o.BucketOwner = &v
}

// GetLocking returns the Locking field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetLocking() bool {
	if o == nil || IsNil(o.Locking) {
		var ret bool
		return ret
	}
	return *o.Locking
}

// GetLockingOk returns a tuple with the Locking field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetLockingOk() (*bool, bool) {
	if o == nil || IsNil(o.Locking) {
		return nil, false
	}
	return o.Locking, true
}

// HasLocking returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasLocking() bool {
	if o != nil && !IsNil(o.Locking) {
		return true
	}

	return false
}

// SetLocking gets a reference to the given bool and assigns it to the Locking field.
func (o *ViewsPartialUpdateRequest) SetLocking(v bool) {
	o.Locking = &v
}

// GetS3LocksRetentionMode returns the S3LocksRetentionMode field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetS3LocksRetentionMode() string {
	if o == nil || IsNil(o.S3LocksRetentionMode) {
		var ret string
		return ret
	}
	return *o.S3LocksRetentionMode
}

// GetS3LocksRetentionModeOk returns a tuple with the S3LocksRetentionMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetS3LocksRetentionModeOk() (*string, bool) {
	if o == nil || IsNil(o.S3LocksRetentionMode) {
		return nil, false
	}
	return o.S3LocksRetentionMode, true
}

// HasS3LocksRetentionMode returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasS3LocksRetentionMode() bool {
	if o != nil && !IsNil(o.S3LocksRetentionMode) {
		return true
	}

	return false
}

// SetS3LocksRetentionMode gets a reference to the given string and assigns it to the S3LocksRetentionMode field.
func (o *ViewsPartialUpdateRequest) SetS3LocksRetentionMode(v string) {
	o.S3LocksRetentionMode = &v
}

// GetDefaultRetentionPeriod returns the DefaultRetentionPeriod field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetDefaultRetentionPeriod() string {
	if o == nil || IsNil(o.DefaultRetentionPeriod) {
		var ret string
		return ret
	}
	return *o.DefaultRetentionPeriod
}

// GetDefaultRetentionPeriodOk returns a tuple with the DefaultRetentionPeriod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetDefaultRetentionPeriodOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultRetentionPeriod) {
		return nil, false
	}
	return o.DefaultRetentionPeriod, true
}

// HasDefaultRetentionPeriod returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasDefaultRetentionPeriod() bool {
	if o != nil && !IsNil(o.DefaultRetentionPeriod) {
		return true
	}

	return false
}

// SetDefaultRetentionPeriod gets a reference to the given string and assigns it to the DefaultRetentionPeriod field.
func (o *ViewsPartialUpdateRequest) SetDefaultRetentionPeriod(v string) {
	o.DefaultRetentionPeriod = &v
}

// GetNfsInteropFlags returns the NfsInteropFlags field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetNfsInteropFlags() string {
	if o == nil || IsNil(o.NfsInteropFlags) {
		var ret string
		return ret
	}
	return *o.NfsInteropFlags
}

// GetNfsInteropFlagsOk returns a tuple with the NfsInteropFlags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetNfsInteropFlagsOk() (*string, bool) {
	if o == nil || IsNil(o.NfsInteropFlags) {
		return nil, false
	}
	return o.NfsInteropFlags, true
}

// HasNfsInteropFlags returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasNfsInteropFlags() bool {
	if o != nil && !IsNil(o.NfsInteropFlags) {
		return true
	}

	return false
}

// SetNfsInteropFlags gets a reference to the given string and assigns it to the NfsInteropFlags field.
func (o *ViewsPartialUpdateRequest) SetNfsInteropFlags(v string) {
	o.NfsInteropFlags = &v
}

// GetBucketCreators returns the BucketCreators field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetBucketCreators() []string {
	if o == nil || IsNil(o.BucketCreators) {
		var ret []string
		return ret
	}
	return o.BucketCreators
}

// GetBucketCreatorsOk returns a tuple with the BucketCreators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetBucketCreatorsOk() ([]string, bool) {
	if o == nil || IsNil(o.BucketCreators) {
		return nil, false
	}
	return o.BucketCreators, true
}

// HasBucketCreators returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasBucketCreators() bool {
	if o != nil && !IsNil(o.BucketCreators) {
		return true
	}

	return false
}

// SetBucketCreators gets a reference to the given []string and assigns it to the BucketCreators field.
func (o *ViewsPartialUpdateRequest) SetBucketCreators(v []string) {
	o.BucketCreators = v
}

// GetBucketCreatorsGroups returns the BucketCreatorsGroups field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetBucketCreatorsGroups() []string {
	if o == nil || IsNil(o.BucketCreatorsGroups) {
		var ret []string
		return ret
	}
	return o.BucketCreatorsGroups
}

// GetBucketCreatorsGroupsOk returns a tuple with the BucketCreatorsGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetBucketCreatorsGroupsOk() ([]string, bool) {
	if o == nil || IsNil(o.BucketCreatorsGroups) {
		return nil, false
	}
	return o.BucketCreatorsGroups, true
}

// HasBucketCreatorsGroups returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasBucketCreatorsGroups() bool {
	if o != nil && !IsNil(o.BucketCreatorsGroups) {
		return true
	}

	return false
}

// SetBucketCreatorsGroups gets a reference to the given []string and assigns it to the BucketCreatorsGroups field.
func (o *ViewsPartialUpdateRequest) SetBucketCreatorsGroups(v []string) {
	o.BucketCreatorsGroups = v
}

// GetShareAcl returns the ShareAcl field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetShareAcl() map[string]interface{} {
	if o == nil || IsNil(o.ShareAcl) {
		var ret map[string]interface{}
		return ret
	}
	return o.ShareAcl
}

// GetShareAclOk returns a tuple with the ShareAcl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetShareAclOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ShareAcl) {
		return map[string]interface{}{}, false
	}
	return o.ShareAcl, true
}

// HasShareAcl returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasShareAcl() bool {
	if o != nil && !IsNil(o.ShareAcl) {
		return true
	}

	return false
}

// SetShareAcl gets a reference to the given map[string]interface{} and assigns it to the ShareAcl field.
func (o *ViewsPartialUpdateRequest) SetShareAcl(v map[string]interface{}) {
	o.ShareAcl = v
}

// GetSelectForLiveMonitoring returns the SelectForLiveMonitoring field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetSelectForLiveMonitoring() bool {
	if o == nil || IsNil(o.SelectForLiveMonitoring) {
		var ret bool
		return ret
	}
	return *o.SelectForLiveMonitoring
}

// GetSelectForLiveMonitoringOk returns a tuple with the SelectForLiveMonitoring field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetSelectForLiveMonitoringOk() (*bool, bool) {
	if o == nil || IsNil(o.SelectForLiveMonitoring) {
		return nil, false
	}
	return o.SelectForLiveMonitoring, true
}

// HasSelectForLiveMonitoring returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasSelectForLiveMonitoring() bool {
	if o != nil && !IsNil(o.SelectForLiveMonitoring) {
		return true
	}

	return false
}

// SetSelectForLiveMonitoring gets a reference to the given bool and assigns it to the SelectForLiveMonitoring field.
func (o *ViewsPartialUpdateRequest) SetSelectForLiveMonitoring(v bool) {
	o.SelectForLiveMonitoring = &v
}

// GetQosPolicyId returns the QosPolicyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ViewsPartialUpdateRequest) GetQosPolicyId() int32 {
	if o == nil || IsNil(o.QosPolicyId.Get()) {
		var ret int32
		return ret
	}
	return *o.QosPolicyId.Get()
}

// GetQosPolicyIdOk returns a tuple with the QosPolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ViewsPartialUpdateRequest) GetQosPolicyIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.QosPolicyId.Get(), o.QosPolicyId.IsSet()
}

// HasQosPolicyId returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasQosPolicyId() bool {
	if o != nil && o.QosPolicyId.IsSet() {
		return true
	}

	return false
}

// SetQosPolicyId gets a reference to the given NullableInt32 and assigns it to the QosPolicyId field.
func (o *ViewsPartialUpdateRequest) SetQosPolicyId(v int32) {
	o.QosPolicyId.Set(&v)
}
// SetQosPolicyIdNil sets the value for QosPolicyId to be an explicit nil
func (o *ViewsPartialUpdateRequest) SetQosPolicyIdNil() {
	o.QosPolicyId.Set(nil)
}

// UnsetQosPolicyId ensures that no value is present for QosPolicyId, not even an explicit nil
func (o *ViewsPartialUpdateRequest) UnsetQosPolicyId() {
	o.QosPolicyId.Unset()
}

// GetQosPolicy returns the QosPolicy field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetQosPolicy() string {
	if o == nil || IsNil(o.QosPolicy) {
		var ret string
		return ret
	}
	return *o.QosPolicy
}

// GetQosPolicyOk returns a tuple with the QosPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetQosPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.QosPolicy) {
		return nil, false
	}
	return o.QosPolicy, true
}

// HasQosPolicy returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasQosPolicy() bool {
	if o != nil && !IsNil(o.QosPolicy) {
		return true
	}

	return false
}

// SetQosPolicy gets a reference to the given string and assigns it to the QosPolicy field.
func (o *ViewsPartialUpdateRequest) SetQosPolicy(v string) {
	o.QosPolicy = &v
}

// GetAbeProtocols returns the AbeProtocols field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetAbeProtocols() []string {
	if o == nil || IsNil(o.AbeProtocols) {
		var ret []string
		return ret
	}
	return o.AbeProtocols
}

// GetAbeProtocolsOk returns a tuple with the AbeProtocols field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetAbeProtocolsOk() ([]string, bool) {
	if o == nil || IsNil(o.AbeProtocols) {
		return nil, false
	}
	return o.AbeProtocols, true
}

// HasAbeProtocols returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasAbeProtocols() bool {
	if o != nil && !IsNil(o.AbeProtocols) {
		return true
	}

	return false
}

// SetAbeProtocols gets a reference to the given []string and assigns it to the AbeProtocols field.
func (o *ViewsPartialUpdateRequest) SetAbeProtocols(v []string) {
	o.AbeProtocols = v
}

// GetAbeMaxDepth returns the AbeMaxDepth field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetAbeMaxDepth() int32 {
	if o == nil || IsNil(o.AbeMaxDepth) {
		var ret int32
		return ret
	}
	return *o.AbeMaxDepth
}

// GetAbeMaxDepthOk returns a tuple with the AbeMaxDepth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetAbeMaxDepthOk() (*int32, bool) {
	if o == nil || IsNil(o.AbeMaxDepth) {
		return nil, false
	}
	return o.AbeMaxDepth, true
}

// HasAbeMaxDepth returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasAbeMaxDepth() bool {
	if o != nil && !IsNil(o.AbeMaxDepth) {
		return true
	}

	return false
}

// SetAbeMaxDepth gets a reference to the given int32 and assigns it to the AbeMaxDepth field.
func (o *ViewsPartialUpdateRequest) SetAbeMaxDepth(v int32) {
	o.AbeMaxDepth = &v
}

// GetIsSeamless returns the IsSeamless field value if set, zero value otherwise.
func (o *ViewsPartialUpdateRequest) GetIsSeamless() bool {
	if o == nil || IsNil(o.IsSeamless) {
		var ret bool
		return ret
	}
	return *o.IsSeamless
}

// GetIsSeamlessOk returns a tuple with the IsSeamless field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewsPartialUpdateRequest) GetIsSeamlessOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSeamless) {
		return nil, false
	}
	return o.IsSeamless, true
}

// HasIsSeamless returns a boolean if a field has been set.
func (o *ViewsPartialUpdateRequest) HasIsSeamless() bool {
	if o != nil && !IsNil(o.IsSeamless) {
		return true
	}

	return false
}

// SetIsSeamless gets a reference to the given bool and assigns it to the IsSeamless field.
func (o *ViewsPartialUpdateRequest) SetIsSeamless(v bool) {
	o.IsSeamless = &v
}

func (o ViewsPartialUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewsPartialUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.CreateDir) {
		toSerialize["create_dir"] = o.CreateDir
	}
	if !IsNil(o.Alias) {
		toSerialize["alias"] = o.Alias
	}
	if !IsNil(o.Bucket) {
		toSerialize["bucket"] = o.Bucket
	}
	if !IsNil(o.S3ObjectOwnershipRule) {
		toSerialize["s3_object_ownership_rule"] = o.S3ObjectOwnershipRule
	}
	if !IsNil(o.Protocols) {
		toSerialize["protocols"] = o.Protocols
	}
	if !IsNil(o.Share) {
		toSerialize["share"] = o.Share
	}
	if !IsNil(o.PolicyId) {
		toSerialize["policy_id"] = o.PolicyId
	}
	if !IsNil(o.S3Versioning) {
		toSerialize["s3_versioning"] = o.S3Versioning
	}
	if !IsNil(o.S3UnverifiedLookup) {
		toSerialize["s3_unverified_lookup"] = o.S3UnverifiedLookup
	}
	if !IsNil(o.AllowAnonymousAccess) {
		toSerialize["allow_anonymous_access"] = o.AllowAnonymousAccess
	}
	if !IsNil(o.AllowS3AnonymousAccess) {
		toSerialize["allow_s3_anonymous_access"] = o.AllowS3AnonymousAccess
	}
	if !IsNil(o.BucketOwner) {
		toSerialize["bucket_owner"] = o.BucketOwner
	}
	if !IsNil(o.Locking) {
		toSerialize["locking"] = o.Locking
	}
	if !IsNil(o.S3LocksRetentionMode) {
		toSerialize["s3_locks_retention_mode"] = o.S3LocksRetentionMode
	}
	if !IsNil(o.DefaultRetentionPeriod) {
		toSerialize["default_retention_period"] = o.DefaultRetentionPeriod
	}
	if !IsNil(o.NfsInteropFlags) {
		toSerialize["nfs_interop_flags"] = o.NfsInteropFlags
	}
	if !IsNil(o.BucketCreators) {
		toSerialize["bucket_creators"] = o.BucketCreators
	}
	if !IsNil(o.BucketCreatorsGroups) {
		toSerialize["bucket_creators_groups"] = o.BucketCreatorsGroups
	}
	if !IsNil(o.ShareAcl) {
		toSerialize["share_acl"] = o.ShareAcl
	}
	if !IsNil(o.SelectForLiveMonitoring) {
		toSerialize["select_for_live_monitoring"] = o.SelectForLiveMonitoring
	}
	if o.QosPolicyId.IsSet() {
		toSerialize["qos_policy_id"] = o.QosPolicyId.Get()
	}
	if !IsNil(o.QosPolicy) {
		toSerialize["qos_policy"] = o.QosPolicy
	}
	if !IsNil(o.AbeProtocols) {
		toSerialize["abe_protocols"] = o.AbeProtocols
	}
	if !IsNil(o.AbeMaxDepth) {
		toSerialize["abe_max_depth"] = o.AbeMaxDepth
	}
	if !IsNil(o.IsSeamless) {
		toSerialize["is_seamless"] = o.IsSeamless
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ViewsPartialUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	varViewsPartialUpdateRequest := _ViewsPartialUpdateRequest{}

	err = json.Unmarshal(data, &varViewsPartialUpdateRequest)

	if err != nil {
		return err
	}

	*o = ViewsPartialUpdateRequest(varViewsPartialUpdateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "path")
		delete(additionalProperties, "create_dir")
		delete(additionalProperties, "alias")
		delete(additionalProperties, "bucket")
		delete(additionalProperties, "s3_object_ownership_rule")
		delete(additionalProperties, "protocols")
		delete(additionalProperties, "share")
		delete(additionalProperties, "policy_id")
		delete(additionalProperties, "s3_versioning")
		delete(additionalProperties, "s3_unverified_lookup")
		delete(additionalProperties, "allow_anonymous_access")
		delete(additionalProperties, "allow_s3_anonymous_access")
		delete(additionalProperties, "bucket_owner")
		delete(additionalProperties, "locking")
		delete(additionalProperties, "s3_locks_retention_mode")
		delete(additionalProperties, "default_retention_period")
		delete(additionalProperties, "nfs_interop_flags")
		delete(additionalProperties, "bucket_creators")
		delete(additionalProperties, "bucket_creators_groups")
		delete(additionalProperties, "share_acl")
		delete(additionalProperties, "select_for_live_monitoring")
		delete(additionalProperties, "qos_policy_id")
		delete(additionalProperties, "qos_policy")
		delete(additionalProperties, "abe_protocols")
		delete(additionalProperties, "abe_max_depth")
		delete(additionalProperties, "is_seamless")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableViewsPartialUpdateRequest struct {
	value *ViewsPartialUpdateRequest
	isSet bool
}

func (v NullableViewsPartialUpdateRequest) Get() *ViewsPartialUpdateRequest {
	return v.value
}

func (v *NullableViewsPartialUpdateRequest) Set(val *ViewsPartialUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableViewsPartialUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableViewsPartialUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewsPartialUpdateRequest(val *ViewsPartialUpdateRequest) *NullableViewsPartialUpdateRequest {
	return &NullableViewsPartialUpdateRequest{value: val, isSet: true}
}

func (v NullableViewsPartialUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewsPartialUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


