/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EventDefinition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EventDefinition{}

// EventDefinition struct for EventDefinition
type EventDefinition struct {
	Id *int32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	ObjectType *string `json:"object_type,omitempty"`
	EventType *string `json:"event_type,omitempty"`
	// The severity of the alarm
	Severity *string `json:"severity,omitempty"`
	// For 'Object Modified' alarms: a list of values | For 'Threshold/Rate' alarms: a list of 2 members. The first is an operator like gt/ge/lte and the second is a number 
	TriggerOn *string `json:"trigger_on,omitempty"`
	// For 'Object Modified' alarms: a list of values
	TriggerOff *string `json:"trigger_off,omitempty"`
	// Did a user modify this event definition
	UserModified *bool `json:"user_modified,omitempty"`
	// List of emails you want to notify in case this event occurs
	EmailRecipients []string `json:"email_recipients,omitempty"`
	// The URL that the webhook will go to
	WebhookUrl *string `json:"webhook_url,omitempty"`
	// Use $event as event message parameter
	WebhookData *string `json:"webhook_data,omitempty"`
	// The method that the webhook will use
	WebhookMethod *string `json:"webhook_method,omitempty"`
	Property *string `json:"property,omitempty"`
	WebhookParams *string `json:"webhook_params,omitempty"`
	AlarmDefinitions *string `json:"alarm_definitions,omitempty"`
	ActionDefinitions *string `json:"action_definitions,omitempty"`
	EventMessage *string `json:"event_message,omitempty"`
	DisableActions *bool `json:"disable_actions,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	Internal *bool `json:"internal,omitempty"`
	// When this is enabled, only alarms will lead to email and webhook actions
	AlarmOnly *bool `json:"alarm_only,omitempty"`
	// Minimal time to wait between two consecutive events
	Cooldown *int32 `json:"cooldown,omitempty"`
	// Raise an alarm after a specific number of recurrences
	RaiseAtCount *int32 `json:"raise_at_count,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EventDefinition EventDefinition

// NewEventDefinition instantiates a new EventDefinition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventDefinition() *EventDefinition {
	this := EventDefinition{}
	return &this
}

// NewEventDefinitionWithDefaults instantiates a new EventDefinition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventDefinitionWithDefaults() *EventDefinition {
	this := EventDefinition{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EventDefinition) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EventDefinition) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *EventDefinition) SetId(v int32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EventDefinition) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EventDefinition) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EventDefinition) SetName(v string) {
	o.Name = &v
}

// GetObjectType returns the ObjectType field value if set, zero value otherwise.
func (o *EventDefinition) GetObjectType() string {
	if o == nil || IsNil(o.ObjectType) {
		var ret string
		return ret
	}
	return *o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetObjectTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectType) {
		return nil, false
	}
	return o.ObjectType, true
}

// HasObjectType returns a boolean if a field has been set.
func (o *EventDefinition) HasObjectType() bool {
	if o != nil && !IsNil(o.ObjectType) {
		return true
	}

	return false
}

// SetObjectType gets a reference to the given string and assigns it to the ObjectType field.
func (o *EventDefinition) SetObjectType(v string) {
	o.ObjectType = &v
}

// GetEventType returns the EventType field value if set, zero value otherwise.
func (o *EventDefinition) GetEventType() string {
	if o == nil || IsNil(o.EventType) {
		var ret string
		return ret
	}
	return *o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetEventTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EventType) {
		return nil, false
	}
	return o.EventType, true
}

// HasEventType returns a boolean if a field has been set.
func (o *EventDefinition) HasEventType() bool {
	if o != nil && !IsNil(o.EventType) {
		return true
	}

	return false
}

// SetEventType gets a reference to the given string and assigns it to the EventType field.
func (o *EventDefinition) SetEventType(v string) {
	o.EventType = &v
}

// GetSeverity returns the Severity field value if set, zero value otherwise.
func (o *EventDefinition) GetSeverity() string {
	if o == nil || IsNil(o.Severity) {
		var ret string
		return ret
	}
	return *o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetSeverityOk() (*string, bool) {
	if o == nil || IsNil(o.Severity) {
		return nil, false
	}
	return o.Severity, true
}

// HasSeverity returns a boolean if a field has been set.
func (o *EventDefinition) HasSeverity() bool {
	if o != nil && !IsNil(o.Severity) {
		return true
	}

	return false
}

// SetSeverity gets a reference to the given string and assigns it to the Severity field.
func (o *EventDefinition) SetSeverity(v string) {
	o.Severity = &v
}

// GetTriggerOn returns the TriggerOn field value if set, zero value otherwise.
func (o *EventDefinition) GetTriggerOn() string {
	if o == nil || IsNil(o.TriggerOn) {
		var ret string
		return ret
	}
	return *o.TriggerOn
}

// GetTriggerOnOk returns a tuple with the TriggerOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetTriggerOnOk() (*string, bool) {
	if o == nil || IsNil(o.TriggerOn) {
		return nil, false
	}
	return o.TriggerOn, true
}

// HasTriggerOn returns a boolean if a field has been set.
func (o *EventDefinition) HasTriggerOn() bool {
	if o != nil && !IsNil(o.TriggerOn) {
		return true
	}

	return false
}

// SetTriggerOn gets a reference to the given string and assigns it to the TriggerOn field.
func (o *EventDefinition) SetTriggerOn(v string) {
	o.TriggerOn = &v
}

// GetTriggerOff returns the TriggerOff field value if set, zero value otherwise.
func (o *EventDefinition) GetTriggerOff() string {
	if o == nil || IsNil(o.TriggerOff) {
		var ret string
		return ret
	}
	return *o.TriggerOff
}

// GetTriggerOffOk returns a tuple with the TriggerOff field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetTriggerOffOk() (*string, bool) {
	if o == nil || IsNil(o.TriggerOff) {
		return nil, false
	}
	return o.TriggerOff, true
}

// HasTriggerOff returns a boolean if a field has been set.
func (o *EventDefinition) HasTriggerOff() bool {
	if o != nil && !IsNil(o.TriggerOff) {
		return true
	}

	return false
}

// SetTriggerOff gets a reference to the given string and assigns it to the TriggerOff field.
func (o *EventDefinition) SetTriggerOff(v string) {
	o.TriggerOff = &v
}

// GetUserModified returns the UserModified field value if set, zero value otherwise.
func (o *EventDefinition) GetUserModified() bool {
	if o == nil || IsNil(o.UserModified) {
		var ret bool
		return ret
	}
	return *o.UserModified
}

// GetUserModifiedOk returns a tuple with the UserModified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetUserModifiedOk() (*bool, bool) {
	if o == nil || IsNil(o.UserModified) {
		return nil, false
	}
	return o.UserModified, true
}

// HasUserModified returns a boolean if a field has been set.
func (o *EventDefinition) HasUserModified() bool {
	if o != nil && !IsNil(o.UserModified) {
		return true
	}

	return false
}

// SetUserModified gets a reference to the given bool and assigns it to the UserModified field.
func (o *EventDefinition) SetUserModified(v bool) {
	o.UserModified = &v
}

// GetEmailRecipients returns the EmailRecipients field value if set, zero value otherwise.
func (o *EventDefinition) GetEmailRecipients() []string {
	if o == nil || IsNil(o.EmailRecipients) {
		var ret []string
		return ret
	}
	return o.EmailRecipients
}

// GetEmailRecipientsOk returns a tuple with the EmailRecipients field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetEmailRecipientsOk() ([]string, bool) {
	if o == nil || IsNil(o.EmailRecipients) {
		return nil, false
	}
	return o.EmailRecipients, true
}

// HasEmailRecipients returns a boolean if a field has been set.
func (o *EventDefinition) HasEmailRecipients() bool {
	if o != nil && !IsNil(o.EmailRecipients) {
		return true
	}

	return false
}

// SetEmailRecipients gets a reference to the given []string and assigns it to the EmailRecipients field.
func (o *EventDefinition) SetEmailRecipients(v []string) {
	o.EmailRecipients = v
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise.
func (o *EventDefinition) GetWebhookUrl() string {
	if o == nil || IsNil(o.WebhookUrl) {
		var ret string
		return ret
	}
	return *o.WebhookUrl
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetWebhookUrlOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookUrl) {
		return nil, false
	}
	return o.WebhookUrl, true
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *EventDefinition) HasWebhookUrl() bool {
	if o != nil && !IsNil(o.WebhookUrl) {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given string and assigns it to the WebhookUrl field.
func (o *EventDefinition) SetWebhookUrl(v string) {
	o.WebhookUrl = &v
}

// GetWebhookData returns the WebhookData field value if set, zero value otherwise.
func (o *EventDefinition) GetWebhookData() string {
	if o == nil || IsNil(o.WebhookData) {
		var ret string
		return ret
	}
	return *o.WebhookData
}

// GetWebhookDataOk returns a tuple with the WebhookData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetWebhookDataOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookData) {
		return nil, false
	}
	return o.WebhookData, true
}

// HasWebhookData returns a boolean if a field has been set.
func (o *EventDefinition) HasWebhookData() bool {
	if o != nil && !IsNil(o.WebhookData) {
		return true
	}

	return false
}

// SetWebhookData gets a reference to the given string and assigns it to the WebhookData field.
func (o *EventDefinition) SetWebhookData(v string) {
	o.WebhookData = &v
}

// GetWebhookMethod returns the WebhookMethod field value if set, zero value otherwise.
func (o *EventDefinition) GetWebhookMethod() string {
	if o == nil || IsNil(o.WebhookMethod) {
		var ret string
		return ret
	}
	return *o.WebhookMethod
}

// GetWebhookMethodOk returns a tuple with the WebhookMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetWebhookMethodOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookMethod) {
		return nil, false
	}
	return o.WebhookMethod, true
}

// HasWebhookMethod returns a boolean if a field has been set.
func (o *EventDefinition) HasWebhookMethod() bool {
	if o != nil && !IsNil(o.WebhookMethod) {
		return true
	}

	return false
}

// SetWebhookMethod gets a reference to the given string and assigns it to the WebhookMethod field.
func (o *EventDefinition) SetWebhookMethod(v string) {
	o.WebhookMethod = &v
}

// GetProperty returns the Property field value if set, zero value otherwise.
func (o *EventDefinition) GetProperty() string {
	if o == nil || IsNil(o.Property) {
		var ret string
		return ret
	}
	return *o.Property
}

// GetPropertyOk returns a tuple with the Property field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetPropertyOk() (*string, bool) {
	if o == nil || IsNil(o.Property) {
		return nil, false
	}
	return o.Property, true
}

// HasProperty returns a boolean if a field has been set.
func (o *EventDefinition) HasProperty() bool {
	if o != nil && !IsNil(o.Property) {
		return true
	}

	return false
}

// SetProperty gets a reference to the given string and assigns it to the Property field.
func (o *EventDefinition) SetProperty(v string) {
	o.Property = &v
}

// GetWebhookParams returns the WebhookParams field value if set, zero value otherwise.
func (o *EventDefinition) GetWebhookParams() string {
	if o == nil || IsNil(o.WebhookParams) {
		var ret string
		return ret
	}
	return *o.WebhookParams
}

// GetWebhookParamsOk returns a tuple with the WebhookParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetWebhookParamsOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookParams) {
		return nil, false
	}
	return o.WebhookParams, true
}

// HasWebhookParams returns a boolean if a field has been set.
func (o *EventDefinition) HasWebhookParams() bool {
	if o != nil && !IsNil(o.WebhookParams) {
		return true
	}

	return false
}

// SetWebhookParams gets a reference to the given string and assigns it to the WebhookParams field.
func (o *EventDefinition) SetWebhookParams(v string) {
	o.WebhookParams = &v
}

// GetAlarmDefinitions returns the AlarmDefinitions field value if set, zero value otherwise.
func (o *EventDefinition) GetAlarmDefinitions() string {
	if o == nil || IsNil(o.AlarmDefinitions) {
		var ret string
		return ret
	}
	return *o.AlarmDefinitions
}

// GetAlarmDefinitionsOk returns a tuple with the AlarmDefinitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetAlarmDefinitionsOk() (*string, bool) {
	if o == nil || IsNil(o.AlarmDefinitions) {
		return nil, false
	}
	return o.AlarmDefinitions, true
}

// HasAlarmDefinitions returns a boolean if a field has been set.
func (o *EventDefinition) HasAlarmDefinitions() bool {
	if o != nil && !IsNil(o.AlarmDefinitions) {
		return true
	}

	return false
}

// SetAlarmDefinitions gets a reference to the given string and assigns it to the AlarmDefinitions field.
func (o *EventDefinition) SetAlarmDefinitions(v string) {
	o.AlarmDefinitions = &v
}

// GetActionDefinitions returns the ActionDefinitions field value if set, zero value otherwise.
func (o *EventDefinition) GetActionDefinitions() string {
	if o == nil || IsNil(o.ActionDefinitions) {
		var ret string
		return ret
	}
	return *o.ActionDefinitions
}

// GetActionDefinitionsOk returns a tuple with the ActionDefinitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetActionDefinitionsOk() (*string, bool) {
	if o == nil || IsNil(o.ActionDefinitions) {
		return nil, false
	}
	return o.ActionDefinitions, true
}

// HasActionDefinitions returns a boolean if a field has been set.
func (o *EventDefinition) HasActionDefinitions() bool {
	if o != nil && !IsNil(o.ActionDefinitions) {
		return true
	}

	return false
}

// SetActionDefinitions gets a reference to the given string and assigns it to the ActionDefinitions field.
func (o *EventDefinition) SetActionDefinitions(v string) {
	o.ActionDefinitions = &v
}

// GetEventMessage returns the EventMessage field value if set, zero value otherwise.
func (o *EventDefinition) GetEventMessage() string {
	if o == nil || IsNil(o.EventMessage) {
		var ret string
		return ret
	}
	return *o.EventMessage
}

// GetEventMessageOk returns a tuple with the EventMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetEventMessageOk() (*string, bool) {
	if o == nil || IsNil(o.EventMessage) {
		return nil, false
	}
	return o.EventMessage, true
}

// HasEventMessage returns a boolean if a field has been set.
func (o *EventDefinition) HasEventMessage() bool {
	if o != nil && !IsNil(o.EventMessage) {
		return true
	}

	return false
}

// SetEventMessage gets a reference to the given string and assigns it to the EventMessage field.
func (o *EventDefinition) SetEventMessage(v string) {
	o.EventMessage = &v
}

// GetDisableActions returns the DisableActions field value if set, zero value otherwise.
func (o *EventDefinition) GetDisableActions() bool {
	if o == nil || IsNil(o.DisableActions) {
		var ret bool
		return ret
	}
	return *o.DisableActions
}

// GetDisableActionsOk returns a tuple with the DisableActions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetDisableActionsOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableActions) {
		return nil, false
	}
	return o.DisableActions, true
}

// HasDisableActions returns a boolean if a field has been set.
func (o *EventDefinition) HasDisableActions() bool {
	if o != nil && !IsNil(o.DisableActions) {
		return true
	}

	return false
}

// SetDisableActions gets a reference to the given bool and assigns it to the DisableActions field.
func (o *EventDefinition) SetDisableActions(v bool) {
	o.DisableActions = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *EventDefinition) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *EventDefinition) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *EventDefinition) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetInternal returns the Internal field value if set, zero value otherwise.
func (o *EventDefinition) GetInternal() bool {
	if o == nil || IsNil(o.Internal) {
		var ret bool
		return ret
	}
	return *o.Internal
}

// GetInternalOk returns a tuple with the Internal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetInternalOk() (*bool, bool) {
	if o == nil || IsNil(o.Internal) {
		return nil, false
	}
	return o.Internal, true
}

// HasInternal returns a boolean if a field has been set.
func (o *EventDefinition) HasInternal() bool {
	if o != nil && !IsNil(o.Internal) {
		return true
	}

	return false
}

// SetInternal gets a reference to the given bool and assigns it to the Internal field.
func (o *EventDefinition) SetInternal(v bool) {
	o.Internal = &v
}

// GetAlarmOnly returns the AlarmOnly field value if set, zero value otherwise.
func (o *EventDefinition) GetAlarmOnly() bool {
	if o == nil || IsNil(o.AlarmOnly) {
		var ret bool
		return ret
	}
	return *o.AlarmOnly
}

// GetAlarmOnlyOk returns a tuple with the AlarmOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetAlarmOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.AlarmOnly) {
		return nil, false
	}
	return o.AlarmOnly, true
}

// HasAlarmOnly returns a boolean if a field has been set.
func (o *EventDefinition) HasAlarmOnly() bool {
	if o != nil && !IsNil(o.AlarmOnly) {
		return true
	}

	return false
}

// SetAlarmOnly gets a reference to the given bool and assigns it to the AlarmOnly field.
func (o *EventDefinition) SetAlarmOnly(v bool) {
	o.AlarmOnly = &v
}

// GetCooldown returns the Cooldown field value if set, zero value otherwise.
func (o *EventDefinition) GetCooldown() int32 {
	if o == nil || IsNil(o.Cooldown) {
		var ret int32
		return ret
	}
	return *o.Cooldown
}

// GetCooldownOk returns a tuple with the Cooldown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetCooldownOk() (*int32, bool) {
	if o == nil || IsNil(o.Cooldown) {
		return nil, false
	}
	return o.Cooldown, true
}

// HasCooldown returns a boolean if a field has been set.
func (o *EventDefinition) HasCooldown() bool {
	if o != nil && !IsNil(o.Cooldown) {
		return true
	}

	return false
}

// SetCooldown gets a reference to the given int32 and assigns it to the Cooldown field.
func (o *EventDefinition) SetCooldown(v int32) {
	o.Cooldown = &v
}

// GetRaiseAtCount returns the RaiseAtCount field value if set, zero value otherwise.
func (o *EventDefinition) GetRaiseAtCount() int32 {
	if o == nil || IsNil(o.RaiseAtCount) {
		var ret int32
		return ret
	}
	return *o.RaiseAtCount
}

// GetRaiseAtCountOk returns a tuple with the RaiseAtCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetRaiseAtCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RaiseAtCount) {
		return nil, false
	}
	return o.RaiseAtCount, true
}

// HasRaiseAtCount returns a boolean if a field has been set.
func (o *EventDefinition) HasRaiseAtCount() bool {
	if o != nil && !IsNil(o.RaiseAtCount) {
		return true
	}

	return false
}

// SetRaiseAtCount gets a reference to the given int32 and assigns it to the RaiseAtCount field.
func (o *EventDefinition) SetRaiseAtCount(v int32) {
	o.RaiseAtCount = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *EventDefinition) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EventDefinition) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *EventDefinition) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *EventDefinition) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o EventDefinition) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EventDefinition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.ObjectType) {
		toSerialize["object_type"] = o.ObjectType
	}
	if !IsNil(o.EventType) {
		toSerialize["event_type"] = o.EventType
	}
	if !IsNil(o.Severity) {
		toSerialize["severity"] = o.Severity
	}
	if !IsNil(o.TriggerOn) {
		toSerialize["trigger_on"] = o.TriggerOn
	}
	if !IsNil(o.TriggerOff) {
		toSerialize["trigger_off"] = o.TriggerOff
	}
	if !IsNil(o.UserModified) {
		toSerialize["user_modified"] = o.UserModified
	}
	if !IsNil(o.EmailRecipients) {
		toSerialize["email_recipients"] = o.EmailRecipients
	}
	if !IsNil(o.WebhookUrl) {
		toSerialize["webhook_url"] = o.WebhookUrl
	}
	if !IsNil(o.WebhookData) {
		toSerialize["webhook_data"] = o.WebhookData
	}
	if !IsNil(o.WebhookMethod) {
		toSerialize["webhook_method"] = o.WebhookMethod
	}
	if !IsNil(o.Property) {
		toSerialize["property"] = o.Property
	}
	if !IsNil(o.WebhookParams) {
		toSerialize["webhook_params"] = o.WebhookParams
	}
	if !IsNil(o.AlarmDefinitions) {
		toSerialize["alarm_definitions"] = o.AlarmDefinitions
	}
	if !IsNil(o.ActionDefinitions) {
		toSerialize["action_definitions"] = o.ActionDefinitions
	}
	if !IsNil(o.EventMessage) {
		toSerialize["event_message"] = o.EventMessage
	}
	if !IsNil(o.DisableActions) {
		toSerialize["disable_actions"] = o.DisableActions
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Internal) {
		toSerialize["internal"] = o.Internal
	}
	if !IsNil(o.AlarmOnly) {
		toSerialize["alarm_only"] = o.AlarmOnly
	}
	if !IsNil(o.Cooldown) {
		toSerialize["cooldown"] = o.Cooldown
	}
	if !IsNil(o.RaiseAtCount) {
		toSerialize["raise_at_count"] = o.RaiseAtCount
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EventDefinition) UnmarshalJSON(data []byte) (err error) {
	varEventDefinition := _EventDefinition{}

	err = json.Unmarshal(data, &varEventDefinition)

	if err != nil {
		return err
	}

	*o = EventDefinition(varEventDefinition)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "object_type")
		delete(additionalProperties, "event_type")
		delete(additionalProperties, "severity")
		delete(additionalProperties, "trigger_on")
		delete(additionalProperties, "trigger_off")
		delete(additionalProperties, "user_modified")
		delete(additionalProperties, "email_recipients")
		delete(additionalProperties, "webhook_url")
		delete(additionalProperties, "webhook_data")
		delete(additionalProperties, "webhook_method")
		delete(additionalProperties, "property")
		delete(additionalProperties, "webhook_params")
		delete(additionalProperties, "alarm_definitions")
		delete(additionalProperties, "action_definitions")
		delete(additionalProperties, "event_message")
		delete(additionalProperties, "disable_actions")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "internal")
		delete(additionalProperties, "alarm_only")
		delete(additionalProperties, "cooldown")
		delete(additionalProperties, "raise_at_count")
		delete(additionalProperties, "metadata")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEventDefinition struct {
	value *EventDefinition
	isSet bool
}

func (v NullableEventDefinition) Get() *EventDefinition {
	return v.value
}

func (v *NullableEventDefinition) Set(val *EventDefinition) {
	v.value = val
	v.isSet = true
}

func (v NullableEventDefinition) IsSet() bool {
	return v.isSet
}

func (v *NullableEventDefinition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventDefinition(val *EventDefinition) *NullableEventDefinition {
	return &NullableEventDefinition{value: val, isSet: true}
}

func (v NullableEventDefinition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventDefinition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


