/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the TabularDatabaseHierarchy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TabularDatabaseHierarchy{}

// TabularDatabaseHierarchy struct for TabularDatabaseHierarchy
type TabularDatabaseHierarchy struct {
	// Name of the Database
	DatabaseName string `json:"database_name"`
	// Name of the object
	Name string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _TabularDatabaseHierarchy TabularDatabaseHierarchy

// NewTabularDatabaseHierarchy instantiates a new TabularDatabaseHierarchy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTabularDatabaseHierarchy(databaseName string, name string) *TabularDatabaseHierarchy {
	this := TabularDatabaseHierarchy{}
	this.DatabaseName = databaseName
	this.Name = name
	return &this
}

// NewTabularDatabaseHierarchyWithDefaults instantiates a new TabularDatabaseHierarchy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTabularDatabaseHierarchyWithDefaults() *TabularDatabaseHierarchy {
	this := TabularDatabaseHierarchy{}
	return &this
}

// GetDatabaseName returns the DatabaseName field value
func (o *TabularDatabaseHierarchy) GetDatabaseName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DatabaseName
}

// GetDatabaseNameOk returns a tuple with the DatabaseName field value
// and a boolean to check if the value has been set.
func (o *TabularDatabaseHierarchy) GetDatabaseNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DatabaseName, true
}

// SetDatabaseName sets field value
func (o *TabularDatabaseHierarchy) SetDatabaseName(v string) {
	o.DatabaseName = v
}

// GetName returns the Name field value
func (o *TabularDatabaseHierarchy) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TabularDatabaseHierarchy) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TabularDatabaseHierarchy) SetName(v string) {
	o.Name = v
}

func (o TabularDatabaseHierarchy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TabularDatabaseHierarchy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["database_name"] = o.DatabaseName
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *TabularDatabaseHierarchy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"database_name",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTabularDatabaseHierarchy := _TabularDatabaseHierarchy{}

	err = json.Unmarshal(data, &varTabularDatabaseHierarchy)

	if err != nil {
		return err
	}

	*o = TabularDatabaseHierarchy(varTabularDatabaseHierarchy)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "database_name")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableTabularDatabaseHierarchy struct {
	value *TabularDatabaseHierarchy
	isSet bool
}

func (v NullableTabularDatabaseHierarchy) Get() *TabularDatabaseHierarchy {
	return v.value
}

func (v *NullableTabularDatabaseHierarchy) Set(val *TabularDatabaseHierarchy) {
	v.value = val
	v.isSet = true
}

func (v NullableTabularDatabaseHierarchy) IsSet() bool {
	return v.isSet
}

func (v *NullableTabularDatabaseHierarchy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTabularDatabaseHierarchy(val *TabularDatabaseHierarchy) *NullableTabularDatabaseHierarchy {
	return &NullableTabularDatabaseHierarchy{value: val, isSet: true}
}

func (v NullableTabularDatabaseHierarchy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTabularDatabaseHierarchy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


