/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GlobalSnapStreamOwnerTenant type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GlobalSnapStreamOwnerTenant{}

// GlobalSnapStreamOwnerTenant struct for GlobalSnapStreamOwnerTenant
type GlobalSnapStreamOwnerTenant struct {
	// Owner tenant name
	Name *string `json:"name,omitempty"`
	// Owner tenant guid
	Guid *string `json:"guid,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GlobalSnapStreamOwnerTenant GlobalSnapStreamOwnerTenant

// NewGlobalSnapStreamOwnerTenant instantiates a new GlobalSnapStreamOwnerTenant object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGlobalSnapStreamOwnerTenant() *GlobalSnapStreamOwnerTenant {
	this := GlobalSnapStreamOwnerTenant{}
	return &this
}

// NewGlobalSnapStreamOwnerTenantWithDefaults instantiates a new GlobalSnapStreamOwnerTenant object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGlobalSnapStreamOwnerTenantWithDefaults() *GlobalSnapStreamOwnerTenant {
	this := GlobalSnapStreamOwnerTenant{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GlobalSnapStreamOwnerTenant) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GlobalSnapStreamOwnerTenant) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GlobalSnapStreamOwnerTenant) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GlobalSnapStreamOwnerTenant) SetName(v string) {
	o.Name = &v
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *GlobalSnapStreamOwnerTenant) GetGuid() string {
	if o == nil || IsNil(o.Guid) {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GlobalSnapStreamOwnerTenant) GetGuidOk() (*string, bool) {
	if o == nil || IsNil(o.Guid) {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *GlobalSnapStreamOwnerTenant) HasGuid() bool {
	if o != nil && !IsNil(o.Guid) {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *GlobalSnapStreamOwnerTenant) SetGuid(v string) {
	o.Guid = &v
}

func (o GlobalSnapStreamOwnerTenant) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GlobalSnapStreamOwnerTenant) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Guid) {
		toSerialize["guid"] = o.Guid
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GlobalSnapStreamOwnerTenant) UnmarshalJSON(data []byte) (err error) {
	varGlobalSnapStreamOwnerTenant := _GlobalSnapStreamOwnerTenant{}

	err = json.Unmarshal(data, &varGlobalSnapStreamOwnerTenant)

	if err != nil {
		return err
	}

	*o = GlobalSnapStreamOwnerTenant(varGlobalSnapStreamOwnerTenant)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "guid")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGlobalSnapStreamOwnerTenant struct {
	value *GlobalSnapStreamOwnerTenant
	isSet bool
}

func (v NullableGlobalSnapStreamOwnerTenant) Get() *GlobalSnapStreamOwnerTenant {
	return v.value
}

func (v *NullableGlobalSnapStreamOwnerTenant) Set(val *GlobalSnapStreamOwnerTenant) {
	v.value = val
	v.isSet = true
}

func (v NullableGlobalSnapStreamOwnerTenant) IsSet() bool {
	return v.isSet
}

func (v *NullableGlobalSnapStreamOwnerTenant) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGlobalSnapStreamOwnerTenant(val *GlobalSnapStreamOwnerTenant) *NullableGlobalSnapStreamOwnerTenant {
	return &NullableGlobalSnapStreamOwnerTenant{value: val, isSet: true}
}

func (v NullableGlobalSnapStreamOwnerTenant) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGlobalSnapStreamOwnerTenant) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


