/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ViewPolicyProtocolsAudit type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewPolicyProtocolsAudit{}

// ViewPolicyProtocolsAudit Map of protocols audit configurations
type ViewPolicyProtocolsAudit struct {
	LogFullPath *bool `json:"log_full_path,omitempty"`
	LogUsername *bool `json:"log_username,omitempty"`
	CreateDeleteFilesDirsObjects *bool `json:"create_delete_files_dirs_objects,omitempty"`
	ModifyDataMd *bool `json:"modify_data_md,omitempty"`
	ReadData *bool `json:"read_data,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ViewPolicyProtocolsAudit ViewPolicyProtocolsAudit

// NewViewPolicyProtocolsAudit instantiates a new ViewPolicyProtocolsAudit object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewPolicyProtocolsAudit() *ViewPolicyProtocolsAudit {
	this := ViewPolicyProtocolsAudit{}
	return &this
}

// NewViewPolicyProtocolsAuditWithDefaults instantiates a new ViewPolicyProtocolsAudit object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewPolicyProtocolsAuditWithDefaults() *ViewPolicyProtocolsAudit {
	this := ViewPolicyProtocolsAudit{}
	return &this
}

// GetLogFullPath returns the LogFullPath field value if set, zero value otherwise.
func (o *ViewPolicyProtocolsAudit) GetLogFullPath() bool {
	if o == nil || IsNil(o.LogFullPath) {
		var ret bool
		return ret
	}
	return *o.LogFullPath
}

// GetLogFullPathOk returns a tuple with the LogFullPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewPolicyProtocolsAudit) GetLogFullPathOk() (*bool, bool) {
	if o == nil || IsNil(o.LogFullPath) {
		return nil, false
	}
	return o.LogFullPath, true
}

// HasLogFullPath returns a boolean if a field has been set.
func (o *ViewPolicyProtocolsAudit) HasLogFullPath() bool {
	if o != nil && !IsNil(o.LogFullPath) {
		return true
	}

	return false
}

// SetLogFullPath gets a reference to the given bool and assigns it to the LogFullPath field.
func (o *ViewPolicyProtocolsAudit) SetLogFullPath(v bool) {
	o.LogFullPath = &v
}

// GetLogUsername returns the LogUsername field value if set, zero value otherwise.
func (o *ViewPolicyProtocolsAudit) GetLogUsername() bool {
	if o == nil || IsNil(o.LogUsername) {
		var ret bool
		return ret
	}
	return *o.LogUsername
}

// GetLogUsernameOk returns a tuple with the LogUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewPolicyProtocolsAudit) GetLogUsernameOk() (*bool, bool) {
	if o == nil || IsNil(o.LogUsername) {
		return nil, false
	}
	return o.LogUsername, true
}

// HasLogUsername returns a boolean if a field has been set.
func (o *ViewPolicyProtocolsAudit) HasLogUsername() bool {
	if o != nil && !IsNil(o.LogUsername) {
		return true
	}

	return false
}

// SetLogUsername gets a reference to the given bool and assigns it to the LogUsername field.
func (o *ViewPolicyProtocolsAudit) SetLogUsername(v bool) {
	o.LogUsername = &v
}

// GetCreateDeleteFilesDirsObjects returns the CreateDeleteFilesDirsObjects field value if set, zero value otherwise.
func (o *ViewPolicyProtocolsAudit) GetCreateDeleteFilesDirsObjects() bool {
	if o == nil || IsNil(o.CreateDeleteFilesDirsObjects) {
		var ret bool
		return ret
	}
	return *o.CreateDeleteFilesDirsObjects
}

// GetCreateDeleteFilesDirsObjectsOk returns a tuple with the CreateDeleteFilesDirsObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewPolicyProtocolsAudit) GetCreateDeleteFilesDirsObjectsOk() (*bool, bool) {
	if o == nil || IsNil(o.CreateDeleteFilesDirsObjects) {
		return nil, false
	}
	return o.CreateDeleteFilesDirsObjects, true
}

// HasCreateDeleteFilesDirsObjects returns a boolean if a field has been set.
func (o *ViewPolicyProtocolsAudit) HasCreateDeleteFilesDirsObjects() bool {
	if o != nil && !IsNil(o.CreateDeleteFilesDirsObjects) {
		return true
	}

	return false
}

// SetCreateDeleteFilesDirsObjects gets a reference to the given bool and assigns it to the CreateDeleteFilesDirsObjects field.
func (o *ViewPolicyProtocolsAudit) SetCreateDeleteFilesDirsObjects(v bool) {
	o.CreateDeleteFilesDirsObjects = &v
}

// GetModifyDataMd returns the ModifyDataMd field value if set, zero value otherwise.
func (o *ViewPolicyProtocolsAudit) GetModifyDataMd() bool {
	if o == nil || IsNil(o.ModifyDataMd) {
		var ret bool
		return ret
	}
	return *o.ModifyDataMd
}

// GetModifyDataMdOk returns a tuple with the ModifyDataMd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewPolicyProtocolsAudit) GetModifyDataMdOk() (*bool, bool) {
	if o == nil || IsNil(o.ModifyDataMd) {
		return nil, false
	}
	return o.ModifyDataMd, true
}

// HasModifyDataMd returns a boolean if a field has been set.
func (o *ViewPolicyProtocolsAudit) HasModifyDataMd() bool {
	if o != nil && !IsNil(o.ModifyDataMd) {
		return true
	}

	return false
}

// SetModifyDataMd gets a reference to the given bool and assigns it to the ModifyDataMd field.
func (o *ViewPolicyProtocolsAudit) SetModifyDataMd(v bool) {
	o.ModifyDataMd = &v
}

// GetReadData returns the ReadData field value if set, zero value otherwise.
func (o *ViewPolicyProtocolsAudit) GetReadData() bool {
	if o == nil || IsNil(o.ReadData) {
		var ret bool
		return ret
	}
	return *o.ReadData
}

// GetReadDataOk returns a tuple with the ReadData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewPolicyProtocolsAudit) GetReadDataOk() (*bool, bool) {
	if o == nil || IsNil(o.ReadData) {
		return nil, false
	}
	return o.ReadData, true
}

// HasReadData returns a boolean if a field has been set.
func (o *ViewPolicyProtocolsAudit) HasReadData() bool {
	if o != nil && !IsNil(o.ReadData) {
		return true
	}

	return false
}

// SetReadData gets a reference to the given bool and assigns it to the ReadData field.
func (o *ViewPolicyProtocolsAudit) SetReadData(v bool) {
	o.ReadData = &v
}

func (o ViewPolicyProtocolsAudit) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewPolicyProtocolsAudit) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LogFullPath) {
		toSerialize["log_full_path"] = o.LogFullPath
	}
	if !IsNil(o.LogUsername) {
		toSerialize["log_username"] = o.LogUsername
	}
	if !IsNil(o.CreateDeleteFilesDirsObjects) {
		toSerialize["create_delete_files_dirs_objects"] = o.CreateDeleteFilesDirsObjects
	}
	if !IsNil(o.ModifyDataMd) {
		toSerialize["modify_data_md"] = o.ModifyDataMd
	}
	if !IsNil(o.ReadData) {
		toSerialize["read_data"] = o.ReadData
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ViewPolicyProtocolsAudit) UnmarshalJSON(data []byte) (err error) {
	varViewPolicyProtocolsAudit := _ViewPolicyProtocolsAudit{}

	err = json.Unmarshal(data, &varViewPolicyProtocolsAudit)

	if err != nil {
		return err
	}

	*o = ViewPolicyProtocolsAudit(varViewPolicyProtocolsAudit)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "log_full_path")
		delete(additionalProperties, "log_username")
		delete(additionalProperties, "create_delete_files_dirs_objects")
		delete(additionalProperties, "modify_data_md")
		delete(additionalProperties, "read_data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableViewPolicyProtocolsAudit struct {
	value *ViewPolicyProtocolsAudit
	isSet bool
}

func (v NullableViewPolicyProtocolsAudit) Get() *ViewPolicyProtocolsAudit {
	return v.value
}

func (v *NullableViewPolicyProtocolsAudit) Set(val *ViewPolicyProtocolsAudit) {
	v.value = val
	v.isSet = true
}

func (v NullableViewPolicyProtocolsAudit) IsSet() bool {
	return v.isSet
}

func (v *NullableViewPolicyProtocolsAudit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewPolicyProtocolsAudit(val *ViewPolicyProtocolsAudit) *NullableViewPolicyProtocolsAudit {
	return &NullableViewPolicyProtocolsAudit{value: val, isSet: true}
}

func (v NullableViewPolicyProtocolsAudit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewPolicyProtocolsAudit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


