/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ReplicationpoliciesCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReplicationpoliciesCreateRequest{}

// ReplicationpoliciesCreateRequest struct for ReplicationpoliciesCreateRequest
type ReplicationpoliciesCreateRequest struct {
	// 
	Name string `json:"name"`
	// schedule frequency, in datetime format
	ScheduleFrequency *time.Time `json:"schedule_frequency,omitempty"`
	// Schedule the first restore point after the initial sync
	ScheduleStartTime *time.Time `json:"schedule_start_time,omitempty"`
	// replication target id
	ReplicationTargetId int32 `json:"replication_target_id"`
	// bandwith limitation rules
	BandwidthLimitationRules *string `json:"bandwidth_limitation_rules,omitempty"`
	// low / normal / high
	Priority *string `json:"priority,omitempty"`
	// Amazon S3 / Amazon Glacier
	AwsPreferredStorage *string `json:"aws_preferred_storage,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ReplicationpoliciesCreateRequest ReplicationpoliciesCreateRequest

// NewReplicationpoliciesCreateRequest instantiates a new ReplicationpoliciesCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReplicationpoliciesCreateRequest(name string, replicationTargetId int32) *ReplicationpoliciesCreateRequest {
	this := ReplicationpoliciesCreateRequest{}
	this.Name = name
	this.ReplicationTargetId = replicationTargetId
	return &this
}

// NewReplicationpoliciesCreateRequestWithDefaults instantiates a new ReplicationpoliciesCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReplicationpoliciesCreateRequestWithDefaults() *ReplicationpoliciesCreateRequest {
	this := ReplicationpoliciesCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *ReplicationpoliciesCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ReplicationpoliciesCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ReplicationpoliciesCreateRequest) SetName(v string) {
	o.Name = v
}

// GetScheduleFrequency returns the ScheduleFrequency field value if set, zero value otherwise.
func (o *ReplicationpoliciesCreateRequest) GetScheduleFrequency() time.Time {
	if o == nil || IsNil(o.ScheduleFrequency) {
		var ret time.Time
		return ret
	}
	return *o.ScheduleFrequency
}

// GetScheduleFrequencyOk returns a tuple with the ScheduleFrequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplicationpoliciesCreateRequest) GetScheduleFrequencyOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ScheduleFrequency) {
		return nil, false
	}
	return o.ScheduleFrequency, true
}

// HasScheduleFrequency returns a boolean if a field has been set.
func (o *ReplicationpoliciesCreateRequest) HasScheduleFrequency() bool {
	if o != nil && !IsNil(o.ScheduleFrequency) {
		return true
	}

	return false
}

// SetScheduleFrequency gets a reference to the given time.Time and assigns it to the ScheduleFrequency field.
func (o *ReplicationpoliciesCreateRequest) SetScheduleFrequency(v time.Time) {
	o.ScheduleFrequency = &v
}

// GetScheduleStartTime returns the ScheduleStartTime field value if set, zero value otherwise.
func (o *ReplicationpoliciesCreateRequest) GetScheduleStartTime() time.Time {
	if o == nil || IsNil(o.ScheduleStartTime) {
		var ret time.Time
		return ret
	}
	return *o.ScheduleStartTime
}

// GetScheduleStartTimeOk returns a tuple with the ScheduleStartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplicationpoliciesCreateRequest) GetScheduleStartTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ScheduleStartTime) {
		return nil, false
	}
	return o.ScheduleStartTime, true
}

// HasScheduleStartTime returns a boolean if a field has been set.
func (o *ReplicationpoliciesCreateRequest) HasScheduleStartTime() bool {
	if o != nil && !IsNil(o.ScheduleStartTime) {
		return true
	}

	return false
}

// SetScheduleStartTime gets a reference to the given time.Time and assigns it to the ScheduleStartTime field.
func (o *ReplicationpoliciesCreateRequest) SetScheduleStartTime(v time.Time) {
	o.ScheduleStartTime = &v
}

// GetReplicationTargetId returns the ReplicationTargetId field value
func (o *ReplicationpoliciesCreateRequest) GetReplicationTargetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReplicationTargetId
}

// GetReplicationTargetIdOk returns a tuple with the ReplicationTargetId field value
// and a boolean to check if the value has been set.
func (o *ReplicationpoliciesCreateRequest) GetReplicationTargetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReplicationTargetId, true
}

// SetReplicationTargetId sets field value
func (o *ReplicationpoliciesCreateRequest) SetReplicationTargetId(v int32) {
	o.ReplicationTargetId = v
}

// GetBandwidthLimitationRules returns the BandwidthLimitationRules field value if set, zero value otherwise.
func (o *ReplicationpoliciesCreateRequest) GetBandwidthLimitationRules() string {
	if o == nil || IsNil(o.BandwidthLimitationRules) {
		var ret string
		return ret
	}
	return *o.BandwidthLimitationRules
}

// GetBandwidthLimitationRulesOk returns a tuple with the BandwidthLimitationRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplicationpoliciesCreateRequest) GetBandwidthLimitationRulesOk() (*string, bool) {
	if o == nil || IsNil(o.BandwidthLimitationRules) {
		return nil, false
	}
	return o.BandwidthLimitationRules, true
}

// HasBandwidthLimitationRules returns a boolean if a field has been set.
func (o *ReplicationpoliciesCreateRequest) HasBandwidthLimitationRules() bool {
	if o != nil && !IsNil(o.BandwidthLimitationRules) {
		return true
	}

	return false
}

// SetBandwidthLimitationRules gets a reference to the given string and assigns it to the BandwidthLimitationRules field.
func (o *ReplicationpoliciesCreateRequest) SetBandwidthLimitationRules(v string) {
	o.BandwidthLimitationRules = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *ReplicationpoliciesCreateRequest) GetPriority() string {
	if o == nil || IsNil(o.Priority) {
		var ret string
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplicationpoliciesCreateRequest) GetPriorityOk() (*string, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *ReplicationpoliciesCreateRequest) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given string and assigns it to the Priority field.
func (o *ReplicationpoliciesCreateRequest) SetPriority(v string) {
	o.Priority = &v
}

// GetAwsPreferredStorage returns the AwsPreferredStorage field value if set, zero value otherwise.
func (o *ReplicationpoliciesCreateRequest) GetAwsPreferredStorage() string {
	if o == nil || IsNil(o.AwsPreferredStorage) {
		var ret string
		return ret
	}
	return *o.AwsPreferredStorage
}

// GetAwsPreferredStorageOk returns a tuple with the AwsPreferredStorage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReplicationpoliciesCreateRequest) GetAwsPreferredStorageOk() (*string, bool) {
	if o == nil || IsNil(o.AwsPreferredStorage) {
		return nil, false
	}
	return o.AwsPreferredStorage, true
}

// HasAwsPreferredStorage returns a boolean if a field has been set.
func (o *ReplicationpoliciesCreateRequest) HasAwsPreferredStorage() bool {
	if o != nil && !IsNil(o.AwsPreferredStorage) {
		return true
	}

	return false
}

// SetAwsPreferredStorage gets a reference to the given string and assigns it to the AwsPreferredStorage field.
func (o *ReplicationpoliciesCreateRequest) SetAwsPreferredStorage(v string) {
	o.AwsPreferredStorage = &v
}

func (o ReplicationpoliciesCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReplicationpoliciesCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.ScheduleFrequency) {
		toSerialize["schedule_frequency"] = o.ScheduleFrequency
	}
	if !IsNil(o.ScheduleStartTime) {
		toSerialize["schedule_start_time"] = o.ScheduleStartTime
	}
	toSerialize["replication_target_id"] = o.ReplicationTargetId
	if !IsNil(o.BandwidthLimitationRules) {
		toSerialize["bandwidth_limitation_rules"] = o.BandwidthLimitationRules
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.AwsPreferredStorage) {
		toSerialize["aws_preferred_storage"] = o.AwsPreferredStorage
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ReplicationpoliciesCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"replication_target_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReplicationpoliciesCreateRequest := _ReplicationpoliciesCreateRequest{}

	err = json.Unmarshal(data, &varReplicationpoliciesCreateRequest)

	if err != nil {
		return err
	}

	*o = ReplicationpoliciesCreateRequest(varReplicationpoliciesCreateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "schedule_frequency")
		delete(additionalProperties, "schedule_start_time")
		delete(additionalProperties, "replication_target_id")
		delete(additionalProperties, "bandwidth_limitation_rules")
		delete(additionalProperties, "priority")
		delete(additionalProperties, "aws_preferred_storage")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableReplicationpoliciesCreateRequest struct {
	value *ReplicationpoliciesCreateRequest
	isSet bool
}

func (v NullableReplicationpoliciesCreateRequest) Get() *ReplicationpoliciesCreateRequest {
	return v.value
}

func (v *NullableReplicationpoliciesCreateRequest) Set(val *ReplicationpoliciesCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableReplicationpoliciesCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableReplicationpoliciesCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplicationpoliciesCreateRequest(val *ReplicationpoliciesCreateRequest) *NullableReplicationpoliciesCreateRequest {
	return &NullableReplicationpoliciesCreateRequest{value: val, isSet: true}
}

func (v NullableReplicationpoliciesCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplicationpoliciesCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


