/*
VAST API Swagger Schema

VAST Management API definition

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProtectedpathsValidate200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProtectedpathsValidate200Response{}

// ProtectedpathsValidate200Response struct for ProtectedpathsValidate200Response
type ProtectedpathsValidate200Response struct {
	// Views paths with s3_versioning enabled.
	S3Versioning []string `json:"s3_versioning,omitempty"`
	// Protected Path or one of it's descendants is replication source
	IsSourcePpath *bool `json:"is_source_ppath,omitempty"`
	// Protected Path or one of it's descendants is replication destination
	IsDestPpath *bool `json:"is_dest_ppath,omitempty"`
	// Is system multi-tenant
	IsMultiTenantSystem *bool `json:"is_multi_tenant_system,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ProtectedpathsValidate200Response ProtectedpathsValidate200Response

// NewProtectedpathsValidate200Response instantiates a new ProtectedpathsValidate200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtectedpathsValidate200Response() *ProtectedpathsValidate200Response {
	this := ProtectedpathsValidate200Response{}
	return &this
}

// NewProtectedpathsValidate200ResponseWithDefaults instantiates a new ProtectedpathsValidate200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtectedpathsValidate200ResponseWithDefaults() *ProtectedpathsValidate200Response {
	this := ProtectedpathsValidate200Response{}
	return &this
}

// GetS3Versioning returns the S3Versioning field value if set, zero value otherwise.
func (o *ProtectedpathsValidate200Response) GetS3Versioning() []string {
	if o == nil || IsNil(o.S3Versioning) {
		var ret []string
		return ret
	}
	return o.S3Versioning
}

// GetS3VersioningOk returns a tuple with the S3Versioning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectedpathsValidate200Response) GetS3VersioningOk() ([]string, bool) {
	if o == nil || IsNil(o.S3Versioning) {
		return nil, false
	}
	return o.S3Versioning, true
}

// HasS3Versioning returns a boolean if a field has been set.
func (o *ProtectedpathsValidate200Response) HasS3Versioning() bool {
	if o != nil && !IsNil(o.S3Versioning) {
		return true
	}

	return false
}

// SetS3Versioning gets a reference to the given []string and assigns it to the S3Versioning field.
func (o *ProtectedpathsValidate200Response) SetS3Versioning(v []string) {
	o.S3Versioning = v
}

// GetIsSourcePpath returns the IsSourcePpath field value if set, zero value otherwise.
func (o *ProtectedpathsValidate200Response) GetIsSourcePpath() bool {
	if o == nil || IsNil(o.IsSourcePpath) {
		var ret bool
		return ret
	}
	return *o.IsSourcePpath
}

// GetIsSourcePpathOk returns a tuple with the IsSourcePpath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectedpathsValidate200Response) GetIsSourcePpathOk() (*bool, bool) {
	if o == nil || IsNil(o.IsSourcePpath) {
		return nil, false
	}
	return o.IsSourcePpath, true
}

// HasIsSourcePpath returns a boolean if a field has been set.
func (o *ProtectedpathsValidate200Response) HasIsSourcePpath() bool {
	if o != nil && !IsNil(o.IsSourcePpath) {
		return true
	}

	return false
}

// SetIsSourcePpath gets a reference to the given bool and assigns it to the IsSourcePpath field.
func (o *ProtectedpathsValidate200Response) SetIsSourcePpath(v bool) {
	o.IsSourcePpath = &v
}

// GetIsDestPpath returns the IsDestPpath field value if set, zero value otherwise.
func (o *ProtectedpathsValidate200Response) GetIsDestPpath() bool {
	if o == nil || IsNil(o.IsDestPpath) {
		var ret bool
		return ret
	}
	return *o.IsDestPpath
}

// GetIsDestPpathOk returns a tuple with the IsDestPpath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectedpathsValidate200Response) GetIsDestPpathOk() (*bool, bool) {
	if o == nil || IsNil(o.IsDestPpath) {
		return nil, false
	}
	return o.IsDestPpath, true
}

// HasIsDestPpath returns a boolean if a field has been set.
func (o *ProtectedpathsValidate200Response) HasIsDestPpath() bool {
	if o != nil && !IsNil(o.IsDestPpath) {
		return true
	}

	return false
}

// SetIsDestPpath gets a reference to the given bool and assigns it to the IsDestPpath field.
func (o *ProtectedpathsValidate200Response) SetIsDestPpath(v bool) {
	o.IsDestPpath = &v
}

// GetIsMultiTenantSystem returns the IsMultiTenantSystem field value if set, zero value otherwise.
func (o *ProtectedpathsValidate200Response) GetIsMultiTenantSystem() bool {
	if o == nil || IsNil(o.IsMultiTenantSystem) {
		var ret bool
		return ret
	}
	return *o.IsMultiTenantSystem
}

// GetIsMultiTenantSystemOk returns a tuple with the IsMultiTenantSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProtectedpathsValidate200Response) GetIsMultiTenantSystemOk() (*bool, bool) {
	if o == nil || IsNil(o.IsMultiTenantSystem) {
		return nil, false
	}
	return o.IsMultiTenantSystem, true
}

// HasIsMultiTenantSystem returns a boolean if a field has been set.
func (o *ProtectedpathsValidate200Response) HasIsMultiTenantSystem() bool {
	if o != nil && !IsNil(o.IsMultiTenantSystem) {
		return true
	}

	return false
}

// SetIsMultiTenantSystem gets a reference to the given bool and assigns it to the IsMultiTenantSystem field.
func (o *ProtectedpathsValidate200Response) SetIsMultiTenantSystem(v bool) {
	o.IsMultiTenantSystem = &v
}

func (o ProtectedpathsValidate200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProtectedpathsValidate200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.S3Versioning) {
		toSerialize["s3_versioning"] = o.S3Versioning
	}
	if !IsNil(o.IsSourcePpath) {
		toSerialize["is_source_ppath"] = o.IsSourcePpath
	}
	if !IsNil(o.IsDestPpath) {
		toSerialize["is_dest_ppath"] = o.IsDestPpath
	}
	if !IsNil(o.IsMultiTenantSystem) {
		toSerialize["is_multi_tenant_system"] = o.IsMultiTenantSystem
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ProtectedpathsValidate200Response) UnmarshalJSON(data []byte) (err error) {
	varProtectedpathsValidate200Response := _ProtectedpathsValidate200Response{}

	err = json.Unmarshal(data, &varProtectedpathsValidate200Response)

	if err != nil {
		return err
	}

	*o = ProtectedpathsValidate200Response(varProtectedpathsValidate200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "s3_versioning")
		delete(additionalProperties, "is_source_ppath")
		delete(additionalProperties, "is_dest_ppath")
		delete(additionalProperties, "is_multi_tenant_system")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableProtectedpathsValidate200Response struct {
	value *ProtectedpathsValidate200Response
	isSet bool
}

func (v NullableProtectedpathsValidate200Response) Get() *ProtectedpathsValidate200Response {
	return v.value
}

func (v *NullableProtectedpathsValidate200Response) Set(val *ProtectedpathsValidate200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableProtectedpathsValidate200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableProtectedpathsValidate200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtectedpathsValidate200Response(val *ProtectedpathsValidate200Response) *NullableProtectedpathsValidate200Response {
	return &NullableProtectedpathsValidate200Response{value: val, isSet: true}
}

func (v NullableProtectedpathsValidate200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtectedpathsValidate200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


